items:
- uid: com.microsoft.azure.management.website._cors_settings
  id: _cors_settings
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._cors_settings.allowedOrigins()
  - com.microsoft.azure.management.website._cors_settings.withAllowedOrigins(List<String>)
  href: com.microsoft.azure.management.website._cors_settings.yml
  langs:
  - java
  name: CorsSettings
  fullName: com.microsoft.azure.management.website.CorsSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/CorsSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/CorsSettings.java
    startLine: 15
  package: com.microsoft.azure.management.website
  summary: <p>Cross-Origin Resource Sharing (CORS) settings for the web app. </p>
  syntax: &o1
    content: public class CorsSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._cors_settings.allowedOrigins()
  id: allowedOrigins()
  parent: com.microsoft.azure.management.website._cors_settings
  href: com.microsoft.azure.management.website._cors_settings.yml
  langs:
  - java
  name: allowedOrigins()
  fullName: List<String> com.microsoft.azure.management.website.CorsSettings.allowedOrigins()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/CorsSettings.java
    startLine: 29
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the allowedOrigins value.</p>

    <p></p>
  syntax:
    content: public List<String> allowedOrigins()
    return:
      type: 7d60c20e
      description: <p>the allowedOrigins value </p>
- uid: com.microsoft.azure.management.website._cors_settings.withAllowedOrigins(List<String>)
  id: withAllowedOrigins(List<String>)
  parent: com.microsoft.azure.management.website._cors_settings
  href: com.microsoft.azure.management.website._cors_settings.yml
  langs:
  - java
  name: withAllowedOrigins(List<String> allowedOrigins)
  fullName: CorsSettings com.microsoft.azure.management.website.CorsSettings.withAllowedOrigins(List<String> allowedOrigins)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/CorsSettings.java
    startLine: 39
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the allowedOrigins value.</p>

    <p></p>
  syntax:
    content: public CorsSettings withAllowedOrigins(List<String> allowedOrigins)
    parameters:
    - id: allowedOrigins
      type: 7d60c20e
      description: <p>the allowedOrigins value to set </p>
    return:
      type: com.microsoft.azure.management.website._cors_settings
      description: <p>the <xref href="com.microsoft.azure.management.website._cors_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 7d60c20e
  spec.java:
  - name: List<String>
    fullName: List<String>
- uid: com.microsoft.azure.management.website._cors_settings
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._cors_settings.yml
  name: CorsSettings
  fullName: com.microsoft.azure.management.website.CorsSettings
  type: Class
  summary: <p>Cross-Origin Resource Sharing (CORS) settings for the web app. </p>
  syntax: *o1
