items:
- uid: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations
  id: _with_configurations
  parent: com.microsoft.azure.management.keyvault
  children:
  - com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDeploymentDisabled()
  - com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDeploymentEnabled()
  - com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDiskEncryptionDisabled()
  - com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDiskEncryptionEnabled()
  - com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withTemplateDeploymentDisabled()
  - com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withTemplateDeploymentEnabled()
  href: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.yml
  langs:
  - java
  name: Vault.UpdateStages.WithConfigurations
  fullName: com.microsoft.azure.management.keyvault.Vault.UpdateStages.WithConfigurations
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 246
  package: com.microsoft.azure.management.keyvault
  summary: <p>A key vault update allowing various configurations to be set. </p>
  syntax:
    content: public interface WithConfigurations
- uid: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDeploymentDisabled()
  id: withDeploymentDisabled()
  parent: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.yml
  langs:
  - java
  name: withDeploymentDisabled()
  fullName: Update com.microsoft.azure.management.keyvault.Vault.UpdateStages.WithConfigurations.withDeploymentDisabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 273
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Disable <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Virtual Machines to retrieve certificates stored as secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public Update withDeploymentDisabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._update
      description: <p>the key vault update stage </p>
- uid: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDeploymentEnabled()
  id: withDeploymentEnabled()
  parent: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.yml
  langs:
  - java
  name: withDeploymentEnabled()
  fullName: Update com.microsoft.azure.management.keyvault.Vault.UpdateStages.WithConfigurations.withDeploymentEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 252
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Enable <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Virtual Machines to retrieve certificates stored as secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public Update withDeploymentEnabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._update
      description: <p>the key vault update stage </p>
- uid: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDiskEncryptionDisabled()
  id: withDiskEncryptionDisabled()
  parent: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.yml
  langs:
  - java
  name: withDiskEncryptionDisabled()
  fullName: Update com.microsoft.azure.management.keyvault.Vault.UpdateStages.WithConfigurations.withDiskEncryptionDisabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 280
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Disable <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Disk Encryption to retrieve secrets from the vault and unwrap keys.</p>

    <p></p>
  syntax:
    content: public Update withDiskEncryptionDisabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._update
      description: <p>the next stage of key vault definition </p>
- uid: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withDiskEncryptionEnabled()
  id: withDiskEncryptionEnabled()
  parent: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.yml
  langs:
  - java
  name: withDiskEncryptionEnabled()
  fullName: Update com.microsoft.azure.management.keyvault.Vault.UpdateStages.WithConfigurations.withDiskEncryptionEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 259
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Enable <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Disk Encryption to retrieve secrets from the vault and unwrap keys.</p>

    <p></p>
  syntax:
    content: public Update withDiskEncryptionEnabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._update
      description: <p>the key vault update stage </p>
- uid: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withTemplateDeploymentDisabled()
  id: withTemplateDeploymentDisabled()
  parent: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.yml
  langs:
  - java
  name: withTemplateDeploymentDisabled()
  fullName: Update com.microsoft.azure.management.keyvault.Vault.UpdateStages.WithConfigurations.withTemplateDeploymentDisabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 287
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Disable <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Resource Manager to retrieve secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public Update withTemplateDeploymentDisabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._update
      description: <p>the key vault update stage </p>
- uid: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.withTemplateDeploymentEnabled()
  id: withTemplateDeploymentEnabled()
  parent: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._update_stages._with_configurations.yml
  langs:
  - java
  name: withTemplateDeploymentEnabled()
  fullName: Update com.microsoft.azure.management.keyvault.Vault.UpdateStages.WithConfigurations.withTemplateDeploymentEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 266
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Enable <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Resource Manager to retrieve secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public Update withTemplateDeploymentEnabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._update
      description: <p>the key vault update stage </p>
references:
- uid: com.microsoft.azure.management.keyvault._vault._update
  parent: com.microsoft.azure.management.keyvault
  href: com.microsoft.azure.management.keyvault._vault._update.yml
  name: Vault.Update
  fullName: com.microsoft.azure.management.keyvault.Vault.Update
  type: Interface
  summary: <p>The template for a key vault update operation, containing all the settings that can be modified. </p>
  syntax:
    content: public interface Update extends Appliable< Vault >,Vault.UpdateStages.WithAccessPolicy,Vault.UpdateStages.WithConfigurations
- uid: com.microsoft.azure.management._azure
  parent: com.microsoft.azure.management
  href: com.microsoft.azure.management._azure.yml
  name: Azure
  fullName: com.microsoft.azure.management.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
