items:
- uid: com.microsoft.azure.management.network._application_gateway_request_rout1e7b246db500e86cbff5d15699b118ee
  id: _application_gateway_request_rout1e7b246db500e86cbff5d15699b118ee
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_rout1e7b246db500e86cbff5d15699b118ee.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRule.DefinitionStages.WithCookieBasedAffinity<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.DefinitionStages.WithCookieBasedAffinity<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
    startLine: 193
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway request routing rule allowing to enable cookie based affinity. </p>
  syntax:
    content: public interface WithCookieBasedAffinity<ParentT> extends HasCookieBasedAffinity.DefinitionStages.WithCookieBasedAffinity<WithAttach<ParentT>>
    typeParameters:
    - type: 18a275b1
      description: <p>the next stage of the definition </p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a.withCookieBasedAffinity()
  - com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a.withoutCookieBasedAffinity()
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a.withCookieBasedAffinity()
  parent: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a
  href: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a.yml
  name: withCookieBasedAffinity()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasCookieBasedAffinity.DefinitionStages.WithCookieBasedAffinity<ReturnT>.withCookieBasedAffinity()
  type: Method
  summary: <p>Enables cookie based affinity. </p>
  syntax:
    content: public ReturnT withCookieBasedAffinity()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a.withoutCookieBasedAffinity()
  parent: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a
  href: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a.yml
  name: withoutCookieBasedAffinity()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasCookieBasedAffinity.DefinitionStages.WithCookieBasedAffinity<ReturnT>.withoutCookieBasedAffinity()
  type: Method
  summary: <p>Disables cookie based affinity. </p>
  syntax:
    content: public ReturnT withoutCookieBasedAffinity()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_cookie_based_affini6d82ff85198c4a172e7754a6e1aee68a.yml
  name: HasCookieBasedAffinity.DefinitionStages.WithCookieBasedAffinity<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasCookieBasedAffinity.DefinitionStages.WithCookieBasedAffinity<ReturnT>
  type: Interface
  summary: <p>The stage of a definition allowing to enable cookie based affinity. </p>
  syntax:
    content: public interface WithCookieBasedAffinity<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_rout79226060d889eae4c50b7b0e5d684f28
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_rout79226060d889eae4c50b7b0e5d684f28.yml
  name: ApplicationGatewayRequestRoutingRule.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway request routing rule definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition,ApplicationGatewayRequestRoutingRule.DefinitionStages.WithHostName<ParentT>,ApplicationGatewayRequestRoutingRule.DefinitionStages.WithCookieBasedAffinity<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the application gateway definition to return to after attaching this definition </p>
