items:
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config
  id: _express_route_circuit_peering_config
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.advertisedPublicPrefixes()
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.advertisedPublicPrefixesState()
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.customerASN()
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.routingRegistryName()
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.withAdvertisedPublicPrefixes(List< String >)
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.withAdvertisedPublicPrefixesState(ExpressRouteCircuitPeeringAdvertisedPublicPrefixState)
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.withCustomerASN(Integer)
  - com.microsoft.azure.management.network._express_route_circuit_peering_config.withRoutingRegistryName(String)
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: ExpressRouteCircuitPeeringConfig
  fullName: com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the peering config. </p>
  syntax: &o1
    content: public class ExpressRouteCircuitPeeringConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.advertisedPublicPrefixes()
  id: advertisedPublicPrefixes()
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: advertisedPublicPrefixes()
  fullName: List<String> com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.advertisedPublicPrefixes()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 43
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the advertisedPublicPrefixes value.</p>

    <p></p>
  syntax:
    content: public List< String > advertisedPublicPrefixes()
    return:
      type: f35af49b
      description: <p>the advertisedPublicPrefixes value </p>
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.advertisedPublicPrefixesState()
  id: advertisedPublicPrefixesState()
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: advertisedPublicPrefixesState()
  fullName: ExpressRouteCircuitPeeringAdvertisedPublicPrefixState com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.advertisedPublicPrefixesState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 63
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the advertisedPublicPrefixesState value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringAdvertisedPublicPrefixState advertisedPublicPrefixesState()
    return:
      type: com.microsoft.azure.management.network._express_route_circuit_peering_advertised_public_prefix_state
      description: <p>the advertisedPublicPrefixesState value </p>
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.customerASN()
  id: customerASN()
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: customerASN()
  fullName: Integer com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.customerASN()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 83
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the customerASN value.</p>

    <p></p>
  syntax:
    content: public Integer customerASN()
    return:
      type: 08effaa0
      description: <p>the customerASN value </p>
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.routingRegistryName()
  id: routingRegistryName()
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: routingRegistryName()
  fullName: String com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.routingRegistryName()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 103
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the routingRegistryName value.</p>

    <p></p>
  syntax:
    content: public String routingRegistryName()
    return:
      type: "26831127"
      description: <p>the routingRegistryName value </p>
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.withAdvertisedPublicPrefixes(List< String >)
  id: withAdvertisedPublicPrefixes(List< String >)
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withAdvertisedPublicPrefixes(List< String > advertisedPublicPrefixes)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.withAdvertisedPublicPrefixes(List< String > advertisedPublicPrefixes)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 53
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the advertisedPublicPrefixes value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withAdvertisedPublicPrefixes(List< String > advertisedPublicPrefixes)
    parameters:
    - id: advertisedPublicPrefixes
      type: f35af49b
      description: <p>the advertisedPublicPrefixes value to set </p>
    return:
      type: com.microsoft.azure.management.network._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.withAdvertisedPublicPrefixesState(ExpressRouteCircuitPeeringAdvertisedPublicPrefixState)
  id: withAdvertisedPublicPrefixesState(ExpressRouteCircuitPeeringAdvertisedPublicPrefixState)
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withAdvertisedPublicPrefixesState(ExpressRouteCircuitPeeringAdvertisedPublicPrefixState advertisedPublicPrefixesState)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.withAdvertisedPublicPrefixesState(ExpressRouteCircuitPeeringAdvertisedPublicPrefixState advertisedPublicPrefixesState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 73
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the advertisedPublicPrefixesState value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withAdvertisedPublicPrefixesState(ExpressRouteCircuitPeeringAdvertisedPublicPrefixState advertisedPublicPrefixesState)
    parameters:
    - id: advertisedPublicPrefixesState
      type: com.microsoft.azure.management.network._express_route_circuit_peering_advertised_public_prefix_state
      description: <p>the advertisedPublicPrefixesState value to set </p>
    return:
      type: com.microsoft.azure.management.network._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.withCustomerASN(Integer)
  id: withCustomerASN(Integer)
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withCustomerASN(Integer customerASN)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.withCustomerASN(Integer customerASN)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 93
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the customerASN value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withCustomerASN(Integer customerASN)
    parameters:
    - id: customerASN
      type: 08effaa0
      description: <p>the customerASN value to set </p>
    return:
      type: com.microsoft.azure.management.network._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config.withRoutingRegistryName(String)
  id: withRoutingRegistryName(String)
  parent: com.microsoft.azure.management.network._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withRoutingRegistryName(String routingRegistryName)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig.withRoutingRegistryName(String routingRegistryName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ExpressRouteCircuitPeeringConfig.java
    startLine: 113
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the routingRegistryName value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withRoutingRegistryName(String routingRegistryName)
    parameters:
    - id: routingRegistryName
      type: "26831127"
      description: <p>the routingRegistryName value to set </p>
    return:
      type: com.microsoft.azure.management.network._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_advertised_public_prefix_state
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._express_route_circuit_peering_advertised_public_prefix_state.yml
  name: ExpressRouteCircuitPeeringAdvertisedPublicPrefixState
  fullName: com.microsoft.azure.management.network.ExpressRouteCircuitPeeringAdvertisedPublicPrefixState
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._express_route_circuit_peering_advertised_public_prefix_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ExpressRouteCircuitPeeringAdvertisedPublicPrefixState
- uid: com.microsoft.azure.management.network._express_route_circuit_peering_config
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._express_route_circuit_peering_config.yml
  name: ExpressRouteCircuitPeeringConfig
  fullName: com.microsoft.azure.management.network.ExpressRouteCircuitPeeringConfig
  type: Class
  summary: <p>Specifies the peering config. </p>
  syntax: *o1
