items:
- uid: com.microsoft.azure.management.compute._ssh_configuration
  id: _ssh_configuration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._ssh_configuration.publicKeys()
  - com.microsoft.azure.management.compute._ssh_configuration.withPublicKeys(List<SshPublicKey>)
  href: com.microsoft.azure.management.compute._ssh_configuration.yml
  langs:
  - java
  name: SshConfiguration
  fullName: com.microsoft.azure.management.compute.SshConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
    startLine: 15
  package: com.microsoft.azure.management.compute
  summary: <p>SSH configuration for Linux based VMs running on <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class SshConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute._ssh_configuration.publicKeys()
  id: publicKeys()
  parent: com.microsoft.azure.management.compute._ssh_configuration
  href: com.microsoft.azure.management.compute._ssh_configuration.yml
  langs:
  - java
  name: publicKeys()
  fullName: List<SshPublicKey> com.microsoft.azure.management.compute.SshConfiguration.publicKeys()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
    startLine: 26
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the publicKeys value.</p>

    <p></p>
  syntax:
    content: public List<SshPublicKey> publicKeys()
    return:
      type: 5618da2dcom.microsoft.azure.management.compute._ssh_public_keya08ddfce
      description: <p>the publicKeys value </p>
- uid: com.microsoft.azure.management.compute._ssh_configuration.withPublicKeys(List<SshPublicKey>)
  id: withPublicKeys(List<SshPublicKey>)
  parent: com.microsoft.azure.management.compute._ssh_configuration
  href: com.microsoft.azure.management.compute._ssh_configuration.yml
  langs:
  - java
  name: withPublicKeys(List<SshPublicKey> publicKeys)
  fullName: SshConfiguration com.microsoft.azure.management.compute.SshConfiguration.withPublicKeys(List<SshPublicKey> publicKeys)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
    startLine: 36
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the publicKeys value.</p>

    <p></p>
  syntax:
    content: public SshConfiguration withPublicKeys(List<SshPublicKey> publicKeys)
    parameters:
    - id: publicKeys
      type: 5618da2dcom.microsoft.azure.management.compute._ssh_public_keya08ddfce
      description: <p>the publicKeys value to set </p>
    return:
      type: com.microsoft.azure.management.compute._ssh_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._ssh_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 5618da2dcom.microsoft.azure.management.compute._ssh_public_keya08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.management.compute._ssh_public_key
    name: SshPublicKey
    fullName: com.microsoft.azure.management.compute.SshPublicKey
    href: com.microsoft.azure.management.compute._ssh_public_key.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.compute._ssh_public_key
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._ssh_public_key.yml
  name: SshPublicKey
  fullName: com.microsoft.azure.management.compute.SshPublicKey
  type: Class
  summary: <p>Contains information about SSH certificate public key and the path on the Linux VM where the public key is placed. </p>
  syntax:
    content: public class SshPublicKey
- uid: com.microsoft.azure.management.compute._ssh_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._ssh_configuration.yml
  name: SshConfiguration
  fullName: com.microsoft.azure.management.compute.SshConfiguration
  type: Class
  summary: <p>SSH configuration for Linux based VMs running on <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
- uid: com.microsoft.azure.management._azure
  parent: com.microsoft.azure.management
  href: com.microsoft.azure.management._azure.yml
  name: Azure
  fullName: com.microsoft.azure.management.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
