items:
- uid: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner
  id: _deployment_export_result_inner
  parent: com.microsoft.azure.management.resources.implementation
  children:
  - com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.template()
  - com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.withTemplate(Object)
  href: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.yml
  langs:
  - java
  name: DeploymentExportResultInner
  fullName: com.microsoft.azure.management.resources.implementation.DeploymentExportResultInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentExportResultInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentExportResultInner.java
    startLine: 14
  package: com.microsoft.azure.management.resources.implementation
  summary: <p>The <xref href="com.microsoft.azure.management.resources.implementation._deployment_export_result_inner" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: &o1
    content: public class DeploymentExportResultInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.template()
  id: template()
  parent: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner
  href: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.yml
  langs:
  - java
  name: template()
  fullName: Object com.microsoft.azure.management.resources.implementation.DeploymentExportResultInner.template()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentExportResultInner.java
    startLine: 25
  package: com.microsoft.azure.management.resources.implementation
  summary: >-
    <p>Get the template value.</p>

    <p></p>
  syntax:
    content: public Object template()
    return:
      type: "79317049"
      description: <p>the template value </p>
- uid: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.withTemplate(Object)
  id: withTemplate(Object)
  parent: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner
  href: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.yml
  langs:
  - java
  name: withTemplate(Object template)
  fullName: DeploymentExportResultInner com.microsoft.azure.management.resources.implementation.DeploymentExportResultInner.withTemplate(Object template)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentExportResultInner.java
    startLine: 35
  package: com.microsoft.azure.management.resources.implementation
  summary: >-
    <p>Set the template value.</p>

    <p></p>
  syntax:
    content: public DeploymentExportResultInner withTemplate(Object template)
    parameters:
    - id: template
      type: "79317049"
      description: <p>the template value to set </p>
    return:
      type: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner
      description: <p>the <xref href="com.microsoft.azure.management.resources.implementation._deployment_export_result_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner
  parent: com.microsoft.azure.management.resources.implementation
  href: com.microsoft.azure.management.resources.implementation._deployment_export_result_inner.yml
  name: DeploymentExportResultInner
  fullName: com.microsoft.azure.management.resources.implementation.DeploymentExportResultInner
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.resources.implementation._deployment_export_result_inner" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: *o1
