items:
- uid: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746
  id: _update_definition_af002c8421e16b745af55a95ece4e746
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746.defineNewApplicationPackage(String)
  href: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746.yml
  langs:
  - java
  name: Application.UpdateDefinitionStages.WithApplicationPackage<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.WithApplicationPackage<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 141
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>A application definition to allow creation of application package.</p>

    <p></p>
  syntax:
    content: public interface WithApplicationPackage<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746.defineNewApplicationPackage(String)
  id: defineNewApplicationPackage(String)
  parent: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746
  href: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746.yml
  langs:
  - java
  name: defineNewApplicationPackage(String version)
  fullName: UpdateDefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.WithApplicationPackage<ParentT>.defineNewApplicationPackage(String version)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 148
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>First stage to create new application package in Batch account application.</p>

    <p></p>
  syntax:
    content: public UpdateDefinitionStages.WithAttach<ParentT> defineNewApplicationPackage(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version of the application </p>
    return:
      type: 302b4b76
      description: <p>next stage to create the application. </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 302b4b76
  spec.java:
  - name: UpdateDefinitionStages.WithAttach<ParentT>
    fullName: UpdateDefinitionStages.WithAttach<ParentT>
- uid: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.yml
  name: Application.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of the application definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the application definition can be attached to the parent batch account definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
