items:
- uid: com.microsoft.azure.management.network._bgp_settings
  id: _bgp_settings
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._bgp_settings.asn()
  - com.microsoft.azure.management.network._bgp_settings.bgpPeeringAddress()
  - com.microsoft.azure.management.network._bgp_settings.peerWeight()
  - com.microsoft.azure.management.network._bgp_settings.withAsn(Long)
  - com.microsoft.azure.management.network._bgp_settings.withBgpPeeringAddress(String)
  - com.microsoft.azure.management.network._bgp_settings.withPeerWeight(Integer)
  href: com.microsoft.azure.management.network._bgp_settings.yml
  langs:
  - java
  name: BgpSettings
  fullName: com.microsoft.azure.management.network.BgpSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
    startLine: 14
  package: com.microsoft.azure.management.network
  summary: <p>The <xref href="com.microsoft.azure.management.network._bgp_settings" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: &o1
    content: public class BgpSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._bgp_settings.asn()
  id: asn()
  parent: com.microsoft.azure.management.network._bgp_settings
  href: com.microsoft.azure.management.network._bgp_settings.yml
  langs:
  - java
  name: asn()
  fullName: Long com.microsoft.azure.management.network.BgpSettings.asn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
    startLine: 36
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the asn value.</p>

    <p></p>
  syntax:
    content: public Long asn()
    return:
      type: 34f09483
      description: <p>the asn value </p>
- uid: com.microsoft.azure.management.network._bgp_settings.bgpPeeringAddress()
  id: bgpPeeringAddress()
  parent: com.microsoft.azure.management.network._bgp_settings
  href: com.microsoft.azure.management.network._bgp_settings.yml
  langs:
  - java
  name: bgpPeeringAddress()
  fullName: String com.microsoft.azure.management.network.BgpSettings.bgpPeeringAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
    startLine: 56
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the bgpPeeringAddress value.</p>

    <p></p>
  syntax:
    content: public String bgpPeeringAddress()
    return:
      type: "26831127"
      description: <p>the bgpPeeringAddress value </p>
- uid: com.microsoft.azure.management.network._bgp_settings.peerWeight()
  id: peerWeight()
  parent: com.microsoft.azure.management.network._bgp_settings
  href: com.microsoft.azure.management.network._bgp_settings.yml
  langs:
  - java
  name: peerWeight()
  fullName: Integer com.microsoft.azure.management.network.BgpSettings.peerWeight()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
    startLine: 76
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the peerWeight value.</p>

    <p></p>
  syntax:
    content: public Integer peerWeight()
    return:
      type: 08effaa0
      description: <p>the peerWeight value </p>
- uid: com.microsoft.azure.management.network._bgp_settings.withAsn(Long)
  id: withAsn(Long)
  parent: com.microsoft.azure.management.network._bgp_settings
  href: com.microsoft.azure.management.network._bgp_settings.yml
  langs:
  - java
  name: withAsn(Long asn)
  fullName: BgpSettings com.microsoft.azure.management.network.BgpSettings.withAsn(Long asn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
    startLine: 46
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the asn value.</p>

    <p></p>
  syntax:
    content: public BgpSettings withAsn(Long asn)
    parameters:
    - id: asn
      type: 34f09483
      description: <p>the asn value to set </p>
    return:
      type: com.microsoft.azure.management.network._bgp_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._bgp_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._bgp_settings.withBgpPeeringAddress(String)
  id: withBgpPeeringAddress(String)
  parent: com.microsoft.azure.management.network._bgp_settings
  href: com.microsoft.azure.management.network._bgp_settings.yml
  langs:
  - java
  name: withBgpPeeringAddress(String bgpPeeringAddress)
  fullName: BgpSettings com.microsoft.azure.management.network.BgpSettings.withBgpPeeringAddress(String bgpPeeringAddress)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
    startLine: 66
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the bgpPeeringAddress value.</p>

    <p></p>
  syntax:
    content: public BgpSettings withBgpPeeringAddress(String bgpPeeringAddress)
    parameters:
    - id: bgpPeeringAddress
      type: "26831127"
      description: <p>the bgpPeeringAddress value to set </p>
    return:
      type: com.microsoft.azure.management.network._bgp_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._bgp_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._bgp_settings.withPeerWeight(Integer)
  id: withPeerWeight(Integer)
  parent: com.microsoft.azure.management.network._bgp_settings
  href: com.microsoft.azure.management.network._bgp_settings.yml
  langs:
  - java
  name: withPeerWeight(Integer peerWeight)
  fullName: BgpSettings com.microsoft.azure.management.network.BgpSettings.withPeerWeight(Integer peerWeight)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/BgpSettings.java
    startLine: 86
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the peerWeight value.</p>

    <p></p>
  syntax:
    content: public BgpSettings withPeerWeight(Integer peerWeight)
    parameters:
    - id: peerWeight
      type: 08effaa0
      description: <p>the peerWeight value to set </p>
    return:
      type: com.microsoft.azure.management.network._bgp_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._bgp_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 34f09483
  spec.java:
  - name: Long
    fullName: Long
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.network._bgp_settings
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._bgp_settings.yml
  name: BgpSettings
  fullName: com.microsoft.azure.management.network.BgpSettings
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.network._bgp_settings" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: *o1
