items:
- uid: com.microsoft.azure.batch.protocol.models._application_list_options
  id: _application_list_options
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_list_options.clientRequestId()
  - com.microsoft.azure.batch.protocol.models._application_list_options.maxResults()
  - com.microsoft.azure.batch.protocol.models._application_list_options.ocpDate()
  - com.microsoft.azure.batch.protocol.models._application_list_options.returnClientRequestId()
  - com.microsoft.azure.batch.protocol.models._application_list_options.timeout()
  - com.microsoft.azure.batch.protocol.models._application_list_options.withClientRequestId(String)
  - com.microsoft.azure.batch.protocol.models._application_list_options.withMaxResults(Integer)
  - com.microsoft.azure.batch.protocol.models._application_list_options.withOcpDate(DateTime)
  - com.microsoft.azure.batch.protocol.models._application_list_options.withReturnClientRequestId(Boolean)
  - com.microsoft.azure.batch.protocol.models._application_list_options.withTimeout(Integer)
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: ApplicationListOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationListOptions
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Additional parameters for the Application_List operation. </p>
  syntax: &o1
    content: public class ApplicationListOptions
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.clientRequestId()
  id: clientRequestId()
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationListOptions.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 98
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.maxResults()
  id: maxResults()
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: maxResults()
  fullName: Integer com.microsoft.azure.batch.protocol.models.ApplicationListOptions.maxResults()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 58
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the maxResults value.</p>

    <p></p>
  syntax:
    content: public Integer maxResults()
    return:
      type: 08effaa0
      description: <p>the maxResults value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.ocpDate()
  id: ocpDate()
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: ocpDate()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ApplicationListOptions.ocpDate()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 138
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the ocpDate value.</p>

    <p></p>
  syntax:
    content: public DateTime ocpDate()
    return:
      type: 230df18c
      description: <p>the ocpDate value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.returnClientRequestId()
  id: returnClientRequestId()
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: returnClientRequestId()
  fullName: Boolean com.microsoft.azure.batch.protocol.models.ApplicationListOptions.returnClientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 118
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public Boolean returnClientRequestId()
    return:
      type: 866c2227
      description: <p>the returnClientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.timeout()
  id: timeout()
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: timeout()
  fullName: Integer com.microsoft.azure.batch.protocol.models.ApplicationListOptions.timeout()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 78
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the timeout value.</p>

    <p></p>
  syntax:
    content: public Integer timeout()
    return:
      type: 08effaa0
      description: <p>the timeout value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.withClientRequestId(String)
  id: withClientRequestId(String)
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 108
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.withMaxResults(Integer)
  id: withMaxResults(Integer)
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withMaxResults(Integer maxResults)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withMaxResults(Integer maxResults)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 68
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the maxResults value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withMaxResults(Integer maxResults)
    parameters:
    - id: maxResults
      type: 08effaa0
      description: <p>the maxResults value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.withOcpDate(DateTime)
  id: withOcpDate(DateTime)
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withOcpDate(DateTime ocpDate)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withOcpDate(DateTime ocpDate)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 151
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the ocpDate value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withOcpDate(DateTime ocpDate)
    parameters:
    - id: ocpDate
      type: 230df18c
      description: <p>the ocpDate value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.withReturnClientRequestId(Boolean)
  id: withReturnClientRequestId(Boolean)
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withReturnClientRequestId(Boolean returnClientRequestId)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withReturnClientRequestId(Boolean returnClientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 128
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withReturnClientRequestId(Boolean returnClientRequestId)
    parameters:
    - id: returnClientRequestId
      type: 866c2227
      description: <p>the returnClientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options.withTimeout(Integer)
  id: withTimeout(Integer)
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withTimeout(Integer timeout)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withTimeout(Integer timeout)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 88
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the timeout value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withTimeout(Integer timeout)
    parameters:
    - id: timeout
      type: 08effaa0
      description: <p>the timeout value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.azure.batch.protocol.models._application_list_options
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  name: ApplicationListOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationListOptions
  type: Class
  summary: <p>Additional parameters for the Application_List operation. </p>
  syntax: *o1
