items:
- uid: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer
  id: _sdk_version_context_initializer
  parent: com.microsoft.applicationinsights.extensibility.initializer
  children:
  - com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.initialize(TelemetryContext)
  href: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.yml
  langs:
  - java
  name: SdkVersionContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.SdkVersionContextInitializer
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SdkVersionContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SdkVersionContextInitializer.java
    startLine: 33
  package: com.microsoft.applicationinsights.extensibility.initializer
  summary: <p>Initializer for SDK version. </p>
  syntax:
    content: public class SdkVersionContextInitializer implements ContextInitializer
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._context_initializer
  inheritedMembers:
  - com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.sdkPrefix()
- uid: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.initialize(TelemetryContext)
  id: initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.yml
  langs:
  - java
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SdkVersionContextInitializer.initialize(TelemetryContext context)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SdkVersionContextInitializer.java
    startLine: 37
  package: com.microsoft.applicationinsights.extensibility.initializer
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
  overridden: com.microsoft.applicationinsights.extensibility._context_initializer.initialize(TelemetryContext)
references:
- uid: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.sdkPrefix()
- uid: com.microsoft.applicationinsights.extensibility._context_initializer
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._context_initializer.yml
  name: ContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.ContextInitializer
  type: Interface
  summary: <p>Represents an object that implements supporting logic for TelemetryContext. <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public interface ContextInitializer
- uid: com.microsoft.applicationinsights.extensibility._context_initializer.initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility._context_initializer
  href: com.microsoft.applicationinsights.extensibility._context_initializer.yml
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.extensibility.ContextInitializer.initialize(TelemetryContext context)
  type: Method
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry_context.yml
  name: TelemetryContext
  fullName: com.microsoft.applicationinsights.telemetry.TelemetryContext
  type: Class
  summary: <p>Represents a context for sending telemetry to the Application Insights service. The context holds data that is sent with every telemetry item. It includes the instrumentation key; the current operation id, for correlating related telemetry items; and user, session and device data. You can also set properties that are added to every telemetry item, and can be used in the portal to filter the telemetry that used this context. </p>
  syntax:
    content: public class TelemetryContext
