items:
- uid: com.microsoft.azure.management.network._application_gateway_backend._6081d9596f9b84f2f12e5f7a2576ce84
  id: _6081d9596f9b84f2f12e5f7a2576ce84
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend._6081d9596f9b84f2f12e5f7a2576ce84.yml
  langs:
  - java
  name: ApplicationGatewayBackend.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 172
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The final stage of an application gateway backend definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdate,ApplicationGatewayBackend.UpdateDefinitionStages.WithAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  - com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189.withFqdn(String)
  - com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189.withIpAddress(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdate<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189.withFqdn(String)
  parent: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189
  href: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189.yml
  name: withFqdn(String fqdn)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateDefinitionStages.WithAddress<ParentT>.withFqdn(String fqdn)
  type: Method
  summary: <p>Adds the specified existing fully qualified domain name (FQDN) to the backend. </p>
  syntax:
    content: public WithAttach<ParentT> withFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>a fully qualified domain name (FQDN) </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend._6081d9596f9b84f2f12e5f7a2576ce84da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189.withIpAddress(String)
  parent: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189
  href: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189.yml
  name: withIpAddress(String ipAddress)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateDefinitionStages.WithAddress<ParentT>.withIpAddress(String ipAddress)
  type: Method
  summary: <p>Adds the specified existing IP address to the backend. </p>
  syntax:
    content: public WithAttach<ParentT> withIpAddress(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>an IP address </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend._6081d9596f9b84f2f12e5f7a2576ce84da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: Attachable.InUpdate<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdate<ParentT>
  type: Interface
  summary: <p>The final stage of the child object definition, as which it can be attached to the parent. </p>
  syntax:
    content: public interface InUpdate<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend._8bb0ccc2a96949fb36e3c31142ba4189.yml
  name: ApplicationGatewayBackend.UpdateDefinitionStages.WithAddress<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateDefinitionStages.WithAddress<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway backed definition allowing to add an address to the backend. </p>
  syntax:
    content: public interface WithAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway type </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend._update_definition.yml
  name: ApplicationGatewayBackend.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway backend definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayBackend.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayBackend.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._b27c38d53e2854ec34d78148feec338b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend._b27c38d53e2854ec34d78148feec338b.yml
  name: ApplicationGatewayBackend.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  summary: <p>The first stage of an application gateway backend definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayBackend.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway type </p>
