items:
- uid: com.microsoft.azure.management.website._application_logs_config
  id: _application_logs_config
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._application_logs_config.azureBlobStorage()
  - com.microsoft.azure.management.website._application_logs_config.azureTableStorage()
  - com.microsoft.azure.management.website._application_logs_config.fileSystem()
  - com.microsoft.azure.management.website._application_logs_config.withAzureBlobStorage(AzureBlobStorageApplicationLogsConfig)
  - com.microsoft.azure.management.website._application_logs_config.withAzureTableStorage(AzureTableStorageApplicationLogsConfig)
  - com.microsoft.azure.management.website._application_logs_config.withFileSystem(FileSystemApplicationLogsConfig)
  href: com.microsoft.azure.management.website._application_logs_config.yml
  langs:
  - java
  name: ApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.ApplicationLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
    startLine: 14
  package: com.microsoft.azure.management.website
  summary: <p>Application logs configuration. </p>
  syntax: &o1
    content: public class ApplicationLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._application_logs_config.azureBlobStorage()
  id: azureBlobStorage()
  parent: com.microsoft.azure.management.website._application_logs_config
  href: com.microsoft.azure.management.website._application_logs_config.yml
  langs:
  - java
  name: azureBlobStorage()
  fullName: AzureBlobStorageApplicationLogsConfig com.microsoft.azure.management.website.ApplicationLogsConfig.azureBlobStorage()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
    startLine: 75
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the azureBlobStorage value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig azureBlobStorage()
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
      description: <p>the azureBlobStorage value </p>
- uid: com.microsoft.azure.management.website._application_logs_config.azureTableStorage()
  id: azureTableStorage()
  parent: com.microsoft.azure.management.website._application_logs_config
  href: com.microsoft.azure.management.website._application_logs_config.yml
  langs:
  - java
  name: azureTableStorage()
  fullName: AzureTableStorageApplicationLogsConfig com.microsoft.azure.management.website.ApplicationLogsConfig.azureTableStorage()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
    startLine: 55
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the azureTableStorage value.</p>

    <p></p>
  syntax:
    content: public AzureTableStorageApplicationLogsConfig azureTableStorage()
    return:
      type: com.microsoft.azure.management.website._azure_table_storage_application_logs_config
      description: <p>the azureTableStorage value </p>
- uid: com.microsoft.azure.management.website._application_logs_config.fileSystem()
  id: fileSystem()
  parent: com.microsoft.azure.management.website._application_logs_config
  href: com.microsoft.azure.management.website._application_logs_config.yml
  langs:
  - java
  name: fileSystem()
  fullName: FileSystemApplicationLogsConfig com.microsoft.azure.management.website.ApplicationLogsConfig.fileSystem()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
    startLine: 35
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the fileSystem value.</p>

    <p></p>
  syntax:
    content: public FileSystemApplicationLogsConfig fileSystem()
    return:
      type: com.microsoft.azure.management.website._file_system_application_logs_config
      description: <p>the fileSystem value </p>
- uid: com.microsoft.azure.management.website._application_logs_config.withAzureBlobStorage(AzureBlobStorageApplicationLogsConfig)
  id: withAzureBlobStorage(AzureBlobStorageApplicationLogsConfig)
  parent: com.microsoft.azure.management.website._application_logs_config
  href: com.microsoft.azure.management.website._application_logs_config.yml
  langs:
  - java
  name: withAzureBlobStorage(AzureBlobStorageApplicationLogsConfig azureBlobStorage)
  fullName: ApplicationLogsConfig com.microsoft.azure.management.website.ApplicationLogsConfig.withAzureBlobStorage(AzureBlobStorageApplicationLogsConfig azureBlobStorage)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
    startLine: 85
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the azureBlobStorage value.</p>

    <p></p>
  syntax:
    content: public ApplicationLogsConfig withAzureBlobStorage(AzureBlobStorageApplicationLogsConfig azureBlobStorage)
    parameters:
    - id: azureBlobStorage
      type: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
      description: <p>the azureBlobStorage value to set </p>
    return:
      type: com.microsoft.azure.management.website._application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._application_logs_config.withAzureTableStorage(AzureTableStorageApplicationLogsConfig)
  id: withAzureTableStorage(AzureTableStorageApplicationLogsConfig)
  parent: com.microsoft.azure.management.website._application_logs_config
  href: com.microsoft.azure.management.website._application_logs_config.yml
  langs:
  - java
  name: withAzureTableStorage(AzureTableStorageApplicationLogsConfig azureTableStorage)
  fullName: ApplicationLogsConfig com.microsoft.azure.management.website.ApplicationLogsConfig.withAzureTableStorage(AzureTableStorageApplicationLogsConfig azureTableStorage)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
    startLine: 65
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the azureTableStorage value.</p>

    <p></p>
  syntax:
    content: public ApplicationLogsConfig withAzureTableStorage(AzureTableStorageApplicationLogsConfig azureTableStorage)
    parameters:
    - id: azureTableStorage
      type: com.microsoft.azure.management.website._azure_table_storage_application_logs_config
      description: <p>the azureTableStorage value to set </p>
    return:
      type: com.microsoft.azure.management.website._application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._application_logs_config.withFileSystem(FileSystemApplicationLogsConfig)
  id: withFileSystem(FileSystemApplicationLogsConfig)
  parent: com.microsoft.azure.management.website._application_logs_config
  href: com.microsoft.azure.management.website._application_logs_config.yml
  langs:
  - java
  name: withFileSystem(FileSystemApplicationLogsConfig fileSystem)
  fullName: ApplicationLogsConfig com.microsoft.azure.management.website.ApplicationLogsConfig.withFileSystem(FileSystemApplicationLogsConfig fileSystem)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/ApplicationLogsConfig.java
    startLine: 45
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the fileSystem value.</p>

    <p></p>
  syntax:
    content: public ApplicationLogsConfig withFileSystem(FileSystemApplicationLogsConfig fileSystem)
    parameters:
    - id: fileSystem
      type: com.microsoft.azure.management.website._file_system_application_logs_config
      description: <p>the fileSystem value to set </p>
    return:
      type: com.microsoft.azure.management.website._application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: com.microsoft.azure.management.website._file_system_application_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._file_system_application_logs_config.yml
  name: FileSystemApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.FileSystemApplicationLogsConfig
  type: Class
  summary: <p>Application logs to file system configuration. </p>
  syntax:
    content: public class FileSystemApplicationLogsConfig
- uid: com.microsoft.azure.management.website._azure_table_storage_application_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._azure_table_storage_application_logs_config.yml
  name: AzureTableStorageApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.AzureTableStorageApplicationLogsConfig
  type: Class
  summary: <p>Application logs to azure table storage configuration. </p>
  syntax:
    content: public class AzureTableStorageApplicationLogsConfig
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  name: AzureBlobStorageApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig
  type: Class
  summary: <p>Application logs azure blob storage configuration. </p>
  syntax:
    content: public class AzureBlobStorageApplicationLogsConfig
- uid: com.microsoft.azure.management.website._application_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._application_logs_config.yml
  name: ApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.ApplicationLogsConfig
  type: Class
  summary: <p>Application logs configuration. </p>
  syntax: *o1
