items:
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  id: _application_gateway_cookie_based_affinity
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.ApplicationGatewayCookieBasedAffinity(String)
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.DISABLED()
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.ENABLED()
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.equals(Object)
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.hashCode()
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.toString()
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: ApplicationGatewayCookieBasedAffinity
  fullName: com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayCookieBasedAffinity
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.ApplicationGatewayCookieBasedAffinity(String)
  id: ApplicationGatewayCookieBasedAffinity(String)
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: ApplicationGatewayCookieBasedAffinity(String value)
  fullName: com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.ApplicationGatewayCookieBasedAffinity(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 28
  package: com.microsoft.azure.management.network
  summary: <p>Creates a custom value for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public ApplicationGatewayCookieBasedAffinity(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the custom value </p>
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.DISABLED()
  id: DISABLED()
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: DISABLED
  fullName: final ApplicationGatewayCookieBasedAffinity com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.DISABLED
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 20
  package: com.microsoft.azure.management.network
  summary: <p>Static value Disabled for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayCookieBasedAffinity DISABLED= new ApplicationGatewayCookieBasedAffinity("Disabled")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.ENABLED()
  id: ENABLED()
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: ENABLED
  fullName: final ApplicationGatewayCookieBasedAffinity com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.ENABLED
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>Static value Enabled for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayCookieBasedAffinity ENABLED= new ApplicationGatewayCookieBasedAffinity("Enabled")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.equals(Object)
  id: equals(Object)
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: equals(Object obj)
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.equals(Object obj)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 44
  package: com.microsoft.azure.management.network
  syntax:
    content: public boolean equals(Object obj)
    parameters:
    - id: obj
      type: "79317049"
    return:
      type: 4fc6e284
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.hashCode()
  id: hashCode()
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: hashCode()
  fullName: int com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.hashCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 39
  package: com.microsoft.azure.management.network
  syntax:
    content: public int hashCode()
    return:
      type: f75371fa
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.toString()
  id: toString()
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 34
  package: com.microsoft.azure.management.network
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 93de0ef9com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
    name: ApplicationGatewayCookieBasedAffinity
    fullName: com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity
    href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  name: ApplicationGatewayCookieBasedAffinity
  fullName: com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
