items:
- uid: com.microsoft.azure.management.website._hosting_environment_profile
  id: _hosting_environment_profile
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._hosting_environment_profile.id()
  - com.microsoft.azure.management.website._hosting_environment_profile.name()
  - com.microsoft.azure.management.website._hosting_environment_profile.type()
  - com.microsoft.azure.management.website._hosting_environment_profile.withId(String)
  - com.microsoft.azure.management.website._hosting_environment_profile.withName(String)
  - com.microsoft.azure.management.website._hosting_environment_profile.withType(String)
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  langs:
  - java
  name: HostingEnvironmentProfile
  fullName: com.microsoft.azure.management.website.HostingEnvironmentProfile
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
    startLine: 15
  package: com.microsoft.azure.management.website
  summary: <p>Specification for a hostingEnvironment (App Service Environment) to use for this resource. </p>
  syntax: &o1
    content: public class HostingEnvironmentProfile
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._hosting_environment_profile.id()
  id: id()
  parent: com.microsoft.azure.management.website._hosting_environment_profile
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  langs:
  - java
  name: id()
  fullName: String com.microsoft.azure.management.website.HostingEnvironmentProfile.id()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
    startLine: 37
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure.management.website._hosting_environment_profile.name()
  id: name()
  parent: com.microsoft.azure.management.website._hosting_environment_profile
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.website.HostingEnvironmentProfile.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
    startLine: 57
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.website._hosting_environment_profile.type()
  id: type()
  parent: com.microsoft.azure.management.website._hosting_environment_profile
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  langs:
  - java
  name: type()
  fullName: String com.microsoft.azure.management.website.HostingEnvironmentProfile.type()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
    startLine: 77
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the type value.</p>

    <p></p>
  syntax:
    content: public String type()
    return:
      type: "26831127"
      description: <p>the type value </p>
- uid: com.microsoft.azure.management.website._hosting_environment_profile.withId(String)
  id: withId(String)
  parent: com.microsoft.azure.management.website._hosting_environment_profile
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  langs:
  - java
  name: withId(String id)
  fullName: HostingEnvironmentProfile com.microsoft.azure.management.website.HostingEnvironmentProfile.withId(String id)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
    startLine: 47
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentProfile withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure.management.website._hosting_environment_profile
      description: <p>the <xref href="com.microsoft.azure.management.website._hosting_environment_profile" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._hosting_environment_profile.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.website._hosting_environment_profile
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  langs:
  - java
  name: withName(String name)
  fullName: HostingEnvironmentProfile com.microsoft.azure.management.website.HostingEnvironmentProfile.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
    startLine: 67
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentProfile withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.website._hosting_environment_profile
      description: <p>the <xref href="com.microsoft.azure.management.website._hosting_environment_profile" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._hosting_environment_profile.withType(String)
  id: withType(String)
  parent: com.microsoft.azure.management.website._hosting_environment_profile
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  langs:
  - java
  name: withType(String type)
  fullName: HostingEnvironmentProfile com.microsoft.azure.management.website.HostingEnvironmentProfile.withType(String type)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentProfile.java
    startLine: 87
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the type value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentProfile withType(String type)
    parameters:
    - id: type
      type: "26831127"
      description: <p>the type value to set </p>
    return:
      type: com.microsoft.azure.management.website._hosting_environment_profile
      description: <p>the <xref href="com.microsoft.azure.management.website._hosting_environment_profile" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website._hosting_environment_profile
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._hosting_environment_profile.yml
  name: HostingEnvironmentProfile
  fullName: com.microsoft.azure.management.website.HostingEnvironmentProfile
  type: Class
  summary: <p>Specification for a hostingEnvironment (App Service Environment) to use for this resource. </p>
  syntax: *o1
