items:
- uid: com.microsoft.azure.management.resources._deployment_operation
  id: _deployment_operation
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment_operation.operationId()
  - com.microsoft.azure.management.resources._deployment_operation.provisioningState()
  - com.microsoft.azure.management.resources._deployment_operation.statusCode()
  - com.microsoft.azure.management.resources._deployment_operation.statusMessage()
  - com.microsoft.azure.management.resources._deployment_operation.targetResource()
  - com.microsoft.azure.management.resources._deployment_operation.timestamp()
  href: com.microsoft.azure.management.resources._deployment_operation.yml
  langs:
  - java
  name: DeploymentOperation
  fullName: com.microsoft.azure.management.resources.DeploymentOperation
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
    startLine: 19
  package: com.microsoft.azure.management.resources
  summary: <p>An immutable client-side representation of a deployment operation. </p>
  syntax:
    content: public interface DeploymentOperation extends Indexable,Refreshable< DeploymentOperation >,Wrapper< DeploymentOperationInner >
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  - com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  - com.microsoft.azure.management.resources.fluentcore.model._refreshable.refresh()
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
- uid: com.microsoft.azure.management.resources._deployment_operation.operationId()
  id: operationId()
  parent: com.microsoft.azure.management.resources._deployment_operation
  href: com.microsoft.azure.management.resources._deployment_operation.yml
  langs:
  - java
  name: operationId()
  fullName: String com.microsoft.azure.management.resources.DeploymentOperation.operationId()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
    startLine: 27
  package: com.microsoft.azure.management.resources
  syntax:
    content: public String operationId()
    return:
      type: "26831127"
      description: <p>the deployment operation id </p>
- uid: com.microsoft.azure.management.resources._deployment_operation.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.resources._deployment_operation
  href: com.microsoft.azure.management.resources._deployment_operation.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.resources.DeploymentOperation.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
    startLine: 33
  package: com.microsoft.azure.management.resources
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the state of the provisioning resource being deployed </p>
- uid: com.microsoft.azure.management.resources._deployment_operation.statusCode()
  id: statusCode()
  parent: com.microsoft.azure.management.resources._deployment_operation
  href: com.microsoft.azure.management.resources._deployment_operation.yml
  langs:
  - java
  name: statusCode()
  fullName: String com.microsoft.azure.management.resources.DeploymentOperation.statusCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
    startLine: 43
  package: com.microsoft.azure.management.resources
  syntax:
    content: public String statusCode()
    return:
      type: "26831127"
      description: <p>the operation status code.= </p>
- uid: com.microsoft.azure.management.resources._deployment_operation.statusMessage()
  id: statusMessage()
  parent: com.microsoft.azure.management.resources._deployment_operation
  href: com.microsoft.azure.management.resources._deployment_operation.yml
  langs:
  - java
  name: statusMessage()
  fullName: Object com.microsoft.azure.management.resources.DeploymentOperation.statusMessage()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
    startLine: 48
  package: com.microsoft.azure.management.resources
  syntax:
    content: public Object statusMessage()
    return:
      type: "79317049"
      description: <p>the operation status message </p>
- uid: com.microsoft.azure.management.resources._deployment_operation.targetResource()
  id: targetResource()
  parent: com.microsoft.azure.management.resources._deployment_operation
  href: com.microsoft.azure.management.resources._deployment_operation.yml
  langs:
  - java
  name: targetResource()
  fullName: TargetResource com.microsoft.azure.management.resources.DeploymentOperation.targetResource()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
    startLine: 53
  package: com.microsoft.azure.management.resources
  syntax:
    content: public TargetResource targetResource()
    return:
      type: com.microsoft.azure.management.resources._target_resource
      description: <p>the target resource </p>
- uid: com.microsoft.azure.management.resources._deployment_operation.timestamp()
  id: timestamp()
  parent: com.microsoft.azure.management.resources._deployment_operation
  href: com.microsoft.azure.management.resources._deployment_operation.yml
  langs:
  - java
  name: timestamp()
  fullName: DateTime com.microsoft.azure.management.resources.DeploymentOperation.timestamp()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
    startLine: 38
  package: com.microsoft.azure.management.resources
  syntax:
    content: public DateTime timestamp()
    return:
      type: 230df18c
      description: <p>the date and time of the operation </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: inner()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Wrapper< T >.inner()
  type: Method
  syntax:
    content: public T inner()
    return:
      type: 8ce1ecb9
      description: <p>wrapped inner object providing direct access to the underlying auto-generated API implementation, based on <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> REST API </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._refreshable.refresh()
  parent: com.microsoft.azure.management.resources.fluentcore.model._refreshable
  href: com.microsoft.azure.management.resources.fluentcore.model._refreshable.yml
  name: refresh()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Refreshable< T >.refresh()
  type: Method
  summary: >-
    <p>Refreshes the resource to sync with <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public T refresh()
    return:
      type: 8ce1ecb9
      description: <p>the refreshed resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: setInner(T inner)
  fullName: void com.microsoft.azure.management.resources.fluentcore.model.Wrapper< T >.setInner(T inner)
  type: Method
  summary: >-
    <p>Set the wrapped inner model. (For internal use only)</p>

    <p></p>
  syntax:
    content: public void setInner(T inner)
    parameters:
    - id: inner
      type: 8ce1ecb9
      description: <p>the new inner model </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: Indexable
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Indexable
  type: Interface
  summary: <p>Base interface for all models that can be indexed by a key. </p>
  syntax:
    content: public interface Indexable
- uid: com.microsoft.azure.management.resources.fluentcore.model._refreshable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._refreshable.yml
  name: Refreshable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Refreshable<T>
  type: Interface
  summary: >-
    <p>Base class for resources that can be refreshed to get the latest state.</p>

    <p></p>
  syntax:
    content: public interface Refreshable<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the fluent type of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: Wrapper<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>
  type: Interface
  summary: >-
    <p>The wrapper around an inner object providing extended functionalities.</p>

    <p></p>
  syntax:
    content: public interface Wrapper<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the inner object. </p>
- uid: com.microsoft.azure.management.resources.implementation._deployment_operation_impl
- uid: com.microsoft.azure.management.resources._target_resource
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._target_resource.yml
  name: TargetResource
  fullName: com.microsoft.azure.management.resources.TargetResource
  type: Class
  summary: <p>Target resource. </p>
  syntax:
    content: public class TargetResource
