items:
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
  id: _hosting_environment_diagnostics_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.diagnosicsOutput()
  - com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.name()
  - com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.withDiagnosicsOutput(String)
  - com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.withName(String)
  href: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: HostingEnvironmentDiagnosticsInner
  fullName: com.microsoft.azure.management.website.implementation.HostingEnvironmentDiagnosticsInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentDiagnosticsInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentDiagnosticsInner.java
    startLine: 14
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Diagnostics for a hosting environment (App Service Environment). </p>
  syntax: &o1
    content: public class HostingEnvironmentDiagnosticsInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.diagnosicsOutput()
  id: diagnosicsOutput()
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: diagnosicsOutput()
  fullName: String com.microsoft.azure.management.website.implementation.HostingEnvironmentDiagnosticsInner.diagnosicsOutput()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentDiagnosticsInner.java
    startLine: 50
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the diagnosicsOutput value.</p>

    <p></p>
  syntax:
    content: public String diagnosicsOutput()
    return:
      type: "26831127"
      description: <p>the diagnosicsOutput value </p>
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.name()
  id: name()
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.website.implementation.HostingEnvironmentDiagnosticsInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentDiagnosticsInner.java
    startLine: 30
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.withDiagnosicsOutput(String)
  id: withDiagnosicsOutput(String)
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: withDiagnosicsOutput(String diagnosicsOutput)
  fullName: HostingEnvironmentDiagnosticsInner com.microsoft.azure.management.website.implementation.HostingEnvironmentDiagnosticsInner.withDiagnosicsOutput(String diagnosicsOutput)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentDiagnosticsInner.java
    startLine: 60
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the diagnosicsOutput value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentDiagnosticsInner withDiagnosicsOutput(String diagnosicsOutput)
    parameters:
    - id: diagnosicsOutput
      type: "26831127"
      description: <p>the diagnosicsOutput value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: HostingEnvironmentDiagnosticsInner com.microsoft.azure.management.website.implementation.HostingEnvironmentDiagnosticsInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentDiagnosticsInner.java
    startLine: 40
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentDiagnosticsInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._hosting_environment_diagnostics_inner.yml
  name: HostingEnvironmentDiagnosticsInner
  fullName: com.microsoft.azure.management.website.implementation.HostingEnvironmentDiagnosticsInner
  type: Class
  summary: <p>Diagnostics for a hosting environment (App Service Environment). </p>
  syntax: *o1
