items:
- uid: com.microsoft.azure.management.network._vpn_client_configuration
  id: _vpn_client_configuration
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._vpn_client_configuration.vpnClientAddressPool()
  - com.microsoft.azure.management.network._vpn_client_configuration.vpnClientRevokedCertificates()
  - com.microsoft.azure.management.network._vpn_client_configuration.vpnClientRootCertificates()
  - com.microsoft.azure.management.network._vpn_client_configuration.withVpnClientAddressPool(AddressSpace)
  - com.microsoft.azure.management.network._vpn_client_configuration.withVpnClientRevokedCertificates(List<VpnClientRevokedCertificateInner>)
  - com.microsoft.azure.management.network._vpn_client_configuration.withVpnClientRootCertificates(List<VpnClientRootCertificateInner>)
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: VpnClientConfiguration
  fullName: com.microsoft.azure.management.network.VpnClientConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> for P2S client. </p>
  syntax: &o1
    content: public class VpnClientConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._vpn_client_configuration.vpnClientAddressPool()
  id: vpnClientAddressPool()
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientAddressPool()
  fullName: AddressSpace com.microsoft.azure.management.network.VpnClientConfiguration.vpnClientAddressPool()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 39
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the vpnClientAddressPool value.</p>

    <p></p>
  syntax:
    content: public AddressSpace vpnClientAddressPool()
    return:
      type: com.microsoft.azure.management.network._address_space
      description: <p>the vpnClientAddressPool value </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration.vpnClientRevokedCertificates()
  id: vpnClientRevokedCertificates()
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientRevokedCertificates()
  fullName: List<VpnClientRevokedCertificateInner> com.microsoft.azure.management.network.VpnClientConfiguration.vpnClientRevokedCertificates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 79
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the vpnClientRevokedCertificates value.</p>

    <p></p>
  syntax:
    content: public List<VpnClientRevokedCertificateInner> vpnClientRevokedCertificates()
    return:
      type: 5618da2dcom.microsoft.azure.management.network.implementation._vpn_client_revoked_certificate_innera08ddfce
      description: <p>the vpnClientRevokedCertificates value </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration.vpnClientRootCertificates()
  id: vpnClientRootCertificates()
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientRootCertificates()
  fullName: List<VpnClientRootCertificateInner> com.microsoft.azure.management.network.VpnClientConfiguration.vpnClientRootCertificates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 59
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the vpnClientRootCertificates value.</p>

    <p></p>
  syntax:
    content: public List<VpnClientRootCertificateInner> vpnClientRootCertificates()
    return:
      type: 5618da2dcom.microsoft.azure.management.network.implementation._vpn_client_root_certificate_innera08ddfce
      description: <p>the vpnClientRootCertificates value </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration.withVpnClientAddressPool(AddressSpace)
  id: withVpnClientAddressPool(AddressSpace)
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.VpnClientConfiguration.withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 49
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the vpnClientAddressPool value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
    parameters:
    - id: vpnClientAddressPool
      type: com.microsoft.azure.management.network._address_space
      description: <p>the vpnClientAddressPool value to set </p>
    return:
      type: com.microsoft.azure.management.network._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration.withVpnClientRevokedCertificates(List<VpnClientRevokedCertificateInner>)
  id: withVpnClientRevokedCertificates(List<VpnClientRevokedCertificateInner>)
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientRevokedCertificates(List<VpnClientRevokedCertificateInner> vpnClientRevokedCertificates)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.VpnClientConfiguration.withVpnClientRevokedCertificates(List<VpnClientRevokedCertificateInner> vpnClientRevokedCertificates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 89
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the vpnClientRevokedCertificates value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientRevokedCertificates(List<VpnClientRevokedCertificateInner> vpnClientRevokedCertificates)
    parameters:
    - id: vpnClientRevokedCertificates
      type: 5618da2dcom.microsoft.azure.management.network.implementation._vpn_client_revoked_certificate_innera08ddfce
      description: <p>the vpnClientRevokedCertificates value to set </p>
    return:
      type: com.microsoft.azure.management.network._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration.withVpnClientRootCertificates(List<VpnClientRootCertificateInner>)
  id: withVpnClientRootCertificates(List<VpnClientRootCertificateInner>)
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientRootCertificates(List<VpnClientRootCertificateInner> vpnClientRootCertificates)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.VpnClientConfiguration.withVpnClientRootCertificates(List<VpnClientRootCertificateInner> vpnClientRootCertificates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 69
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the vpnClientRootCertificates value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientRootCertificates(List<VpnClientRootCertificateInner> vpnClientRootCertificates)
    parameters:
    - id: vpnClientRootCertificates
      type: 5618da2dcom.microsoft.azure.management.network.implementation._vpn_client_root_certificate_innera08ddfce
      description: <p>the vpnClientRootCertificates value to set </p>
    return:
      type: com.microsoft.azure.management.network._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 5618da2dcom.microsoft.azure.management.network.implementation._vpn_client_root_certificate_innera08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.management.network.implementation._vpn_client_root_certificate_inner
    name: VpnClientRootCertificateInner
    fullName: com.microsoft.azure.management.network.implementation.VpnClientRootCertificateInner
    href: com.microsoft.azure.management.network.implementation._vpn_client_root_certificate_inner.yml
  - name: '>'
    fullName: '>'
- uid: 5618da2dcom.microsoft.azure.management.network.implementation._vpn_client_revoked_certificate_innera08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.management.network.implementation._vpn_client_revoked_certificate_inner
    name: VpnClientRevokedCertificateInner
    fullName: com.microsoft.azure.management.network.implementation.VpnClientRevokedCertificateInner
    href: com.microsoft.azure.management.network.implementation._vpn_client_revoked_certificate_inner.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.network._address_space
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._address_space.yml
  name: AddressSpace
  fullName: com.microsoft.azure.management.network.AddressSpace
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._address_space" data-throw-if-not-resolved="false"></xref> contains an array of IP address ranges that can be used by subnets. </p>
  syntax:
    content: public class AddressSpace
- uid: com.microsoft.azure.management.network.implementation._vpn_client_root_certificate_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._vpn_client_root_certificate_inner.yml
  name: VpnClientRootCertificateInner
  fullName: com.microsoft.azure.management.network.implementation.VpnClientRootCertificateInner
  type: Class
  summary: <p>VPN client root certificate of virtual network gateway. </p>
  syntax:
    content: public class VpnClientRootCertificateInner
- uid: com.microsoft.azure.management.network.implementation._vpn_client_revoked_certificate_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._vpn_client_revoked_certificate_inner.yml
  name: VpnClientRevokedCertificateInner
  fullName: com.microsoft.azure.management.network.implementation.VpnClientRevokedCertificateInner
  type: Class
  summary: <p>VPN client revoked certificate of virtual network gateway. </p>
  syntax:
    content: public class VpnClientRevokedCertificateInner
- uid: com.microsoft.azure.management.network._vpn_client_configuration
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  name: VpnClientConfiguration
  fullName: com.microsoft.azure.management.network.VpnClientConfiguration
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> for P2S client. </p>
  syntax: *o1
