items:
- uid: com.microsoft.azure.management.website._file_system_application_logs_config
  id: _file_system_application_logs_config
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._file_system_application_logs_config.level()
  - com.microsoft.azure.management.website._file_system_application_logs_config.withLevel(LogLevel)
  href: com.microsoft.azure.management.website._file_system_application_logs_config.yml
  langs:
  - java
  name: FileSystemApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.FileSystemApplicationLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemApplicationLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemApplicationLogsConfig.java
    startLine: 14
  package: com.microsoft.azure.management.website
  summary: <p>Application logs to file system configuration. </p>
  syntax: &o1
    content: public class FileSystemApplicationLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._file_system_application_logs_config.level()
  id: level()
  parent: com.microsoft.azure.management.website._file_system_application_logs_config
  href: com.microsoft.azure.management.website._file_system_application_logs_config.yml
  langs:
  - java
  name: level()
  fullName: LogLevel com.microsoft.azure.management.website.FileSystemApplicationLogsConfig.level()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemApplicationLogsConfig.java
    startLine: 26
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the level value.</p>

    <p></p>
  syntax:
    content: public LogLevel level()
    return:
      type: com.microsoft.azure.management.website._log_level
      description: <p>the level value </p>
- uid: com.microsoft.azure.management.website._file_system_application_logs_config.withLevel(LogLevel)
  id: withLevel(LogLevel)
  parent: com.microsoft.azure.management.website._file_system_application_logs_config
  href: com.microsoft.azure.management.website._file_system_application_logs_config.yml
  langs:
  - java
  name: withLevel(LogLevel level)
  fullName: FileSystemApplicationLogsConfig com.microsoft.azure.management.website.FileSystemApplicationLogsConfig.withLevel(LogLevel level)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemApplicationLogsConfig.java
    startLine: 36
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the level value.</p>

    <p></p>
  syntax:
    content: public FileSystemApplicationLogsConfig withLevel(LogLevel level)
    parameters:
    - id: level
      type: com.microsoft.azure.management.website._log_level
      description: <p>the level value to set </p>
    return:
      type: com.microsoft.azure.management.website._file_system_application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._file_system_application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: com.microsoft.azure.management.website._log_level
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._log_level.yml
  name: LogLevel
  fullName: com.microsoft.azure.management.website.LogLevel
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.website._log_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum LogLevel
- uid: com.microsoft.azure.management.website._file_system_application_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._file_system_application_logs_config.yml
  name: FileSystemApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.FileSystemApplicationLogsConfig
  type: Class
  summary: <p>Application logs to file system configuration. </p>
  syntax: *o1
