items:
- uid: com.microsoft.applicationinsights.internal.logger
  id: logger
  children:
  - com.microsoft.applicationinsights.internal.logger._console_logger_output
  - com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  - com.microsoft.applicationinsights.internal.logger._default_log_file_proxy_factory
  - com.microsoft.applicationinsights.internal.logger._file_logger_output
  - com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  - com.microsoft.applicationinsights.internal.logger._internal_logger
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  - com.microsoft.applicationinsights.internal.logger._internal_logger_test
  - com.microsoft.applicationinsights.internal.logger._log_file_proxy
  - com.microsoft.applicationinsights.internal.logger._log_file_proxy_factory
  - com.microsoft.applicationinsights.internal.logger._logger_output
  href: com.microsoft.applicationinsights.internal.logger.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.logger
  fullName: com.microsoft.applicationinsights.internal.logger
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/ConsoleLoggerOutput.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/ConsoleLoggerOutput.java
    startLine: 21
  syntax:
    content: namespace logger
references:
- uid: com.microsoft.applicationinsights.internal.logger._console_logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._console_logger_output.yml
  name: ConsoleLoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.ConsoleLoggerOutput
  type: Class
  summary: <p>Created by gupele on 1/14/2015. </p>
  syntax:
    content: public class ConsoleLoggerOutput implements LoggerOutput
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.yml
  name: DefaultLogFileProxy
  fullName: com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxy
  type: Class
  summary: <p>The class is responsible for doing the work with the log files. </p>
  syntax:
    content: public class DefaultLogFileProxy implements LogFileProxy
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy_factory
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy_factory.yml
  name: DefaultLogFileProxyFactory
  fullName: com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxyFactory
  type: Class
  summary: <p>Created by gupele on 2/1/2015. </p>
  syntax:
    content: public class DefaultLogFileProxyFactory implements LogFileProxyFactory
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output.yml
  name: FileLoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.FileLoggerOutput
  type: Class
  summary: >-
    <p>The class is responsible for write log messages into log files. The class will write to a file until the file max size is reached.</p>

    <p>When that happens it will create close that file and open a new file.</p>

    <p>When the maximum amount of log files is reached, the oldest one will be deleted.</p>

    <p>The class does a 'best effort' to work with files, if there is a problem, the class will try to write into a <xref href="com.microsoft.applicationinsights.internal.logger._console_logger_output" data-throw-if-not-resolved="false"></xref> but will not fail the process under any scenario. </p>
  syntax:
    content: public class FileLoggerOutput implements LoggerOutput
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  name: FileLoggerOutputTest
  fullName: com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest
  type: Class
  syntax:
    content: public class FileLoggerOutputTest
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  name: InternalLogger
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger
  type: Enum
  summary: >-
    <p>A first, very simple version of an internal logger</p>

    <p>Note: this class is for the SDK internal use only, and therefore should ONLY be used by SDK classes.</p>

    <p>By default the logger will not log messages since it will use the 'NullLoggerOutput' and LoggerLevel of 'OFF' which both deny the output</p>

    <p>Created by gupele on 1/13/2015. </p>
  syntax:
    content: public enum InternalLogger
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  name: InternalLoggerTest
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLoggerTest
  type: Class
  syntax:
    content: public class InternalLoggerTest
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  name: LogFileProxy
  fullName: com.microsoft.applicationinsights.internal.logger.LogFileProxy
  type: Interface
  summary: <p>Created by gupele on 2/1/2015. </p>
  syntax:
    content: public interface LogFileProxy
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy_factory
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy_factory.yml
  name: LogFileProxyFactory
  fullName: com.microsoft.applicationinsights.internal.logger.LogFileProxyFactory
  type: Interface
  summary: <p>Created by gupele on 2/1/2015. </p>
  syntax:
    content: public interface LogFileProxyFactory
- uid: com.microsoft.applicationinsights.internal.logger._logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._logger_output.yml
  name: LoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.LoggerOutput
  type: Interface
  summary: <p>Created by gupele on 1/14/2015. </p>
  syntax:
    content: public interface LoggerOutput
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.yml
  name: InternalLogger.LoggerOutputType
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggerOutputType
  type: Enum
  syntax:
    content: public enum LoggerOutputType
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  name: InternalLogger.LoggingLevel
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel
  type: Enum
  syntax:
    content: public enum LoggingLevel
