items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._update
  id: _update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._update.yml
  langs:
  - java
  name: ApplicationGatewayFrontendHttpListener.Update
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.Update
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 191
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of an application gateway HTTP listener update as part of an application gateway update. </p>
  syntax:
    content: public interface Update extends Settable<ApplicationGateway.Update>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._settable.parent()
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable.parent()
  parent: com.microsoft.azure.management.resources.fluentcore.model._settable
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: parent()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Settable<ParentT>.parent()
  type: Method
  summary: >-
    <p>Begins an update for a child resource. </p>

    <p>This is the beginning of the builder pattern used to update child resources The final method completing the update and continue the actual parent resource update process in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> is <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable.parent()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public ParentT parent()
    return:
      type: 18a275b1
      description: <p>the stage of parent resource update </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: Settable<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Settable<ParentT>
  type: Interface
  summary: >-
    <p>The base interface for all template interfaces for child resources that support update operations.</p>

    <p></p>
  syntax:
    content: public interface Settable<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable.parent()" data-throw-if-not-resolved="false"></xref> returns to </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_http_listener_impl
