items:
- uid: com.microsoft.azure.management.appservice._deployment_slots
  id: _deployment_slots
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice._deployment_slots.yml
  langs:
  - java
  name: DeploymentSlots
  fullName: com.microsoft.azure.management.appservice.DeploymentSlots
  type: Interface
  source:
    remote:
      path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/DeploymentSlots.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/DeploymentSlots.java
    startLine: 20
  package: com.microsoft.azure.management.appservice
  summary: <p>Entry point for storage accounts management API. </p>
  syntax:
    content: public interface DeploymentSlots extends SupportsCreating<DeploymentSlot.DefinitionStages.Blank>,SupportsListing<DeploymentSlot>,SupportsGettingByName<DeploymentSlot>,SupportsDeletingById,SupportsGettingById<DeploymentSlot>,SupportsDeletingByName
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_creating.define(String)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.deleteById(String)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.deleteByIdAsync(String,ServiceCallback<Void>)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.deleteByIdAsync(String)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.deleteByName(String)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.deleteByNameAsync(String,ServiceCallback<Void>)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.deleteByNameAsync(String)
  - com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.getById(String)
  - com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_name.getByName(String)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.list()
references:
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_creating.define(String)
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_creating
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_creating.yml
  name: define(String name)
  fullName: T com.microsoft.azure.management.resources.fluentcore.collection.SupportsCreating<T>.define(String name)
  type: Method
  summary: >-
    <p>Begins a definition for a new resource. </p>

    <p>This is the beginning of the builder pattern used to create top level resources in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. The final method completing the definition and starting the actual resource creation process in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> is <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable.create()" data-throw-if-not-resolved="false"></xref>. </p>

    <p>Note that the <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable.create()" data-throw-if-not-resolved="false"></xref> method is only available at the stage of the resource definition that has the minimum set of input parameters specified. If you do not see <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable.create()" data-throw-if-not-resolved="false"></xref> among the available methods, it means you have not yet specified all the required input settings. Input settings generally begin with the word "with", for example:  and return the next stage of the resource definition, as an interface in the "fluent interface" style. </p>
  syntax:
    content: public T define(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the new resource </p>
    return:
      type: 8ce1ecb9
      description: <p>the first stage of the new resource definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.deleteById(String)
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.yml
  name: deleteById(String id)
  fullName: void com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingById.deleteById(String id)
  type: Method
  summary: >-
    <p>Deletes a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource ID.</p>

    <p></p>
  syntax:
    content: public void deleteById(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the resource ID of the resource to delete </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.deleteByIdAsync(String,ServiceCallback<Void>)
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.yml
  name: deleteByIdAsync(String id, ServiceCallback<Void> callback)
  fullName: ServiceCall<Void> com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingById.deleteByIdAsync(String id, ServiceCallback<Void> callback)
  type: Method
  summary: >-
    <p>Asynchronously delete a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource ID.</p>

    <p></p>
  syntax:
    content: public ServiceCall<Void> deleteByIdAsync(String id, ServiceCallback<Void> callback)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the resource ID of the resource to delete </p>
    - id: callback
      type: da7fd5ea
      description: <p>the callback on success or failure </p>
    return:
      type: edb85f85
      description: <p>a handle to cancel the request </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.deleteByIdAsync(String)
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.yml
  name: deleteByIdAsync(String id)
  fullName: Observable<Void> com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingById.deleteByIdAsync(String id)
  type: Method
  summary: >-
    <p>Asynchronously delete a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource ID.</p>

    <p></p>
  syntax:
    content: public Observable<Void> deleteByIdAsync(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the resource ID of the resource to delete </p>
    return:
      type: dcd884b2
      description: <p>an observable of the request </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.deleteByName(String)
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.yml
  name: deleteByName(String name)
  fullName: void com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingByName.deleteByName(String name)
  type: Method
  summary: >-
    <p>Deletes a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource name.</p>

    <p></p>
  syntax:
    content: public void deleteByName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the resource to delete </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.deleteByNameAsync(String,ServiceCallback<Void>)
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.yml
  name: deleteByNameAsync(String name, ServiceCallback<Void> callback)
  fullName: ServiceCall<Void> com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingByName.deleteByNameAsync(String name, ServiceCallback<Void> callback)
  type: Method
  summary: >-
    <p>Asynchronously delete a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource name.</p>

    <p></p>
  syntax:
    content: public ServiceCall<Void> deleteByNameAsync(String name, ServiceCallback<Void> callback)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the resource to delete </p>
    - id: callback
      type: da7fd5ea
      description: <p>the callback on success or failure </p>
    return:
      type: edb85f85
      description: <p>a handle to cancel the request </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.deleteByNameAsync(String)
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.yml
  name: deleteByNameAsync(String name)
  fullName: Observable<Void> com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingByName.deleteByNameAsync(String name)
  type: Method
  summary: >-
    <p>Asynchronously delete a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource name.</p>

    <p></p>
  syntax:
    content: public Observable<Void> deleteByNameAsync(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the resource to delete </p>
    return:
      type: dcd884b2
      description: <p>an observable of the request </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.getById(String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id
  href: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.yml
  name: getById(String id)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.collection.SupportsGettingById<T>.getById(String id)
  type: Method
  summary: >-
    <p>Gets the information about a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> based on the resource id.</p>

    <p></p>
  syntax:
    content: public T getById(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id of the resource. </p>
    return:
      type: 8ce1ecb9
      description: <p>an immutable representation of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_name.getByName(String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_name
  href: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_name.yml
  name: getByName(String name)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.collection.SupportsGettingByName<T>.getByName(String name)
  type: Method
  summary: >-
    <p>Gets the information about a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> based on the resource name within the current resource group.</p>

    <p></p>
  syntax:
    content: public T getByName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the resource. (Note, this is not the resource ID.) </p>
    return:
      type: 8ce1ecb9
      description: <p>an immutable representation of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.list()
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.yml
  name: list()
  fullName: PagedList<T> com.microsoft.azure.management.resources.fluentcore.collection.SupportsListing<T>.list()
  type: Method
  summary: >-
    <p>Lists all the resources of the specified type in the currently selected subscription.</p>

    <p></p>
  syntax:
    content: public PagedList<T> list()
    return:
      type: e5f90f8a
      description: <p>list of resources </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_creating
  parent: com.microsoft.azure.management.resources.fluentcore.collection
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_creating.yml
  name: SupportsCreating<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.collection.SupportsCreating<T>
  type: Interface
  summary: >-
    <p>Providing access to creating <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> top level resources. </p>

    <p>(Note: this interface is not intended to be implemented by user code) </p>
  syntax:
    content: public interface SupportsCreating<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the initial blank definition interface </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing
  parent: com.microsoft.azure.management.resources.fluentcore.collection
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.yml
  name: SupportsListing<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.collection.SupportsListing<T>
  type: Interface
  summary: >-
    <p>Provides access to listing <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> resources of a specific type in a subscription. </p>

    <p>(Note: this interface is not intended to be implemented by user code)</p>

    <p></p>
  syntax:
    content: public interface SupportsListing<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the fluent type of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_name
  parent: com.microsoft.azure.management.resources.fluentcore.arm.collection
  href: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_name.yml
  name: SupportsGettingByName<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.collection.SupportsGettingByName<T>
  type: Interface
  summary: >-
    <p>Provides access to getting a specific <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> resource based on its name within the current resource group.</p>

    <p></p>
  syntax:
    content: public interface SupportsGettingByName<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the resource collection </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id
  parent: com.microsoft.azure.management.resources.fluentcore.collection
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_id.yml
  name: SupportsDeletingById
  fullName: com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingById
  type: Interface
  summary: >-
    <p>Provides access to deleting a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource ID. </p>

    <p>(Note: this interface is not intended to be implemented by user code) </p>
  syntax:
    content: public interface SupportsDeletingById
- uid: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id
  parent: com.microsoft.azure.management.resources.fluentcore.arm.collection
  href: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.yml
  name: SupportsGettingById<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.collection.SupportsGettingById<T>
  type: Interface
  summary: >-
    <p>Provides access to getting a specific <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> resource based on its resource ID.</p>

    <p></p>
  syntax:
    content: public interface SupportsGettingById<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the resource collection </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name
  parent: com.microsoft.azure.management.resources.fluentcore.collection
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_deleting_by_name.yml
  name: SupportsDeletingByName
  fullName: com.microsoft.azure.management.resources.fluentcore.collection.SupportsDeletingByName
  type: Interface
  summary: >-
    <p>Provides access to deleting a resource from <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>, identifying it by its resource name. </p>

    <p>(Note: this interface is not intended to be implemented by user code) </p>
  syntax:
    content: public interface SupportsDeletingByName
- uid: com.microsoft.azure.management.appservice.implementation._deployment_slots_impl
