items:
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  id: _with_template
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment._update_stages._with_template.withTemplate(Object)
  - com.microsoft.azure.management.resources._deployment._update_stages._with_template.withTemplate(String)
  - com.microsoft.azure.management.resources._deployment._update_stages._with_template.withTemplateLink(String,String)
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  langs:
  - java
  name: Deployment.UpdateStages.WithTemplate
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 262
  package: com.microsoft.azure.management.resources
  summary: <p>A deployment update allowing to change the template. </p>
  syntax:
    content: public interface WithTemplate
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template.withTemplate(Object)
  id: withTemplate(Object)
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  langs:
  - java
  name: withTemplate(Object template)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate.withTemplate(Object template)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 269
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the template as a Java object.</p>

    <p></p>
  syntax:
    content: public Update withTemplate(Object template)
    parameters:
    - id: template
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template.withTemplate(String)
  id: withTemplate(String)
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  langs:
  - java
  name: withTemplate(String templateJson)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate.withTemplate(String templateJson)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 278
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the template as a JSON string.</p>

    <p></p>
  syntax:
    content: public Update withTemplate(String templateJson)
    parameters:
    - id: templateJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
  exceptions:
  - type: cbf33bbe
    description: <p>exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template.withTemplateLink(String,String)
  id: withTemplateLink(String,String)
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  langs:
  - java
  name: withTemplateLink(String uri, String contentVersion)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate.withTemplateLink(String uri, String contentVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 287
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the template as a URL.</p>

    <p></p>
  syntax:
    content: public Update withTemplateLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote template file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the template file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
references:
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources._deployment._update
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update.yml
  name: Deployment.Update
  fullName: com.microsoft.azure.management.resources.Deployment.Update
  type: Interface
  summary: >-
    <p>The template for a deployment update operation, containing all the settings that can be modified. </p>

    <p>Call <xref href="com.microsoft.azure.management.resources.fluentcore.model._appliable.apply()" data-throw-if-not-resolved="false"></xref> to apply the changes to the deployment in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Update extends Appliable< Deployment >,Deployment.UpdateStages.WithTemplate,Deployment.UpdateStages.WithParameters,Deployment.UpdateStages.WithMode
