items:
- uid: com.microsoft.azure.batch.protocol.models._application_summary
  id: _application_summary
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_summary.displayName()
  - com.microsoft.azure.batch.protocol.models._application_summary.id()
  - com.microsoft.azure.batch.protocol.models._application_summary.versions()
  - com.microsoft.azure.batch.protocol.models._application_summary.withDisplayName(String)
  - com.microsoft.azure.batch.protocol.models._application_summary.withId(String)
  - com.microsoft.azure.batch.protocol.models._application_summary.withVersions(List<String>)
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  langs:
  - java
  name: ApplicationSummary
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationSummary
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
    startLine: 16
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Contains information about an application in an Azure Batch account. </p>
  syntax: &o1
    content: public class ApplicationSummary
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_summary.displayName()
  id: displayName()
  parent: com.microsoft.azure.batch.protocol.models._application_summary
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  langs:
  - java
  name: displayName()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationSummary.displayName()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
    startLine: 60
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the displayName value.</p>

    <p></p>
  syntax:
    content: public String displayName()
    return:
      type: "26831127"
      description: <p>the displayName value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_summary.id()
  id: id()
  parent: com.microsoft.azure.batch.protocol.models._application_summary
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  langs:
  - java
  name: id()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationSummary.id()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
    startLine: 40
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_summary.versions()
  id: versions()
  parent: com.microsoft.azure.batch.protocol.models._application_summary
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  langs:
  - java
  name: versions()
  fullName: List<String> com.microsoft.azure.batch.protocol.models.ApplicationSummary.versions()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
    startLine: 80
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the versions value.</p>

    <p></p>
  syntax:
    content: public List<String> versions()
    return:
      type: 7d60c20e
      description: <p>the versions value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_summary.withDisplayName(String)
  id: withDisplayName(String)
  parent: com.microsoft.azure.batch.protocol.models._application_summary
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  langs:
  - java
  name: withDisplayName(String displayName)
  fullName: ApplicationSummary com.microsoft.azure.batch.protocol.models.ApplicationSummary.withDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
    startLine: 70
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the displayName value.</p>

    <p></p>
  syntax:
    content: public ApplicationSummary withDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
      description: <p>the displayName value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_summary
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_summary" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_summary.withId(String)
  id: withId(String)
  parent: com.microsoft.azure.batch.protocol.models._application_summary
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  langs:
  - java
  name: withId(String id)
  fullName: ApplicationSummary com.microsoft.azure.batch.protocol.models.ApplicationSummary.withId(String id)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
    startLine: 50
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public ApplicationSummary withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_summary
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_summary" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_summary.withVersions(List<String>)
  id: withVersions(List<String>)
  parent: com.microsoft.azure.batch.protocol.models._application_summary
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  langs:
  - java
  name: withVersions(List<String> versions)
  fullName: ApplicationSummary com.microsoft.azure.batch.protocol.models.ApplicationSummary.withVersions(List<String> versions)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationSummary.java
    startLine: 90
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the versions value.</p>

    <p></p>
  syntax:
    content: public ApplicationSummary withVersions(List<String> versions)
    parameters:
    - id: versions
      type: 7d60c20e
      description: <p>the versions value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_summary
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_summary" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 7d60c20e
  spec.java:
  - name: List<String>
    fullName: List<String>
- uid: com.microsoft.azure.batch.protocol.models._application_summary
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  name: ApplicationSummary
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationSummary
  type: Class
  summary: <p>Contains information about an application in an Azure Batch account. </p>
  syntax: *o1
