items:
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63
  id: _application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63.withPfxPassword(String)
  href: com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63.yml
  langs:
  - java
  name: ApplicationGatewaySslCertificate.DefinitionStages.WithPassword<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithPassword<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 74
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an SSL certificate definition allowing to specify the password for the private key (PFX) content of the certificate. </p>
  syntax:
    content: public interface WithPassword<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63.withPfxPassword(String)
  id: withPfxPassword(String)
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63
  href: com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63.yml
  langs:
  - java
  name: withPfxPassword(String password)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithPassword<ParentT>.withPfxPassword(String password)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 80
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the password currently used to protect the provided PFX content of the SSL certificate. </p>
  syntax:
    content: public WithAttach<ParentT> withPfxPassword(String password)
    parameters:
    - id: password
      type: "26831127"
      description: <p>a password </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebfda8a2936
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebfda8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebf
    name: ApplicationGatewaySslCertificate.DefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithAttach
    href: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebf.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate._definition.yml
  name: ApplicationGatewaySslCertificate.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway SSL certificate definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends ApplicationGatewaySslCertificate.DefinitionStages.Blank<ParentT>,ApplicationGatewaySslCertificate.DefinitionStages.WithAttach<ParentT>,ApplicationGatewaySslCertificate.DefinitionStages.WithData<ParentT>,ApplicationGatewaySslCertificate.DefinitionStages.WithPassword<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebf
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebf.yml
  name: ApplicationGatewaySslCertificate.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway SSL certificate definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
