items:
- uid: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be
  id: _application_gateway_request_rout0b48dcf24d11f11af359289325f203be
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be.toBackendHttpConfiguration(String)
  - com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be.toBackendHttpPort(int)
  href: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfiguration<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfiguration<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
    startLine: 596
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway request routing rule definition allowing to specify the backend HTTP settings configuration to associate the routing rule with. </p>
  syntax:
    content: public interface WithBackendHttpConfiguration<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the application gateway definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be.toBackendHttpConfiguration(String)
  id: toBackendHttpConfiguration(String)
  parent: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be
  href: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be.yml
  langs:
  - java
  name: toBackendHttpConfiguration(String name)
  fullName: WithBackendOrAddress<ParentT> com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfiguration<ParentT>.toBackendHttpConfiguration(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
    startLine: 605
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Associates the specified backend HTTP settings configuration with this request routing rule. </p>

    <p>If the backend configuration does not exist yet, it must be defined in the optional part of the application gateway definition, using<programlisting><codeline><highlight class="normal">defineBackendHttpConfiguration(...)<sp></sp></highlight></codeline></programlisting> . The request routing rule references it only by name. </p>
  syntax:
    content: public WithBackendOrAddress<ParentT> toBackendHttpConfiguration(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of a backend HTTP settings configuration </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_request_rout767f6403d92b7a5984340f7611316de7da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be.toBackendHttpPort(int)
  id: toBackendHttpPort(int)
  parent: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be
  href: com.microsoft.azure.management.network._application_gateway_request_rout0b48dcf24d11f11af359289325f203be.yml
  langs:
  - java
  name: toBackendHttpPort(int portNumber)
  fullName: WithBackendOrAddress<ParentT> com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfiguration<ParentT>.toBackendHttpPort(int portNumber)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
    startLine: 615
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Creates a backend HTTP settings configuration for the specified backend port and the HTTP protocol, and associates it with this request routing rule. </p>

    <p>An auto-generated name will be used for this newly created configuration. </p>
  syntax:
    content: public WithBackendOrAddress<ParentT> toBackendHttpPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>the port number for a new backend HTTP settings configuration </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_request_rout767f6403d92b7a5984340f7611316de7da8a2936
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._application_gateway_request_rout767f6403d92b7a5984340f7611316de7da8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_request_rout767f6403d92b7a5984340f7611316de7
    name: ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendOrAddress
    fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendOrAddress
    href: com.microsoft.azure.management.network._application_gateway_request_rout767f6403d92b7a5984340f7611316de7.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule._update_definition.yml
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway request routing rule definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithAttach<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithFrontend<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithListener<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithFrontendPort<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithListenerOrFrontend<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackend<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendAddress<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendOrAddress<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendAddressOrAttach<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfiguration<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfigurationOrSni<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithSslCertificate<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithSslPassword<UpdateDefinitionStages.WithBackendHttpConfigurationOrSni<ParentT>>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the application gateway definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_routeda1683b8d44578112a49b8f6ef73259
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routeda1683b8d44578112a49b8f6ef73259.yml
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfigurationOrSni<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfigurationOrSni<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway request routing rule definition allowing to require server name indication if the application gateway is serving multiple websites in its backends and SSL is required. </p>
  syntax:
    content: public interface WithBackendHttpConfigurationOrSni<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the application gateway definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_rout767f6403d92b7a5984340f7611316de7
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_rout767f6403d92b7a5984340f7611316de7.yml
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendOrAddress<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendOrAddress<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway request routing rule definition allowing to add an address to specify an existing backend to associate with this request routing rule or create a new backend with an auto-generated name and addresses to it. </p>
  syntax:
    content: public interface WithBackendOrAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the application gateway definition to return to after attaching this definition </p>
