items:
- uid: com.microsoft.azure.management.website._http_logs_config
  id: _http_logs_config
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._http_logs_config.azureBlobStorage()
  - com.microsoft.azure.management.website._http_logs_config.fileSystem()
  - com.microsoft.azure.management.website._http_logs_config.withAzureBlobStorage(AzureBlobStorageHttpLogsConfig)
  - com.microsoft.azure.management.website._http_logs_config.withFileSystem(FileSystemHttpLogsConfig)
  href: com.microsoft.azure.management.website._http_logs_config.yml
  langs:
  - java
  name: HttpLogsConfig
  fullName: com.microsoft.azure.management.website.HttpLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HttpLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HttpLogsConfig.java
    startLine: 14
  package: com.microsoft.azure.management.website
  summary: <p>Http logs configuration. </p>
  syntax: &o1
    content: public class HttpLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._http_logs_config.azureBlobStorage()
  id: azureBlobStorage()
  parent: com.microsoft.azure.management.website._http_logs_config
  href: com.microsoft.azure.management.website._http_logs_config.yml
  langs:
  - java
  name: azureBlobStorage()
  fullName: AzureBlobStorageHttpLogsConfig com.microsoft.azure.management.website.HttpLogsConfig.azureBlobStorage()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HttpLogsConfig.java
    startLine: 50
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the azureBlobStorage value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageHttpLogsConfig azureBlobStorage()
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
      description: <p>the azureBlobStorage value </p>
- uid: com.microsoft.azure.management.website._http_logs_config.fileSystem()
  id: fileSystem()
  parent: com.microsoft.azure.management.website._http_logs_config
  href: com.microsoft.azure.management.website._http_logs_config.yml
  langs:
  - java
  name: fileSystem()
  fullName: FileSystemHttpLogsConfig com.microsoft.azure.management.website.HttpLogsConfig.fileSystem()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HttpLogsConfig.java
    startLine: 30
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the fileSystem value.</p>

    <p></p>
  syntax:
    content: public FileSystemHttpLogsConfig fileSystem()
    return:
      type: com.microsoft.azure.management.website._file_system_http_logs_config
      description: <p>the fileSystem value </p>
- uid: com.microsoft.azure.management.website._http_logs_config.withAzureBlobStorage(AzureBlobStorageHttpLogsConfig)
  id: withAzureBlobStorage(AzureBlobStorageHttpLogsConfig)
  parent: com.microsoft.azure.management.website._http_logs_config
  href: com.microsoft.azure.management.website._http_logs_config.yml
  langs:
  - java
  name: withAzureBlobStorage(AzureBlobStorageHttpLogsConfig azureBlobStorage)
  fullName: HttpLogsConfig com.microsoft.azure.management.website.HttpLogsConfig.withAzureBlobStorage(AzureBlobStorageHttpLogsConfig azureBlobStorage)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HttpLogsConfig.java
    startLine: 60
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the azureBlobStorage value.</p>

    <p></p>
  syntax:
    content: public HttpLogsConfig withAzureBlobStorage(AzureBlobStorageHttpLogsConfig azureBlobStorage)
    parameters:
    - id: azureBlobStorage
      type: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
      description: <p>the azureBlobStorage value to set </p>
    return:
      type: com.microsoft.azure.management.website._http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._http_logs_config.withFileSystem(FileSystemHttpLogsConfig)
  id: withFileSystem(FileSystemHttpLogsConfig)
  parent: com.microsoft.azure.management.website._http_logs_config
  href: com.microsoft.azure.management.website._http_logs_config.yml
  langs:
  - java
  name: withFileSystem(FileSystemHttpLogsConfig fileSystem)
  fullName: HttpLogsConfig com.microsoft.azure.management.website.HttpLogsConfig.withFileSystem(FileSystemHttpLogsConfig fileSystem)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HttpLogsConfig.java
    startLine: 40
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the fileSystem value.</p>

    <p></p>
  syntax:
    content: public HttpLogsConfig withFileSystem(FileSystemHttpLogsConfig fileSystem)
    parameters:
    - id: fileSystem
      type: com.microsoft.azure.management.website._file_system_http_logs_config
      description: <p>the fileSystem value to set </p>
    return:
      type: com.microsoft.azure.management.website._http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: com.microsoft.azure.management.website._file_system_http_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  name: FileSystemHttpLogsConfig
  fullName: com.microsoft.azure.management.website.FileSystemHttpLogsConfig
  type: Class
  summary: <p>Http logs to file system configuration. </p>
  syntax:
    content: public class FileSystemHttpLogsConfig
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  name: AzureBlobStorageHttpLogsConfig
  fullName: com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig
  type: Class
  summary: <p>Http logs to azure blob storage configuration. </p>
  syntax:
    content: public class AzureBlobStorageHttpLogsConfig
- uid: com.microsoft.azure.management.website._http_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._http_logs_config.yml
  name: HttpLogsConfig
  fullName: com.microsoft.azure.management.website.HttpLogsConfig
  type: Class
  summary: <p>Http logs configuration. </p>
  syntax: *o1
