items:
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebf
  id: _application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebf
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certific1e9545fa67b34260ef5c0aa1ee1a7ebf.yml
  langs:
  - java
  name: ApplicationGatewaySslCertificate.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 46
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The final stage of an application gateway SSL certificate definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: Attachable.InDefinition<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition<ParentT>
  type: Interface
  summary: <p>The final stage of the child object definition, as which it can be attached to the parent. </p>
  syntax:
    content: public interface InDefinition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate._definition.yml
  name: ApplicationGatewaySslCertificate.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway SSL certificate definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends ApplicationGatewaySslCertificate.DefinitionStages.Blank<ParentT>,ApplicationGatewaySslCertificate.DefinitionStages.WithAttach<ParentT>,ApplicationGatewaySslCertificate.DefinitionStages.WithData<ParentT>,ApplicationGatewaySslCertificate.DefinitionStages.WithPassword<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
