items:
- uid: com.microsoft.applicationinsights.channel
  id: channel
  children:
  - com.microsoft.applicationinsights.channel._telemetry_channel
  - com.microsoft.applicationinsights.channel._telemetry_sampler
  href: com.microsoft.applicationinsights.channel.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.channel
  fullName: com.microsoft.applicationinsights.channel
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 21
  syntax:
    content: package com.microsoft.applicationinsights.channel
references:
- uid: com.microsoft.applicationinsights.channel._telemetry_channel
  parent: com.microsoft.applicationinsights.channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: TelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.TelemetryChannel
  type: Interface
  summary: <p>Represents a communication channel for sending telemetry to application insights. </p>
  syntax:
    content: public interface TelemetryChannel
- uid: com.microsoft.applicationinsights.channel._telemetry_sampler
  parent: com.microsoft.applicationinsights.channel
  href: com.microsoft.applicationinsights.channel._telemetry_sampler.yml
  name: TelemetrySampler
  fullName: com.microsoft.applicationinsights.channel.TelemetrySampler
  type: Interface
  summary: <p>Telemetry Sampler might be used to reduce the amount of telemetries that are sent by the SDK. Sampling reduces the volume of telemetry without affecting your statistics. It keeps together related data points so that you can navigate between them when diagnosing a problem. In the portal, the total counts are multiplied to compensate for the sampling. </p>
  syntax:
    content: public interface TelemetrySampler
