items:
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type
  id: _logger_output_type
  parent: com.microsoft.applicationinsights.internal.logger
  children:
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.CONSOLE()
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.FILE()
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.yml
  langs:
  - java
  name: InternalLogger.LoggerOutputType
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggerOutputType
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public enum LoggerOutputType
  inheritance:
  - java.lang.Object
  - java.lang.Enum<InternalLogger.LoggerOutputType>
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.CONSOLE()
  id: CONSOLE()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.yml
  langs:
  - java
  name: CONSOLE
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggerOutputType.CONSOLE
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 65
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public CONSOLE
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.FILE()
  id: FILE()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logger_output_type.yml
  langs:
  - java
  name: FILE
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggerOutputType.FILE
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public FILE
references: []
