items:
- uid: com.microsoft.azure.management.network._application_gateway._update_stages._with_instance_count
  id: _with_instance_count
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._update_stages._with_instance_count.withInstanceCount(int)
  href: com.microsoft.azure.management.network._application_gateway._update_stages._with_instance_count.yml
  langs:
  - java
  name: ApplicationGateway.UpdateStages.WithInstanceCount
  fullName: com.microsoft.azure.management.network.ApplicationGateway.UpdateStages.WithInstanceCount
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 674
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway update allowing to specify the capacity (number of instances) of the application gateway. </p>
  syntax:
    content: public interface WithInstanceCount
- uid: com.microsoft.azure.management.network._application_gateway._update_stages._with_instance_count.withInstanceCount(int)
  id: withInstanceCount(int)
  parent: com.microsoft.azure.management.network._application_gateway._update_stages._with_instance_count
  href: com.microsoft.azure.management.network._application_gateway._update_stages._with_instance_count.yml
  langs:
  - java
  name: withInstanceCount(int instanceCount)
  fullName: Update com.microsoft.azure.management.network.ApplicationGateway.UpdateStages.WithInstanceCount.withInstanceCount(int instanceCount)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 680
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the capacity (number of instances) for the application gateway. </p>
  syntax:
    content: public Update withInstanceCount(int instanceCount)
    parameters:
    - id: instanceCount
      type: f75371fa
      description: <p>the capacity as a number between 1 and 10 but also based on the limits imposed by the selected applicatiob gateway size </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._update
      description: <p>the next stage of the update </p>
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.management.network._application_gateway._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._update.yml
  name: ApplicationGateway.Update
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Update
  type: Interface
  summary: >-
    <p>The template for an application gateway update operation, containing all the settings that can be modified. </p>

    <p>Call<programlisting><codeline><highlight class="normal">apply()<sp></sp></highlight></codeline></programlisting> to apply the changes to the resource in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Update extends Appliable<ApplicationGateway>,Resource.UpdateWithTags<Update>,ApplicationGateway.UpdateStages.WithSize,ApplicationGateway.UpdateStages.WithInstanceCount,ApplicationGateway.UpdateStages.WithBackend,ApplicationGateway.UpdateStages.WithBackendHttpConfig,ApplicationGateway.UpdateStages.WithIpConfig,ApplicationGateway.UpdateStages.WithFrontend,ApplicationGateway.UpdateStages.WithPublicIpAddress,ApplicationGateway.UpdateStages.WithFrontendPort,ApplicationGateway.UpdateStages.WithSslCert,ApplicationGateway.UpdateStages.WithListener,ApplicationGateway.UpdateStages.WithRequestRoutingRule,ApplicationGateway.UpdateStages.WithExistingSubnet
