items:
- uid: com.microsoft.azure.management.network._network_interface_dns_settings
  id: _network_interface_dns_settings
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._network_interface_dns_settings.appliedDnsServers()
  - com.microsoft.azure.management.network._network_interface_dns_settings.dnsServers()
  - com.microsoft.azure.management.network._network_interface_dns_settings.internalDnsNameLabel()
  - com.microsoft.azure.management.network._network_interface_dns_settings.internalDomainNameSuffix()
  - com.microsoft.azure.management.network._network_interface_dns_settings.internalFqdn()
  - com.microsoft.azure.management.network._network_interface_dns_settings.withAppliedDnsServers(List<String>)
  - com.microsoft.azure.management.network._network_interface_dns_settings.withDnsServers(List<String>)
  - com.microsoft.azure.management.network._network_interface_dns_settings.withInternalDnsNameLabel(String)
  - com.microsoft.azure.management.network._network_interface_dns_settings.withInternalDomainNameSuffix(String)
  - com.microsoft.azure.management.network._network_interface_dns_settings.withInternalFqdn(String)
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: NetworkInterfaceDnsSettings
  fullName: com.microsoft.azure.management.network.NetworkInterfaceDnsSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Dns settings of a network interface. </p>
  syntax: &o1
    content: public class NetworkInterfaceDnsSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.appliedDnsServers()
  id: appliedDnsServers()
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: appliedDnsServers()
  fullName: List<String> com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.appliedDnsServers()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 66
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the appliedDnsServers value.</p>

    <p></p>
  syntax:
    content: public List<String> appliedDnsServers()
    return:
      type: 7d60c20e
      description: <p>the appliedDnsServers value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.dnsServers()
  id: dnsServers()
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: dnsServers()
  fullName: List<String> com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.dnsServers()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 46
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the dnsServers value.</p>

    <p></p>
  syntax:
    content: public List<String> dnsServers()
    return:
      type: 7d60c20e
      description: <p>the dnsServers value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.internalDnsNameLabel()
  id: internalDnsNameLabel()
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: internalDnsNameLabel()
  fullName: String com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.internalDnsNameLabel()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 86
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the internalDnsNameLabel value.</p>

    <p></p>
  syntax:
    content: public String internalDnsNameLabel()
    return:
      type: "26831127"
      description: <p>the internalDnsNameLabel value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.internalDomainNameSuffix()
  id: internalDomainNameSuffix()
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: internalDomainNameSuffix()
  fullName: String com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.internalDomainNameSuffix()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 126
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the internalDomainNameSuffix value.</p>

    <p></p>
  syntax:
    content: public String internalDomainNameSuffix()
    return:
      type: "26831127"
      description: <p>the internalDomainNameSuffix value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.internalFqdn()
  id: internalFqdn()
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: internalFqdn()
  fullName: String com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.internalFqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 106
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the internalFqdn value.</p>

    <p></p>
  syntax:
    content: public String internalFqdn()
    return:
      type: "26831127"
      description: <p>the internalFqdn value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.withAppliedDnsServers(List<String>)
  id: withAppliedDnsServers(List<String>)
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withAppliedDnsServers(List<String> appliedDnsServers)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withAppliedDnsServers(List<String> appliedDnsServers)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 76
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the appliedDnsServers value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withAppliedDnsServers(List<String> appliedDnsServers)
    parameters:
    - id: appliedDnsServers
      type: 7d60c20e
      description: <p>the appliedDnsServers value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.withDnsServers(List<String>)
  id: withDnsServers(List<String>)
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withDnsServers(List<String> dnsServers)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withDnsServers(List<String> dnsServers)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 56
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the dnsServers value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withDnsServers(List<String> dnsServers)
    parameters:
    - id: dnsServers
      type: 7d60c20e
      description: <p>the dnsServers value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.withInternalDnsNameLabel(String)
  id: withInternalDnsNameLabel(String)
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withInternalDnsNameLabel(String internalDnsNameLabel)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withInternalDnsNameLabel(String internalDnsNameLabel)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 96
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the internalDnsNameLabel value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withInternalDnsNameLabel(String internalDnsNameLabel)
    parameters:
    - id: internalDnsNameLabel
      type: "26831127"
      description: <p>the internalDnsNameLabel value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.withInternalDomainNameSuffix(String)
  id: withInternalDomainNameSuffix(String)
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withInternalDomainNameSuffix(String internalDomainNameSuffix)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withInternalDomainNameSuffix(String internalDomainNameSuffix)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 136
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the internalDomainNameSuffix value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withInternalDomainNameSuffix(String internalDomainNameSuffix)
    parameters:
    - id: internalDomainNameSuffix
      type: "26831127"
      description: <p>the internalDomainNameSuffix value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings.withInternalFqdn(String)
  id: withInternalFqdn(String)
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withInternalFqdn(String internalFqdn)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withInternalFqdn(String internalFqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 116
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the internalFqdn value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withInternalFqdn(String internalFqdn)
    parameters:
    - id: internalFqdn
      type: "26831127"
      description: <p>the internalFqdn value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 7d60c20e
  spec.java:
  - name: List<String>
    fullName: List<String>
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._network_interface_dns_settings
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  name: NetworkInterfaceDnsSettings
  fullName: com.microsoft.azure.management.network.NetworkInterfaceDnsSettings
  type: Class
  summary: <p>Dns settings of a network interface. </p>
  syntax: *o1
