items:
- uid: com.microsoft.azure.management.batch._batch_account._definition_stages._with_application
  id: _with_application
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._batch_account._definition_stages._with_application.defineNewApplication(String)
  href: com.microsoft.azure.management.batch._batch_account._definition_stages._with_application.yml
  langs:
  - java
  name: BatchAccount.DefinitionStages.WithApplication
  fullName: com.microsoft.azure.management.batch.BatchAccount.DefinitionStages.WithApplication
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
    startLine: 128
  package: com.microsoft.azure.management.batch
  summary: <p>A batch account definition to allow creation of application. </p>
  syntax:
    content: public interface WithApplication
- uid: com.microsoft.azure.management.batch._batch_account._definition_stages._with_application.defineNewApplication(String)
  id: defineNewApplication(String)
  parent: com.microsoft.azure.management.batch._batch_account._definition_stages._with_application
  href: com.microsoft.azure.management.batch._batch_account._definition_stages._with_application.yml
  langs:
  - java
  name: defineNewApplication(String applicationId)
  fullName: Application.DefinitionStages.Blank<WithApplicationAndStorage> com.microsoft.azure.management.batch.BatchAccount.DefinitionStages.WithApplication.defineNewApplication(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
    startLine: 135
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>First stage to create new application in Batch account.</p>

    <p></p>
  syntax:
    content: public Application.DefinitionStages.Blank<WithApplicationAndStorage> defineNewApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>id of the application to create </p>
    return:
      type: f6c8f769com.microsoft.azure.management.batch._batch_account._definition_stage0d783d9e8264e6921b5a7ac57082dfd6a08ddfce
      description: <p>next stage to create the Batch account. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f6c8f769com.microsoft.azure.management.batch._batch_account._definition_stage0d783d9e8264e6921b5a7ac57082dfd6a08ddfce
  spec.java:
  - name: Application.DefinitionStages.Blank<
    fullName: Application.DefinitionStages.Blank<
  - uid: com.microsoft.azure.management.batch._batch_account._definition_stage0d783d9e8264e6921b5a7ac57082dfd6
    name: BatchAccount.DefinitionStages.WithApplicationAndStorage
    fullName: com.microsoft.azure.management.batch.BatchAccount.DefinitionStages.WithApplicationAndStorage
    href: com.microsoft.azure.management.batch._batch_account._definition_stage0d783d9e8264e6921b5a7ac57082dfd6.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.batch._batch_account._definition
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._batch_account._definition.yml
  name: BatchAccount.Definition
  fullName: com.microsoft.azure.management.batch.BatchAccount.Definition
  type: Interface
  summary: <p>Container interface for all the definitions that need to be implemented. </p>
  syntax:
    content: public interface Definition extends BatchAccount.DefinitionStages.Blank,BatchAccount.DefinitionStages.WithGroup,BatchAccount.DefinitionStages.WithCreate,BatchAccount.DefinitionStages.WithApplicationAndStorage,BatchAccount.DefinitionStages.WithCreateAndApplication,BatchAccount.DefinitionStages.WithApplication,BatchAccount.DefinitionStages.WithStorage
- uid: com.microsoft.azure.management.batch._batch_account._definition_stage0d783d9e8264e6921b5a7ac57082dfd6
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._batch_account._definition_stage0d783d9e8264e6921b5a7ac57082dfd6.yml
  name: BatchAccount.DefinitionStages.WithApplicationAndStorage
  fullName: com.microsoft.azure.management.batch.BatchAccount.DefinitionStages.WithApplicationAndStorage
  type: Interface
  summary: <p>A batch account definition allowing defining application and storage account. </p>
  syntax:
    content: public interface WithApplicationAndStorage
- uid: com.microsoft.azure.management.batch.implementation._batch_account_impl.defineNewApplication(String)
  parent: com.microsoft.azure.management.batch.implementation._batch_account_impl
  href: com.microsoft.azure.management.batch.implementation._batch_account_impl.yml
  name: defineNewApplication(String applicationId)
  fullName: ApplicationImpl com.microsoft.azure.management.batch.implementation.BatchAccountImpl.defineNewApplication(String applicationId)
  type: Method
  summary: >-
    <p>First stage to create new application in Batch account.</p>

    <p></p>
  syntax:
    content: public ApplicationImpl defineNewApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>id of the application to create </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_impl
      description: <p>next stage to create the Batch account. </p>
