items:
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  id: _page_view_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.additionalSanitize()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.getData()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.getDuration()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.getMetrics()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.getName()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.getSamplingPercentage()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.getUri()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.PageViewTelemetry()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.PageViewTelemetry(String)
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.setDuration(long)
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.setName(String)
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.setSamplingPercentage(Double)
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry.setUrl(URI)
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: PageViewTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.PageViewTelemetry
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 35
  package: com.microsoft.applicationinsights.telemetry
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track page views.</p>

    <p>You can send information about pages viewed by your application to Application Insights by passing an instance of this class to the 'trackPageView' method of the <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public class PageViewTelemetry extends BaseSampleSourceTelemetry<PageViewData>
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  inheritedMembers:
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.reset()
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.setSampleRate(Envelope)
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.additionalSanitize()
  id: additionalSanitize()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: additionalSanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetry.additionalSanitize()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 128
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: protected void additionalSanitize()
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: getData()
  fullName: PageViewData com.microsoft.applicationinsights.telemetry.PageViewTelemetry.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 135
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: protected PageViewData getData()
    return:
      type: b8925027
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.getDuration()
  id: getDuration()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: getDuration()
  fullName: long com.microsoft.applicationinsights.telemetry.PageViewTelemetry.getDuration()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 97
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets the page view duration. </p>
  syntax:
    content: public long getDuration()
    return:
      type: 0364520f
      description: <p>The page view duration. </p>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.getMetrics()
  id: getMetrics()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: getMetrics()
  fullName: ConcurrentMap<String, Double> com.microsoft.applicationinsights.telemetry.PageViewTelemetry.getMetrics()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 113
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets a dictionary of custom defined metrics. </p>
  syntax:
    content: public ConcurrentMap<String, Double> getMetrics()
    return:
      type: 5f392589
      description: <p>Custom defined metrics. </p>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.getName()
  id: getName()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: getName()
  fullName: String com.microsoft.applicationinsights.telemetry.PageViewTelemetry.getName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 68
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets the name of the page view. </p>
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>The page view name. </p>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.getSamplingPercentage()
  id: getSamplingPercentage()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: getSamplingPercentage()
  fullName: Double com.microsoft.applicationinsights.telemetry.PageViewTelemetry.getSamplingPercentage()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 118
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Double getSamplingPercentage()
    return:
      type: 8dd309d9
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.getUri()
  id: getUri()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: getUri()
  fullName: URI com.microsoft.applicationinsights.telemetry.PageViewTelemetry.getUri()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 76
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets the page view Uri. </p>
  syntax:
    content: public URI getUri()
    return:
      type: "62304784"
      description: <p>The page view Uri. </p>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.PageViewTelemetry()
  id: PageViewTelemetry()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: PageViewTelemetry()
  fullName: com.microsoft.applicationinsights.telemetry.PageViewTelemetry.PageViewTelemetry()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 42
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Default Ctor </p>
  syntax:
    content: public PageViewTelemetry()
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.PageViewTelemetry(String)
  id: PageViewTelemetry(String)
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: PageViewTelemetry(String pageName)
  fullName: com.microsoft.applicationinsights.telemetry.PageViewTelemetry.PageViewTelemetry(String pageName)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 51
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Initializes a new instance of the class with the specified 'pageName' </p>
  syntax:
    content: public PageViewTelemetry(String pageName)
    parameters:
    - id: pageName
      type: "26831127"
      description: <p>The name of page to track. </p>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.setDuration(long)
  id: setDuration(long)
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: setDuration(long duration)
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetry.setDuration(long duration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 105
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sets the page view duration. </p>
  syntax:
    content: public void setDuration(long duration)
    parameters:
    - id: duration
      type: 0364520f
      description: <p>The page view duration. </p>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.setName(String)
  id: setName(String)
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: setName(String name)
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetry.setName(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 60
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sets the name of the page view. </p>
  syntax:
    content: public void setName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>The page view name. </p>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.setSamplingPercentage(Double)
  id: setSamplingPercentage(Double)
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: setSamplingPercentage(Double samplingPercentage)
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetry.setSamplingPercentage(Double samplingPercentage)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 123
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void setSamplingPercentage(Double samplingPercentage)
    parameters:
    - id: samplingPercentage
      type: 8dd309d9
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry.setUrl(URI)
  id: setUrl(URI)
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  langs:
  - java
  name: setUrl(URI url)
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetry.setUrl(URI url)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java
    startLine: 89
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sets the page view Uri. </p>
  syntax:
    content: public void setUrl(URI url)
    parameters:
    - id: url
      type: "62304784"
      description: <p>The page view Uri. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 5f392589
  spec.java:
  - name: ConcurrentMap<String, Double>
    fullName: ConcurrentMap<String, Double>
- uid: 8dd309d9
  spec.java:
  - name: Double
    fullName: Double
- uid: b8925027
  spec.java:
  - name: PageViewData
    fullName: PageViewData
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.reset()
  parent: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: reset()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T extends SendableData>.reset()
  type: Method
  syntax:
    content: public void reset()
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.setSampleRate(Envelope)
  parent: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: setSampleRate(Envelope envelope)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T extends SendableData>.setSampleRate(Envelope envelope)
  type: Method
  syntax:
    content: protected void setSampleRate(Envelope envelope)
    parameters:
    - id: envelope
      type: ec5c4d5a
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: BaseSampleSourceTelemetry<T>
  fullName: com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T>
  type: Class
  summary: <p>Created by gupele on 12/4/2016. </p>
  syntax:
    content: public class BaseSampleSourceTelemetry<T extends SendableData> extends BaseTelemetry<T> implements SupportSampling
    typeParameters:
    - type: 8ce1ecb9
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Create an instance of this class to send telemetry to Azure Application Insights. General overview <ulink url="https://docs.microsoft.com/azure/application-insights/app-insights-api-custom-events-metrics">https://docs.microsoft.com/azure/application-insights/app-insights-api-custom-events-metrics</ulink></p>
  syntax:
    content: public class TelemetryClient
