items:
- uid: com.microsoft.azure.management.network._application_gateway_request_routfee49b911fd411fd9ec50d30a011ec45
  id: _application_gateway_request_routfee49b911fd411fd9ec50d30a011ec45
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routfee49b911fd411fd9ec50d30a011ec45.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithSslCertificate<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithSslCertificate<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
    startLine: 493
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway request routing rule allowing to specify an SSL certificate. </p>
  syntax:
    content: public interface WithSslCertificate<ParentT> extends HasSslCertificate<T>.UpdateDefinitionStages.WithSslCertificate<WithBackendHttpConfigurationOrSni<ParentT>>
    typeParameters:
    - type: 18a275b1
      description: <p>the next stage of the definition </p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73.withSslCertificate(String)
  - com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73.withSslCertificateFromPfxFile(File)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73.withSslCertificate(String)
  parent: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73
  href: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73.yml
  name: withSslCertificate(String name)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasSslCertificate<T>.UpdateDefinitionStages.WithSslCertificate<ReturnT>.withSslCertificate(String name)
  type: Method
  summary: >-
    <p>Specifies an SSL certificate to associate with this resource. </p>

    <p>If the certificate does not exist yet, it must be defined in the optional part of the parent resource definition. </p>
  syntax:
    content: public ReturnT withSslCertificate(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of an existing SSL certificate. </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73.withSslCertificateFromPfxFile(File)
  parent: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73
  href: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73.yml
  name: withSslCertificateFromPfxFile(File pfxFile)
  fullName: WithSslPassword<ReturnT> com.microsoft.azure.management.network.model.HasSslCertificate<T>.UpdateDefinitionStages.WithSslCertificate<ReturnT>.withSslCertificateFromPfxFile(File pfxFile)
  type: Method
  summary: >-
    <p>Specifies the PFX file to import the SSL certificate from to associated with this resource. </p>

    <p>The certificate will be named using an auto-generated name. </p>
  syntax:
    content: public WithSslPassword<ReturnT> withSslCertificateFromPfxFile(File pfxFile)
    parameters:
    - id: pfxFile
      type: 8291270b
      description: <p>an existing PFX file </p>
    return:
      type: com.microsoft.azure.management.network.model._has_ssl_certificate.c3388edd83b69882121de2bea3113f695b94c421
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_ssl_certificate.4a195760de846356dd70bfe786a80e73.yml
  name: HasSslCertificate.UpdateDefinitionStages.WithSslCertificate<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasSslCertificate.UpdateDefinitionStages.WithSslCertificate<ReturnT>
  type: Interface
  summary: <p>The stage of a resource definition allowing to specify the SSL certificate to associate with it. </p>
  syntax:
    content: public interface WithSslCertificate<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule._update_definition.yml
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway request routing rule definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithAttach<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithFrontend<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithListener<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithFrontendPort<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithListenerOrFrontend<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackend<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendAddress<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendOrAddress<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendAddressOrAttach<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfiguration<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithBackendHttpConfigurationOrSni<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithSslCertificate<ParentT>,ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithSslPassword<UpdateDefinitionStages.WithBackendHttpConfigurationOrSni<ParentT>>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the application gateway definition to return to after attaching this definition </p>
