items:
- uid: com.microsoft.azure.management.redis.implementation._redis_manager._configurable
  id: _configurable
  parent: com.microsoft.azure.management.redis.implementation
  children:
  - com.microsoft.azure.management.redis.implementation._redis_manager._configurable.authenticate(AzureTokenCredentials,String)
  href: com.microsoft.azure.management.redis.implementation._redis_manager._configurable.yml
  langs:
  - java
  name: RedisManager.Configurable
  fullName: com.microsoft.azure.management.redis.implementation.RedisManager.Configurable
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-redis/src/main/java/com/microsoft/azure/management/redis/implementation/RedisManager.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-redis/src/main/java/com/microsoft/azure/management/redis/implementation/RedisManager.java
    startLine: 78
  package: com.microsoft.azure.management.redis.implementation
  summary: <p>The interface allowing configurations to be set. </p>
  syntax:
    content: public interface Configurable extends AzureConfigurable<Configurable>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withCallbackExecutor(Executor)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withConnectionTimeout(long,TimeUnit)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withInterceptor(Interceptor)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withLogLevel(HttpLoggingInterceptor.Level)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withMaxIdleConnections(int)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withProxy(Proxy)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withReadTimeout(long,TimeUnit)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withUserAgent(String)
- uid: com.microsoft.azure.management.redis.implementation._redis_manager._configurable.authenticate(AzureTokenCredentials,String)
  id: authenticate(AzureTokenCredentials,String)
  parent: com.microsoft.azure.management.redis.implementation._redis_manager._configurable
  href: com.microsoft.azure.management.redis.implementation._redis_manager._configurable.yml
  langs:
  - java
  name: authenticate(AzureTokenCredentials credentials, String subscriptionId)
  fullName: RedisManager com.microsoft.azure.management.redis.implementation.RedisManager.Configurable.authenticate(AzureTokenCredentials credentials, String subscriptionId)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-redis/src/main/java/com/microsoft/azure/management/redis/implementation/RedisManager.java
    startLine: 86
  package: com.microsoft.azure.management.redis.implementation
  summary: >-
    <p>Creates an instance of <xref href="com.microsoft.azure.management.redis.implementation._redis_manager" data-throw-if-not-resolved="false"></xref> that exposes Redis management API entry points.</p>

    <p></p>
  syntax:
    content: public RedisManager authenticate(AzureTokenCredentials credentials, String subscriptionId)
    parameters:
    - id: credentials
      type: f380981c
      description: <p>the credentials to use </p>
    - id: subscriptionId
      type: "26831127"
      description: <p>the subscription UUID </p>
    return:
      type: com.microsoft.azure.management.redis.implementation._redis_manager
      description: <p>the interface exposing Redis management API entry points that work across subscriptions </p>
references:
- uid: f380981c
  spec.java:
  - name: AzureTokenCredentials
    fullName: AzureTokenCredentials
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withCallbackExecutor(Executor)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withCallbackExecutor(Executor executor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withCallbackExecutor(Executor executor)
  type: Method
  summary: >-
    <p>Sets the executor for async callbacks to run on.</p>

    <p></p>
  syntax:
    content: public T withCallbackExecutor(Executor executor)
    parameters:
    - id: executor
      type: 6f968643
      description: <p>the executor to execute the callbacks. </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withConnectionTimeout(long,TimeUnit)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withConnectionTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withConnectionTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the connection timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withConnectionTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withInterceptor(Interceptor)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withInterceptor(Interceptor interceptor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withInterceptor(Interceptor interceptor)
  type: Method
  summary: >-
    <p>Plug in an interceptor into the HTTP pipeline.</p>

    <p></p>
  syntax:
    content: public T withInterceptor(Interceptor interceptor)
    parameters:
    - id: interceptor
      type: 910a0506
      description: <p>the interceptor to plug in </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withLogLevel(HttpLoggingInterceptor.Level)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withLogLevel(HttpLoggingInterceptor.Level level)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withLogLevel(HttpLoggingInterceptor.Level level)
  type: Method
  summary: >-
    <p>Set the logging level on the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withLogLevel(HttpLoggingInterceptor.Level level)
    parameters:
    - id: level
      type: b12c7a8c
      description: <p>the OkHttp logging level </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withMaxIdleConnections(int)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withMaxIdleConnections(int maxIdleConnections)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withMaxIdleConnections(int maxIdleConnections)
  type: Method
  summary: >-
    <p>Set the maximum idle connections for the HTTP client. Default is 5.</p>

    <p></p>
  syntax:
    content: public T withMaxIdleConnections(int maxIdleConnections)
    parameters:
    - id: maxIdleConnections
      type: f75371fa
      description: <p>the maximum idle connections </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withProxy(Proxy)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withProxy(Proxy proxy)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withProxy(Proxy proxy)
  type: Method
  summary: >-
    <p>Sets the proxy for the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withProxy(Proxy proxy)
    parameters:
    - id: proxy
      type: abc26ef5
      description: <p>the proxy to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withReadTimeout(long,TimeUnit)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withReadTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withReadTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the read timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withReadTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withUserAgent(String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withUserAgent(String userAgent)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T extends AzureConfigurable<T>.withUserAgent(String userAgent)
  type: Method
  summary: >-
    <p>Specify the user agent header.</p>

    <p></p>
  syntax:
    content: public T withUserAgent(String userAgent)
    parameters:
    - id: userAgent
      type: "26831127"
      description: <p>the user agent to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  parent: com.microsoft.azure.management.resources.fluentcore.arm
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: AzureConfigurable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T>
  type: Interface
  summary: >-
    <p>The base interface for allowing configurations to be made on the HTTP client.</p>

    <p></p>
  syntax:
    content: public interface AzureConfigurable<T extends AzureConfigurable<T>>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the actual type of the interface extending this interface </p>
- uid: com.microsoft.azure.management.redis.implementation._redis_manager
  parent: com.microsoft.azure.management.redis.implementation
  href: com.microsoft.azure.management.redis.implementation._redis_manager.yml
  name: RedisManager
  fullName: com.microsoft.azure.management.redis.implementation.RedisManager
  type: Class
  summary: <p>Entry point to <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> redis resource management. </p>
  syntax:
    content: public class RedisManager
