items:
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  id: _compute_node_get_remote_login_settings_options
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.clientRequestId()
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.ocpDate()
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.returnClientRequestId()
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.timeout()
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withClientRequestId(String)
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withOcpDate(DateTime)
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withReturnClientRequestId(Boolean)
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withTimeout(Integer)
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: ComputeNodeGetRemoteLoginSettingsOptions
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Additional parameters for the ComputeNode_GetRemoteLoginSettings operation. </p>
  syntax: &o1
    content: public class ComputeNodeGetRemoteLoginSettingsOptions
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.clientRequestId()
  id: clientRequestId()
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 72
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.ocpDate()
  id: ocpDate()
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: ocpDate()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.ocpDate()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 112
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the ocpDate value.</p>

    <p></p>
  syntax:
    content: public DateTime ocpDate()
    return:
      type: 230df18c
      description: <p>the ocpDate value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.returnClientRequestId()
  id: returnClientRequestId()
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: returnClientRequestId()
  fullName: Boolean com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.returnClientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 92
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public Boolean returnClientRequestId()
    return:
      type: 866c2227
      description: <p>the returnClientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.timeout()
  id: timeout()
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: timeout()
  fullName: Integer com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.timeout()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 52
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the timeout value.</p>

    <p></p>
  syntax:
    content: public Integer timeout()
    return:
      type: 08effaa0
      description: <p>the timeout value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withClientRequestId(String)
  id: withClientRequestId(String)
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 82
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withOcpDate(DateTime)
  id: withOcpDate(DateTime)
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withOcpDate(DateTime ocpDate)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withOcpDate(DateTime ocpDate)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 125
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the ocpDate value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withOcpDate(DateTime ocpDate)
    parameters:
    - id: ocpDate
      type: 230df18c
      description: <p>the ocpDate value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withReturnClientRequestId(Boolean)
  id: withReturnClientRequestId(Boolean)
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withReturnClientRequestId(Boolean returnClientRequestId)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withReturnClientRequestId(Boolean returnClientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 102
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withReturnClientRequestId(Boolean returnClientRequestId)
    parameters:
    - id: returnClientRequestId
      type: 866c2227
      description: <p>the returnClientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.withTimeout(Integer)
  id: withTimeout(Integer)
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withTimeout(Integer timeout)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withTimeout(Integer timeout)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 62
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the timeout value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withTimeout(Integer timeout)
    parameters:
    - id: timeout
      type: 08effaa0
      description: <p>the timeout value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  name: ComputeNodeGetRemoteLoginSettingsOptions
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions
  type: Class
  summary: <p>Additional parameters for the ComputeNode_GetRemoteLoginSettings operation. </p>
  syntax: *o1
