items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_http8c41308b050ea24ad7741d41421e1f1d
  id: _application_gateway_backend_http8c41308b050ea24ad7741d41421e1f1d
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http8c41308b050ea24ad7741d41421e1f1d.yml
  langs:
  - java
  name: ApplicationGatewayBackendHttpConfiguration.UpdateStages
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 117
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of application gateway backend HTTP configuration update stages. </p>
  syntax:
    content: public interface UpdateStages
references: []
