items:
- uid: com.microsoft.azure.management.network._application_gateway_listener.919504953ec9be5789fb69b685038032
  id: 919504953ec9be5789fb69b685038032
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_listener.919504953ec9be5789fb69b685038032.yml
  langs:
  - java
  name: ApplicationGatewayListener.UpdateDefinitionStages.WithServerNameIndication<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayListener.UpdateDefinitionStages.WithServerNameIndication<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayListener.java
    startLine: 392
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway frontend listener definition allowing to require server name indication (SNI). </p>
  syntax:
    content: public interface WithServerNameIndication<ParentT> extends HasServerNameIndication.UpdateDefinitionStages.WithServerNameIndication<WithAttach<ParentT>>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching this definition </p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9.withoutServerNameIndication()
  - com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9.withServerNameIndication()
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9.withoutServerNameIndication()
  parent: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9
  href: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9.yml
  name: withoutServerNameIndication()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasServerNameIndication.UpdateDefinitionStages.WithServerNameIndication<ReturnT>.withoutServerNameIndication()
  type: Method
  summary: <p>Ensures server name indication (SNI) is not required. </p>
  syntax:
    content: public ReturnT withoutServerNameIndication()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9.withServerNameIndication()
  parent: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9
  href: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9.yml
  name: withServerNameIndication()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasServerNameIndication.UpdateDefinitionStages.WithServerNameIndication<ReturnT>.withServerNameIndication()
  type: Method
  summary: <p>Requires server name indication (SNI). </p>
  syntax:
    content: public ReturnT withServerNameIndication()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_server_name_indicat4b22e1298adba7fc781c8b5d6c9429d9.yml
  name: HasServerNameIndication.UpdateDefinitionStages.WithServerNameIndication<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasServerNameIndication.UpdateDefinitionStages.WithServerNameIndication<ReturnT>
  type: Interface
  summary: <p>The stage of a definition allowing to require server name indication (SNI). </p>
  syntax:
    content: public interface WithServerNameIndication<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_listener.61d9fc653944e92ded94e93b50deff38
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_listener.61d9fc653944e92ded94e93b50deff38.yml
  name: ApplicationGatewayListener.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayListener.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway HTTP listener definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdate,ApplicationGatewayListener.UpdateDefinitionStages.WithServerNameIndication<ParentT>,ApplicationGatewayListener.UpdateDefinitionStages.WithHostName<ParentT>,ApplicationGatewayListener.UpdateDefinitionStages.WithProtocol<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching this definition </p>
