items:
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific473431b3222c3653b1812199ef6b6b87
  id: _application_gateway_ssl_certific473431b3222c3653b1812199ef6b6b87
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certific473431b3222c3653b1812199ef6b6b87.yml
  langs:
  - java
  name: ApplicationGatewaySslCertificate.UpdateDefinitionStages
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.UpdateDefinitionStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 110
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of application gateway SSL certificate definition stages applicable as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinitionStages
references: []
