items:
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  id: _virtual_machine_scale_set_i_p_configuration_inner
  parent: com.microsoft.azure.management.compute.implementation
  children:
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.applicationGatewayBackendAddressPools()
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.loadBalancerBackendAddressPools()
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.loadBalancerInboundNatPools()
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.name()
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.subnet()
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withApplicationGatewayBackendAddressPools(List< SubResource >)
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withLoadBalancerBackendAddressPools(List< SubResource >)
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withLoadBalancerInboundNatPools(List< SubResource >)
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withName(String)
  - com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withSubnet(ApiEntityReference)
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: VirtualMachineScaleSetIPConfigurationInner
  fullName: com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 20
  package: com.microsoft.azure.management.compute.implementation
  summary: <p>Describes a virtual machine scale set network profile's IP configuration. </p>
  syntax: &o1
    content: public class VirtualMachineScaleSetIPConfigurationInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.applicationGatewayBackendAddressPools()
  id: applicationGatewayBackendAddressPools()
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: applicationGatewayBackendAddressPools()
  fullName: List<SubResource> com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.applicationGatewayBackendAddressPools()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 96
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Get the applicationGatewayBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public List< SubResource > applicationGatewayBackendAddressPools()
    return:
      type: 7be49e81
      description: <p>the applicationGatewayBackendAddressPools value </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.loadBalancerBackendAddressPools()
  id: loadBalancerBackendAddressPools()
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: loadBalancerBackendAddressPools()
  fullName: List<SubResource> com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.loadBalancerBackendAddressPools()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 116
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Get the loadBalancerBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public List< SubResource > loadBalancerBackendAddressPools()
    return:
      type: 7be49e81
      description: <p>the loadBalancerBackendAddressPools value </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.loadBalancerInboundNatPools()
  id: loadBalancerInboundNatPools()
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: loadBalancerInboundNatPools()
  fullName: List<SubResource> com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.loadBalancerInboundNatPools()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 136
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Get the loadBalancerInboundNatPools value.</p>

    <p></p>
  syntax:
    content: public List< SubResource > loadBalancerInboundNatPools()
    return:
      type: 7be49e81
      description: <p>the loadBalancerInboundNatPools value </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.name()
  id: name()
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 56
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.subnet()
  id: subnet()
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: subnet()
  fullName: ApiEntityReference com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.subnet()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 76
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Get the subnet value.</p>

    <p></p>
  syntax:
    content: public ApiEntityReference subnet()
    return:
      type: com.microsoft.azure.management.compute._api_entity_reference
      description: <p>the subnet value </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withApplicationGatewayBackendAddressPools(List< SubResource >)
  id: withApplicationGatewayBackendAddressPools(List< SubResource >)
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: withApplicationGatewayBackendAddressPools(List< SubResource > applicationGatewayBackendAddressPools)
  fullName: VirtualMachineScaleSetIPConfigurationInner com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.withApplicationGatewayBackendAddressPools(List< SubResource > applicationGatewayBackendAddressPools)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 106
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Set the applicationGatewayBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfigurationInner withApplicationGatewayBackendAddressPools(List< SubResource > applicationGatewayBackendAddressPools)
    parameters:
    - id: applicationGatewayBackendAddressPools
      type: 7be49e81
      description: <p>the applicationGatewayBackendAddressPools value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withLoadBalancerBackendAddressPools(List< SubResource >)
  id: withLoadBalancerBackendAddressPools(List< SubResource >)
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: withLoadBalancerBackendAddressPools(List< SubResource > loadBalancerBackendAddressPools)
  fullName: VirtualMachineScaleSetIPConfigurationInner com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.withLoadBalancerBackendAddressPools(List< SubResource > loadBalancerBackendAddressPools)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 126
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Set the loadBalancerBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfigurationInner withLoadBalancerBackendAddressPools(List< SubResource > loadBalancerBackendAddressPools)
    parameters:
    - id: loadBalancerBackendAddressPools
      type: 7be49e81
      description: <p>the loadBalancerBackendAddressPools value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withLoadBalancerInboundNatPools(List< SubResource >)
  id: withLoadBalancerInboundNatPools(List< SubResource >)
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: withLoadBalancerInboundNatPools(List< SubResource > loadBalancerInboundNatPools)
  fullName: VirtualMachineScaleSetIPConfigurationInner com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.withLoadBalancerInboundNatPools(List< SubResource > loadBalancerInboundNatPools)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 146
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Set the loadBalancerInboundNatPools value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfigurationInner withLoadBalancerInboundNatPools(List< SubResource > loadBalancerInboundNatPools)
    parameters:
    - id: loadBalancerInboundNatPools
      type: 7be49e81
      description: <p>the loadBalancerInboundNatPools value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: VirtualMachineScaleSetIPConfigurationInner com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 66
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfigurationInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.withSubnet(ApiEntityReference)
  id: withSubnet(ApiEntityReference)
  parent: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  langs:
  - java
  name: withSubnet(ApiEntityReference subnet)
  fullName: VirtualMachineScaleSetIPConfigurationInner com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner.withSubnet(ApiEntityReference subnet)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetIPConfigurationInner.java
    startLine: 86
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Set the subnet value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfigurationInner withSubnet(ApiEntityReference subnet)
    parameters:
    - id: subnet
      type: com.microsoft.azure.management.compute._api_entity_reference
      description: <p>the subnet value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 7be49e81
  spec.java:
  - name: List< SubResource >
    fullName: List< SubResource >
- uid: com.microsoft.azure.management.compute._api_entity_reference
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._api_entity_reference.yml
  name: ApiEntityReference
  fullName: com.microsoft.azure.management.compute.ApiEntityReference
  type: Class
  summary: <p>The API entity reference. </p>
  syntax:
    content: public class ApiEntityReference
- uid: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner
  parent: com.microsoft.azure.management.compute.implementation
  href: com.microsoft.azure.management.compute.implementation._virtual_machine_scale_set_i_p_configuration_inner.yml
  name: VirtualMachineScaleSetIPConfigurationInner
  fullName: com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetIPConfigurationInner
  type: Class
  summary: <p>Describes a virtual machine scale set network profile's IP configuration. </p>
  syntax: *o1
