items:
- uid: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address
  id: _with_address
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withFqdn(String)
  - com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withIpAddress(String)
  - com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withoutAddress(ApplicationGatewayBackendAddress)
  - com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withoutFqdn(String)
  - com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withoutIpAddress(String)
  href: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.yml
  langs:
  - java
  name: ApplicationGatewayBackend.UpdateStages.WithAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateStages.WithAddress
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 89
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway backed definition allowing to add an address to the backend. </p>
  syntax:
    content: public interface WithAddress
- uid: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withFqdn(String)
  id: withFqdn(String)
  parent: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address
  href: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.yml
  langs:
  - java
  name: withFqdn(String fqdn)
  fullName: Update com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateStages.WithAddress.withFqdn(String fqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 102
  package: com.microsoft.azure.management.network
  summary: <p>Adds the specified existing fully qualified domain name (FQDN) to the backend. </p>
  syntax:
    content: public Update withFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>a fully qualified domain name (FQDN) </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withIpAddress(String)
  id: withIpAddress(String)
  parent: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address
  href: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.yml
  langs:
  - java
  name: withIpAddress(String ipAddress)
  fullName: Update com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateStages.WithAddress.withIpAddress(String ipAddress)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 95
  package: com.microsoft.azure.management.network
  summary: <p>Adds the specified existing IP address to the backend. </p>
  syntax:
    content: public Update withIpAddress(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>an IP address </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withoutAddress(ApplicationGatewayBackendAddress)
  id: withoutAddress(ApplicationGatewayBackendAddress)
  parent: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address
  href: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.yml
  langs:
  - java
  name: withoutAddress(ApplicationGatewayBackendAddress address)
  fullName: Update com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateStages.WithAddress.withoutAddress(ApplicationGatewayBackendAddress address)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 116
  package: com.microsoft.azure.management.network
  summary: <p>Ensure the specified address is not associated with this backend. </p>
  syntax:
    content: public Update withoutAddress(ApplicationGatewayBackendAddress address)
    parameters:
    - id: address
      type: com.microsoft.azure.management.network._application_gateway_backend_address
      description: <p>an existing address currently associated with the backend </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withoutFqdn(String)
  id: withoutFqdn(String)
  parent: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address
  href: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.yml
  langs:
  - java
  name: withoutFqdn(String fqdn)
  fullName: Update com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateStages.WithAddress.withoutFqdn(String fqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 123
  package: com.microsoft.azure.management.network
  summary: <p>Ensures the specified fully qualified domain name (FQDN) is not associated with this backend. </p>
  syntax:
    content: public Update withoutFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>a fully qualified domain name </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.withoutIpAddress(String)
  id: withoutIpAddress(String)
  parent: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address
  href: com.microsoft.azure.management.network._application_gateway_backend._update_stages._with_address.yml
  langs:
  - java
  name: withoutIpAddress(String ipAddress)
  fullName: Update com.microsoft.azure.management.network.ApplicationGatewayBackend.UpdateStages.WithAddress.withoutIpAddress(String ipAddress)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 109
  package: com.microsoft.azure.management.network
  summary: <p>Ensures the specified IP address is not associated with this backend. </p>
  syntax:
    content: public Update withoutIpAddress(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>an IP address </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend._update
      description: <p>the next stage of the update </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._application_gateway_backend._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend._update.yml
  name: ApplicationGatewayBackend.Update
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackend.Update
  type: Interface
  summary: <p>The entirety of an application gateway backend update as part of an application gateway update. </p>
  syntax:
    content: public interface Update extends Settable<ApplicationGateway.Update>,ApplicationGatewayBackend.UpdateStages.WithAddress
- uid: com.microsoft.azure.management.network._application_gateway_backend_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  name: ApplicationGatewayBackendAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
  type: Class
  summary: <p>Backend Address of application gateway. </p>
  syntax:
    content: public class ApplicationGatewayBackendAddress
