items:
- uid: system.fabric.query._provisioned_config_version
  id: _provisioned_config_version
  parent: system.fabric.query
  children:
  - system.fabric.query._provisioned_config_version.getConfigVersion()
  - system.fabric.query._provisioned_config_version.toString()
  href: system.fabric.query._provisioned_config_version.yml
  langs:
  - java
  name: ProvisionedConfigVersion
  fullName: system.fabric.query.ProvisionedConfigVersion
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/query/ProvisionedConfigVersion.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ProvisionedConfigVersion.java
    startLine: 7
  package: system.fabric.query
  syntax:
    content: public class ProvisionedConfigVersion
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric.query._provisioned_config_version.configVersion()
- uid: system.fabric.query._provisioned_config_version.getConfigVersion()
  id: getConfigVersion()
  parent: system.fabric.query._provisioned_config_version
  href: system.fabric.query._provisioned_config_version.yml
  langs:
  - java
  name: getConfigVersion()
  fullName: String system.fabric.query.ProvisionedConfigVersion.getConfigVersion()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ProvisionedConfigVersion.java
    startLine: 17
  package: system.fabric.query
  syntax:
    content: public String getConfigVersion()
    return:
      type: "26831127"
- uid: system.fabric.query._provisioned_config_version.toString()
  id: toString()
  parent: system.fabric.query._provisioned_config_version
  href: system.fabric.query._provisioned_config_version.yml
  langs:
  - java
  name: toString()
  fullName: String system.fabric.query.ProvisionedConfigVersion.toString()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ProvisionedConfigVersion.java
    startLine: 22
  package: system.fabric.query
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric.query._provisioned_config_version.configVersion()
