items:
- uid: system.fabric._application_parameter
  id: _application_parameter
  parent: system.fabric
  children:
  - system.fabric._application_parameter.ApplicationParameter()
  - system.fabric._application_parameter.getName()
  - system.fabric._application_parameter.getValue()
  - system.fabric._application_parameter.setName(String)
  - system.fabric._application_parameter.setValue(String)
  href: system.fabric._application_parameter.yml
  langs:
  - java
  name: ApplicationParameter
  fullName: system.fabric.ApplicationParameter
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationParameter.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationParameter.java
    startLine: 4
  package: system.fabric
  summary: <p>Provides an application parameter override to be applied when creating or upgrading an application. </p>
  syntax: &o1
    content: public class ApplicationParameter
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._application_parameter.ApplicationParameter(String,String)
  - system.fabric._application_parameter.fromNative(long)
  - system.fabric._application_parameter.toNative(PinCollection)
- uid: system.fabric._application_parameter.ApplicationParameter()
  id: ApplicationParameter()
  parent: system.fabric._application_parameter
  href: system.fabric._application_parameter.yml
  langs:
  - java
  name: ApplicationParameter()
  fullName: system.fabric.ApplicationParameter.ApplicationParameter()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationParameter.java
    startLine: 12
  package: system.fabric
  summary: <p>Initializes a new instance of the <ref refid="" kindref="compound">system.fabric.ApplicationParameter</ref> class. </p>
  syntax:
    content: public ApplicationParameter()
- uid: system.fabric._application_parameter.getName()
  id: getName()
  parent: system.fabric._application_parameter
  href: system.fabric._application_parameter.yml
  langs:
  - java
  name: getName()
  fullName: String system.fabric.ApplicationParameter.getName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationParameter.java
    startLine: 20
  package: system.fabric
  summary: <p>Gets the name of the application parameter to override. </p>
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>The name of the application parameter to override. </p>
- uid: system.fabric._application_parameter.getValue()
  id: getValue()
  parent: system.fabric._application_parameter
  href: system.fabric._application_parameter.yml
  langs:
  - java
  name: getValue()
  fullName: String system.fabric.ApplicationParameter.getValue()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationParameter.java
    startLine: 32
  package: system.fabric
  summary: <p>Gets the value of the application parameter to override. </p>
  syntax:
    content: public String getValue()
    return:
      type: "26831127"
      description: <p>The value of the application parameter to override. </p>
- uid: system.fabric._application_parameter.setName(String)
  id: setName(String)
  parent: system.fabric._application_parameter
  href: system.fabric._application_parameter.yml
  langs:
  - java
  name: setName(String name)
  fullName: void system.fabric.ApplicationParameter.setName(String name)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationParameter.java
    startLine: 26
  package: system.fabric
  summary: <p>Sets the name of the application parameter to override. </p>
  syntax:
    content: public void setName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>The name of the application parameter to override. </p>
- uid: system.fabric._application_parameter.setValue(String)
  id: setValue(String)
  parent: system.fabric._application_parameter
  href: system.fabric._application_parameter.yml
  langs:
  - java
  name: setValue(String value)
  fullName: void system.fabric.ApplicationParameter.setValue(String value)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationParameter.java
    startLine: 38
  package: system.fabric
  summary: <p>Sets the value of the application parameter to override. </p>
  syntax:
    content: public void setValue(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>The value of the application parameter to override. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric._application_parameter.ApplicationParameter(String,String)
- uid: system.fabric._application_parameter.fromNative(long)
- uid: system.fabric._application_parameter.toNative(PinCollection)
- uid: system.fabric._application_parameter
  parent: system.fabric
  href: system.fabric._application_parameter.yml
  name: ApplicationParameter
  fullName: system.fabric.ApplicationParameter
  type: Class
  summary: <p>Provides an application parameter override to be applied when creating or upgrading an application. </p>
  syntax: *o1
- uid: system.fabric._pin_collection
  parent: system.fabric
  href: system.fabric._pin_collection.yml
  name: PinCollection
  fullName: system.fabric.PinCollection
  type: Class
  syntax:
    content: public class PinCollection
