items:
- uid: system.fabric.interop._interop_helpers._application_upgrade_progress_helper
  id: _application_upgrade_progress_helper
  parent: system.fabric.interop
  children:
  - system.fabric.interop._interop_helpers._application_upgrade_progress_helper.createFromNative(long)
  - system.fabric.interop._interop_helpers._application_upgrade_progress_helper.getChangedUpgradeDomainsFromNative(long,long)
  href: system.fabric.interop._interop_helpers._application_upgrade_progress_helper.yml
  langs:
  - java
  name: InteropHelpers.ApplicationUpgradeProgressHelper
  fullName: system.fabric.interop.InteropHelpers.ApplicationUpgradeProgressHelper
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/interop/InteropHelpers.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/interop/InteropHelpers.java
    startLine: 46
  package: system.fabric.interop
  syntax:
    content: public class ApplicationUpgradeProgressHelper
  inheritance:
  - java.lang.Object
- uid: system.fabric.interop._interop_helpers._application_upgrade_progress_helper.createFromNative(long)
  id: createFromNative(long)
  parent: system.fabric.interop._interop_helpers._application_upgrade_progress_helper
  href: system.fabric.interop._interop_helpers._application_upgrade_progress_helper.yml
  langs:
  - java
  name: createFromNative(long nativeResultPtr)
  fullName: static ApplicationUpgradeProgress system.fabric.interop.InteropHelpers.ApplicationUpgradeProgressHelper.createFromNative(long nativeResultPtr)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/interop/InteropHelpers.java
    startLine: 59
  package: system.fabric.interop
  syntax:
    content: public static ApplicationUpgradeProgress createFromNative(long nativeResultPtr)
    parameters:
    - id: nativeResultPtr
      type: 0364520f
    return:
      type: system.fabric._application_upgrade_progress
- uid: system.fabric.interop._interop_helpers._application_upgrade_progress_helper.getChangedUpgradeDomainsFromNative(long,long)
  id: getChangedUpgradeDomainsFromNative(long,long)
  parent: system.fabric.interop._interop_helpers._application_upgrade_progress_helper
  href: system.fabric.interop._interop_helpers._application_upgrade_progress_helper.yml
  langs:
  - java
  name: getChangedUpgradeDomainsFromNative(long previousProgress, long upgradeProgress)
  fullName: static List<UpgradeDomainStatus> system.fabric.interop.InteropHelpers.ApplicationUpgradeProgressHelper.getChangedUpgradeDomainsFromNative(long previousProgress, long upgradeProgress)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/interop/InteropHelpers.java
    startLine: 54
  package: system.fabric.interop
  syntax:
    content: public static List<UpgradeDomainStatus> getChangedUpgradeDomainsFromNative(long previousProgress, long upgradeProgress)
    parameters:
    - id: previousProgress
      type: 0364520f
    - id: upgradeProgress
      type: 0364520f
    return:
      type: 5618da2dsystem.fabric._upgrade_domain_statusa08ddfce
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 5618da2dsystem.fabric._upgrade_domain_statusa08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: system.fabric._upgrade_domain_status
    name: UpgradeDomainStatus
    fullName: system.fabric.UpgradeDomainStatus
    href: system.fabric._upgrade_domain_status.yml
  - name: '>'
    fullName: '>'
- uid: system.fabric._upgrade_domain_status
  parent: system.fabric
  href: system.fabric._upgrade_domain_status.yml
  name: UpgradeDomainStatus
  fullName: system.fabric.UpgradeDomainStatus
  type: Class
  summary: <p>Represents the status of an upgrade domain. </p>
  syntax:
    content: public class UpgradeDomainStatus
- uid: system.fabric._application_upgrade_progress
  parent: system.fabric
  href: system.fabric._application_upgrade_progress.yml
  name: ApplicationUpgradeProgress
  fullName: system.fabric.ApplicationUpgradeProgress
  type: Class
  summary: <p>Represents the upgrade status of the application instance. </p>
  syntax:
    content: public class ApplicationUpgradeProgress
