items:
- uid: system.fabric._application_upgrade_state
  id: _application_upgrade_state
  parent: system.fabric
  children:
  - system.fabric._application_upgrade_state.Failed()
  - system.fabric._application_upgrade_state.getValue()
  - system.fabric._application_upgrade_state.Invalid()
  - system.fabric._application_upgrade_state.RollingBackCompleted()
  - system.fabric._application_upgrade_state.RollingBackInProgress()
  - system.fabric._application_upgrade_state.RollingForwardCompleted()
  - system.fabric._application_upgrade_state.RollingForwardInProgress()
  - system.fabric._application_upgrade_state.RollingForwardPending()
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: ApplicationUpgradeState
  fullName: system.fabric.ApplicationUpgradeState
  type: Enum
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 2
  package: system.fabric
  syntax:
    content: public enum ApplicationUpgradeState
  inheritance:
  - java.lang.Object
  - java.lang.Enum<ApplicationUpgradeState>
- uid: system.fabric._application_upgrade_state.Failed()
  id: Failed()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: Failed
  fullName: system.fabric.ApplicationUpgradeState.Failed
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 16
  package: system.fabric
  summary: <p>Indicates that the upgrade has failed. </p>
  syntax:
    content: public Failed=(0x0006)
- uid: system.fabric._application_upgrade_state.getValue()
  id: getValue()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: getValue()
  fullName: int system.fabric.ApplicationUpgradeState.getValue()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 24
  package: system.fabric
  syntax:
    content: public int getValue()
    return:
      type: f75371fa
- uid: system.fabric._application_upgrade_state.Invalid()
  id: Invalid()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: Invalid
  fullName: system.fabric.ApplicationUpgradeState.Invalid
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 4
  package: system.fabric
  summary: <p>Indicates that the type is not valid. All Service Fabric enumerations have an invalid type. </p>
  syntax:
    content: public Invalid=(0x0000)
- uid: system.fabric._application_upgrade_state.RollingBackCompleted()
  id: RollingBackCompleted()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: RollingBackCompleted
  fullName: system.fabric.ApplicationUpgradeState.RollingBackCompleted
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 8
  package: system.fabric
  summary: <p>Indicates that the roll back of the upgrade is completed. The completed rollback indicates that upgrade to the target version has failed. </p>
  syntax:
    content: public RollingBackCompleted=(0x0002)
- uid: system.fabric._application_upgrade_state.RollingBackInProgress()
  id: RollingBackInProgress()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: RollingBackInProgress
  fullName: system.fabric.ApplicationUpgradeState.RollingBackInProgress
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 6
  package: system.fabric
  summary: <p>Indicates that the upgrade is in the process of rolling back. This indicates that upgrade to the target version has failed. Note that this state can also be observed temporarily if the upgrade is interrupted to start a new upgrade. </p>
  syntax:
    content: public RollingBackInProgress=(0x0001)
- uid: system.fabric._application_upgrade_state.RollingForwardCompleted()
  id: RollingForwardCompleted()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: RollingForwardCompleted
  fullName: system.fabric.ApplicationUpgradeState.RollingForwardCompleted
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 14
  package: system.fabric
  summary: <p>Indicates that the upgrade to the target application type version is completed. </p>
  syntax:
    content: public RollingForwardCompleted=(0x0005)
- uid: system.fabric._application_upgrade_state.RollingForwardInProgress()
  id: RollingForwardInProgress()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: RollingForwardInProgress
  fullName: system.fabric.ApplicationUpgradeState.RollingForwardInProgress
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 12
  package: system.fabric
  summary: <p>Indicates that the upgrade to the target application type version is in progress. </p>
  syntax:
    content: public RollingForwardInProgress=(0x0004)
- uid: system.fabric._application_upgrade_state.RollingForwardPending()
  id: RollingForwardPending()
  parent: system.fabric._application_upgrade_state
  href: system.fabric._application_upgrade_state.yml
  langs:
  - java
  name: RollingForwardPending
  fullName: system.fabric.ApplicationUpgradeState.RollingForwardPending
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationUpgradeState.java
    startLine: 10
  package: system.fabric
  summary: <p>Indicates that the upgrade to the target application type version is pending user input. </p>
  syntax:
    content: public RollingForwardPending=(0x0003)
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
