items:
- uid: system.fabric.health._application_health_evaluation
  id: _application_health_evaluation
  parent: system.fabric.health
  children:
  - system.fabric.health._application_health_evaluation.getApplicationName()
  - system.fabric.health._application_health_evaluation.getUnhealthyEvaluations()
  href: system.fabric.health._application_health_evaluation.yml
  langs:
  - java
  name: ApplicationHealthEvaluation
  fullName: system.fabric.health.ApplicationHealthEvaluation
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/health/ApplicationHealthEvaluation.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/health/ApplicationHealthEvaluation.java
    startLine: 8
  package: system.fabric.health
  summary: >-
    <p>Represents health evaluation for an application, containing information about the data and the algorithm used by health store to evaluate health. </p>

    <p>

      <bold>Remarks:</bold> The evaluation is returned only when the aggregated health state is either <ref refid="" kindref="compound">system.fabric.health.HealthState#Error</ref> or <ref refid="" kindref="compound">system.fabric.health.HealthState#Warning</ref>.</p>
  syntax:
    content: public class ApplicationHealthEvaluation extends HealthEvaluation
  inheritance:
  - java.lang.Object
  - system.fabric.health._health_evaluation
  inheritedMembers:
  - system.fabric.health._application_health_evaluation.ApplicationHealthEvaluation(String,int,HealthEvaluation[],String)
  - system.fabric.health._health_evaluation.fromNative(long)
  - system.fabric.health._health_evaluation.getAggregatedHealthState()
  - system.fabric.health._health_evaluation.getDescription()
  - system.fabric.health._health_evaluation.getKind()
  - system.fabric.health._health_evaluation.HealthEvaluation(HealthEvaluationKind,String,HealthState)
  - system.fabric.health._health_evaluation.toString()
- uid: system.fabric.health._application_health_evaluation.getApplicationName()
  id: getApplicationName()
  parent: system.fabric.health._application_health_evaluation
  href: system.fabric.health._application_health_evaluation.yml
  langs:
  - java
  name: getApplicationName()
  fullName: URI system.fabric.health.ApplicationHealthEvaluation.getApplicationName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/health/ApplicationHealthEvaluation.java
    startLine: 34
  package: system.fabric.health
  summary: <p>Gets the application name. </p>
  syntax:
    content: public URI getApplicationName()
    return:
      type: "62304784"
      description: <p>The <ref refid="" kindref="compound">java.net.URI</ref> representing the application name. </p>
- uid: system.fabric.health._application_health_evaluation.getUnhealthyEvaluations()
  id: getUnhealthyEvaluations()
  parent: system.fabric.health._application_health_evaluation
  href: system.fabric.health._application_health_evaluation.yml
  langs:
  - java
  name: getUnhealthyEvaluations()
  fullName: List<HealthEvaluation> system.fabric.health.ApplicationHealthEvaluation.getUnhealthyEvaluations()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/health/ApplicationHealthEvaluation.java
    startLine: 28
  package: system.fabric.health
  summary: <p>Gets the unhealthy evaluations that led to the current aggregated health state of the application. <bold>Remarks:</bold>The types of the unhealthy evaluations can be <xref href="system.fabric.health._deployed_applications_health_evaluation" data-throw-if-not-resolved="false"></xref>, <xref href="system.fabric.health._services_health_evaluation" data-throw-if-not-resolved="false"></xref> or <xref href="system.fabric.health._event_health_evaluation" data-throw-if-not-resolved="false"></xref>.</p>
  syntax:
    content: public List<HealthEvaluation> getUnhealthyEvaluations()
    return:
      type: 5618da2dsystem.fabric.health._health_evaluationa08ddfce
      description: <p>The list of <xref href="system.fabric.health._health_evaluation" data-throw-if-not-resolved="false"></xref> representing the unhealthy evaluations that led to current aggregated health state. </p>
references:
- uid: 5618da2dsystem.fabric.health._health_evaluationa08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: system.fabric.health._health_evaluation
    name: HealthEvaluation
    fullName: system.fabric.health.HealthEvaluation
    href: system.fabric.health._health_evaluation.yml
  - name: '>'
    fullName: '>'
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: system.fabric.health._application_health_evaluation.ApplicationHealthEvaluation(String,int,HealthEvaluation[],String)
- uid: system.fabric.health._health_evaluation.fromNative(long)
  parent: system.fabric.health._health_evaluation
  href: system.fabric.health._health_evaluation.yml
  name: fromNative(long unhealthyEvaluations)
  fullName: static List<HealthEvaluation> system.fabric.health.HealthEvaluation.fromNative(long unhealthyEvaluations)
  type: Method
  syntax:
    content: public static List<HealthEvaluation> fromNative(long unhealthyEvaluations)
    parameters:
    - id: unhealthyEvaluations
      type: 0364520f
    return:
      type: 5618da2dsystem.fabric.health._health_evaluationa08ddfce
- uid: system.fabric.health._health_evaluation.getAggregatedHealthState()
  parent: system.fabric.health._health_evaluation
  href: system.fabric.health._health_evaluation.yml
  name: getAggregatedHealthState()
  fullName: HealthState system.fabric.health.HealthEvaluation.getAggregatedHealthState()
  type: Method
  summary: <p>The aggregated health state of the evaluated entity. </p>
  syntax:
    content: public HealthState getAggregatedHealthState()
    return:
      type: system.fabric.health._health_state
      description: <p>A <xref href="system.fabric.health._health_state" data-throw-if-not-resolved="false"></xref> representing the aggregated health state. </p>
- uid: system.fabric.health._health_evaluation.getDescription()
  parent: system.fabric.health._health_evaluation
  href: system.fabric.health._health_evaluation.yml
  name: getDescription()
  fullName: String system.fabric.health.HealthEvaluation.getDescription()
  type: Method
  summary: <p>Gets the description of the health evaluation, which represents a summary of the evaluation process. </p>
  syntax:
    content: public String getDescription()
    return:
      type: "26831127"
      description: <p>A <ref refid="" kindref="compound">java.lang.String</ref> representing the description of the health evaluation. </p>
- uid: system.fabric.health._health_evaluation.getKind()
  parent: system.fabric.health._health_evaluation
  href: system.fabric.health._health_evaluation.yml
  name: getKind()
  fullName: HealthEvaluationKind system.fabric.health.HealthEvaluation.getKind()
  type: Method
  summary: <p>Gets the kind of the health evaluation. </p>
  syntax:
    content: public HealthEvaluationKind getKind()
    return:
      type: system.fabric.health._health_evaluation_kind
      description: <p>A <xref href="system.fabric.health._health_evaluation_kind" data-throw-if-not-resolved="false"></xref> of the health evaluation. </p>
- uid: system.fabric.health._health_evaluation.HealthEvaluation(HealthEvaluationKind,String,HealthState)
  parent: system.fabric.health._health_evaluation
  href: system.fabric.health._health_evaluation.yml
  name: HealthEvaluation(HealthEvaluationKind kind, String description, HealthState aggregatedHealthState)
  fullName: system.fabric.health.HealthEvaluation.HealthEvaluation(HealthEvaluationKind kind, String description, HealthState aggregatedHealthState)
  type: Constructor
  syntax:
    content: public HealthEvaluation(HealthEvaluationKind kind, String description, HealthState aggregatedHealthState)
    parameters:
    - id: kind
      type: system.fabric.health._health_evaluation_kind
    - id: description
      type: "26831127"
    - id: aggregatedHealthState
      type: system.fabric.health._health_state
- uid: system.fabric.health._health_evaluation.toString()
  parent: system.fabric.health._health_evaluation
  href: system.fabric.health._health_evaluation.yml
  name: toString()
  fullName: String system.fabric.health.HealthEvaluation.toString()
  type: Method
  syntax:
    content: public String toString()
    return:
      type: "26831127"
- uid: system.fabric.health._health_evaluation
  parent: system.fabric.health
  href: system.fabric.health._health_evaluation.yml
  name: HealthEvaluation
  fullName: system.fabric.health.HealthEvaluation
  type: Class
  summary: <p>Represents a health evaluation which describes the data and the algorithm used by health store to evaluate the health of an entity. </p>
  syntax:
    content: public class HealthEvaluation
- uid: system.fabric.health._deployed_applications_health_evaluation
  parent: system.fabric.health
  href: system.fabric.health._deployed_applications_health_evaluation.yml
  name: DeployedApplicationsHealthEvaluation
  fullName: system.fabric.health.DeployedApplicationsHealthEvaluation
  type: Class
  summary: <p>Represents health evaluation for deployed applications, containing health evaluations for each unhealthy deployed application that impacted current aggregated health state. Can be returned when evaluating application health and the aggregated health state is either <ref refid="" kindref="compound">system.fabric.health.HealthState#Error</ref> or <ref refid="" kindref="compound">system.fabric.health.HealthState#Warning</ref></p>
  syntax:
    content: public class DeployedApplicationsHealthEvaluation
- uid: system.fabric.health._services_health_evaluation
  parent: system.fabric.health
  href: system.fabric.health._services_health_evaluation.yml
  name: ServicesHealthEvaluation
  fullName: system.fabric.health.ServicesHealthEvaluation
  type: Class
  summary: <p>Represents health evaluation for services of a certain service type belonging to an application, containing health evaluations for each unhealthy service that impacted current aggregated health state. Can be returned when evaluating application health and the aggregated health state is either <ref refid="" kindref="compound">system.fabric.health.HealthState#Error</ref> or <ref refid="" kindref="compound">system.fabric.health.HealthState#Warning</ref>. </p>
  syntax:
    content: public class ServicesHealthEvaluation
- uid: system.fabric.health._event_health_evaluation
  parent: system.fabric.health
  href: system.fabric.health._event_health_evaluation.yml
  name: EventHealthEvaluation
  fullName: system.fabric.health.EventHealthEvaluation
  type: Class
  summary: <p>Represents health evaluation of a <xref href="system.fabric.health._health_event" data-throw-if-not-resolved="false"></xref>. Can be returned when evaluating health of an entity returns <ref refid="" kindref="compound">system.fabric.health.HealthState#Error</ref> or <ref refid="" kindref="compound">system.fabric.health.HealthState#Warning</ref>. </p>
  syntax:
    content: public class EventHealthEvaluation
