items:
- uid: system.fabric._configuration_package_description
  id: _configuration_package_description
  parent: system.fabric
  href: system.fabric._configuration_package_description.yml
  langs:
  - java
  name: ConfigurationPackageDescription
  fullName: system.fabric.ConfigurationPackageDescription
  type: Class
  source:
    remote:
      path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackageDescription.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackageDescription.java
    startLine: 3
  package: system.fabric
  summary: <p>Describes a configuration package. </p>
  syntax:
    content: public class ConfigurationPackageDescription extends PackageDescription
  inheritance:
  - java.lang.Object
  - system.fabric._package_description
  inheritedMembers:
  - system.fabric._configuration_package_description.ConfigurationPackageDescription(String,String,String,String)
  - system.fabric._package_description.getName()
  - system.fabric._package_description.getServiceManifestName()
  - system.fabric._package_description.getServiceManifestVersion()
  - system.fabric._package_description.getVersion()
  - system.fabric._package_description.PackageDescription(String,String,String,String)
references:
- uid: system.fabric._configuration_package_description.ConfigurationPackageDescription(String,String,String,String)
- uid: system.fabric._package_description.getName()
  parent: system.fabric._package_description
  href: system.fabric._package_description.yml
  name: getName()
  fullName: String system.fabric.PackageDescription.getName()
  type: Method
  summary: <p>Specifies the name of the package. </p>
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric._package_description.getServiceManifestName()
  parent: system.fabric._package_description
  href: system.fabric._package_description.yml
  name: getServiceManifestName()
  fullName: String system.fabric.PackageDescription.getServiceManifestName()
  type: Method
  summary: <p>Specifies the name of the service manifest. </p>
  syntax:
    content: public String getServiceManifestName()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric._package_description.getServiceManifestVersion()
  parent: system.fabric._package_description
  href: system.fabric._package_description.yml
  name: getServiceManifestVersion()
  fullName: String system.fabric.PackageDescription.getServiceManifestVersion()
  type: Method
  summary: <p>Specifies the path to the package. </p>
  syntax:
    content: public String getServiceManifestVersion()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric._package_description.getVersion()
  parent: system.fabric._package_description
  href: system.fabric._package_description.yml
  name: getVersion()
  fullName: String system.fabric.PackageDescription.getVersion()
  type: Method
  summary: <p>Specifies the version of the package. </p>
  syntax:
    content: public String getVersion()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric._package_description.PackageDescription(String,String,String,String)
  parent: system.fabric._package_description
  href: system.fabric._package_description.yml
  name: PackageDescription(String name, String version, String serviceManifestName, String serviceManifestVersion)
  fullName: system.fabric.PackageDescription.PackageDescription(String name, String version, String serviceManifestName, String serviceManifestVersion)
  type: Constructor
  syntax:
    content: public PackageDescription(String name, String version, String serviceManifestName, String serviceManifestVersion)
    parameters:
    - id: name
      type: "26831127"
    - id: version
      type: "26831127"
    - id: serviceManifestName
      type: "26831127"
    - id: serviceManifestVersion
      type: "26831127"
- uid: system.fabric._package_description
  parent: system.fabric
  href: system.fabric._package_description.yml
  name: PackageDescription
  fullName: system.fabric.PackageDescription
  type: Class
  summary: >-
    <p>Represents a base class for all package descriptions.</p>

    <p></p>
  syntax:
    content: public class PackageDescription
