items:
- uid: system.fabric._configuration_settings
  id: _configuration_settings
  parent: system.fabric
  children:
  - system.fabric._configuration_settings.getSections()
  href: system.fabric._configuration_settings.yml
  langs:
  - java
  name: ConfigurationSettings
  fullName: system.fabric.ConfigurationSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationSettings.java
    startLine: 4
  package: system.fabric
  syntax:
    content: public class ConfigurationSettings
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._configuration_settings.ConfigurationSettings(ConfigurationSection [])
- uid: system.fabric._configuration_settings.getSections()
  id: getSections()
  parent: system.fabric._configuration_settings
  href: system.fabric._configuration_settings.yml
  langs:
  - java
  name: getSections()
  fullName: HashMap<String, ConfigurationSection> system.fabric.ConfigurationSettings.getSections()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationSettings.java
    startLine: 19
  package: system.fabric
  summary: <p>Gets the name/value pair collection of the sections. </p>
  syntax:
    content: public HashMap<String, ConfigurationSection> getSections()
    return:
      type: 292b5718system.fabric._configuration_sectiona08ddfce
      description: <p>the name/value pair collection of the sections. </p>
references:
- uid: 292b5718system.fabric._configuration_sectiona08ddfce
  spec.java:
  - name: 'HashMap<String, '
    fullName: 'HashMap<String, '
  - uid: system.fabric._configuration_section
    name: ConfigurationSection
    fullName: system.fabric.ConfigurationSection
    href: system.fabric._configuration_section.yml
  - name: '>'
    fullName: '>'
- uid: system.fabric._configuration_settings.ConfigurationSettings(ConfigurationSection [])
- uid: system.fabric._configuration_section
  parent: system.fabric
  href: system.fabric._configuration_section.yml
  name: ConfigurationSection
  fullName: system.fabric.ConfigurationSection
  type: Class
  summary: <p>Defines any configuration that can be written and read from a configuration store </p>
  syntax:
    content: public class ConfigurationSection
