items:
- uid: system.fabric._deployed_application_health_states_filter
  id: _deployed_application_health_states_filter
  parent: system.fabric
  children:
  - system.fabric._deployed_application_health_states_filter.getHealthStateFilter()
  - system.fabric._deployed_application_health_states_filter.setHealthStateFilter(HealthStateFilter)
  href: system.fabric._deployed_application_health_states_filter.yml
  langs:
  - java
  name: DeployedApplicationHealthStatesFilter
  fullName: system.fabric.DeployedApplicationHealthStatesFilter
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStatesFilter.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStatesFilter.java
    startLine: 5
  package: system.fabric
  syntax:
    content: public class DeployedApplicationHealthStatesFilter
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._deployed_application_health_states_filter.toNative(PinCollection)
  - system.fabric._deployed_application_health_states_filter.ToNative(long)
- uid: system.fabric._deployed_application_health_states_filter.getHealthStateFilter()
  id: getHealthStateFilter()
  parent: system.fabric._deployed_application_health_states_filter
  href: system.fabric._deployed_application_health_states_filter.yml
  langs:
  - java
  name: getHealthStateFilter()
  fullName: HealthStateFilter system.fabric.DeployedApplicationHealthStatesFilter.getHealthStateFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStatesFilter.java
    startLine: 22
  package: system.fabric
  summary: <p>Gets the filter for the aggregated health state of the <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection. <bold>Remarks:</bold>The input collection is filtered to return only entries that respect the desired health state. The filter represents a value obtained from members or bitwise combinations of members of HealthStateFilter.</p>
  syntax:
    content: public HealthStateFilter getHealthStateFilter()
    return:
      type: system.fabric.health._health_state_filter
      description: <p>The filter for the aggregated health state of the <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> entries. </p>
- uid: system.fabric._deployed_application_health_states_filter.setHealthStateFilter(HealthStateFilter)
  id: setHealthStateFilter(HealthStateFilter)
  parent: system.fabric._deployed_application_health_states_filter
  href: system.fabric._deployed_application_health_states_filter.yml
  langs:
  - java
  name: setHealthStateFilter(HealthStateFilter healthStateFilter)
  fullName: void system.fabric.DeployedApplicationHealthStatesFilter.setHealthStateFilter(HealthStateFilter healthStateFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStatesFilter.java
    startLine: 31
  package: system.fabric
  summary: <p>Sets the filter for the aggregated health state of the <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection. <bold>Remarks:</bold>The input collection is filtered to return only entries that respect the desired health state. The filter represents a value obtained from members or bitwise combinations of members of HealthStateFilter.</p>
  syntax:
    content: public void setHealthStateFilter(HealthStateFilter healthStateFilter)
    parameters:
    - id: healthStateFilter
      type: system.fabric.health._health_state_filter
      description: <p>state filter </p>
references:
- uid: system.fabric._deployed_application_health_states_filter.toNative(PinCollection)
- uid: system.fabric._deployed_application_health_states_filter.ToNative(long)
- uid: system.fabric.health._health_state_filter
  parent: system.fabric.health
  href: system.fabric.health._health_state_filter.yml
  name: HealthStateFilter
  fullName: system.fabric.health.HealthStateFilter
  type: Enum
  syntax:
    content: public enum HealthStateFilter
- uid: system.fabric._pin_collection
  parent: system.fabric
  href: system.fabric._pin_collection.yml
  name: PinCollection
  fullName: system.fabric.PinCollection
  type: Class
  syntax:
    content: public class PinCollection
- uid: system.fabric.health._deployed_application_health_state
  parent: system.fabric.health
  href: system.fabric.health._deployed_application_health_state.yml
  name: DeployedApplicationHealthState
  fullName: system.fabric.health.DeployedApplicationHealthState
  type: Class
  summary: <p>Represents the health state of a deployed application, which contains the entity identifier and the aggregated health state. </p>
  syntax:
    content: public class DeployedApplicationHealthState extends EntityHealthState
