items:
- uid: system.fabric.description._application_parameter
  id: _application_parameter
  parent: system.fabric.description
  children:
  - system.fabric.description._application_parameter.getName()
  - system.fabric.description._application_parameter.getValue()
  - system.fabric.description._application_parameter.toString()
  href: system.fabric.description._application_parameter.yml
  langs:
  - java
  name: ApplicationParameter
  fullName: system.fabric.description.ApplicationParameter
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/description/ApplicationParameter.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ApplicationParameter.java
    startLine: 8
  package: system.fabric.description
  summary: >-
    <p>This class contains the detail of application-parameter - a name and a corresponding value.</p>

    <p></p>
  syntax:
    content: public class ApplicationParameter
  inheritance:
  - java.lang.Object
- uid: system.fabric.description._application_parameter.getName()
  id: getName()
  parent: system.fabric.description._application_parameter
  href: system.fabric.description._application_parameter.yml
  langs:
  - java
  name: getName()
  fullName: String system.fabric.description.ApplicationParameter.getName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ApplicationParameter.java
    startLine: 25
  package: system.fabric.description
  summary: <p>Gets the name of the application parameter to override. </p>
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>The name of the application parameter to override. </p>
- uid: system.fabric.description._application_parameter.getValue()
  id: getValue()
  parent: system.fabric.description._application_parameter
  href: system.fabric.description._application_parameter.yml
  langs:
  - java
  name: getValue()
  fullName: String system.fabric.description.ApplicationParameter.getValue()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ApplicationParameter.java
    startLine: 31
  package: system.fabric.description
  summary: <p>Gets the value of the application parameter to override. </p>
  syntax:
    content: public String getValue()
    return:
      type: "26831127"
      description: <p>The value of the application parameter to override. </p>
- uid: system.fabric.description._application_parameter.toString()
  id: toString()
  parent: system.fabric.description._application_parameter
  href: system.fabric.description._application_parameter.yml
  langs:
  - java
  name: toString()
  fullName: String system.fabric.description.ApplicationParameter.toString()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ApplicationParameter.java
    startLine: 36
  package: system.fabric.description
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
