### YamlMime:ManagedReference
items:
- uid: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback
  id: GetAccountCallback
  parent: com.microsoft.identity.client
  children:
  - com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onError(MsalException)
  - com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted(IAccount)
  href: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.yml
  langs:
  - java
  name: IMultipleAccountPublicClientApplication.GetAccountCallback
  nameWithType: IMultipleAccountPublicClientApplication.GetAccountCallback
  fullName: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback
  type: Interface
  source:
    remote: &o0
      path: msal/src/main/java/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.java
      branch: master
      repo: https://github.com/AzureAD/microsoft-authentication-library-for-android
    path: msal/src/main/java/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.java
    startLine: 151
  package: com.microsoft.identity.client
  syntax:
    content: public interface GetAccountCallback
- uid: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onError(MsalException)
  id: onError(MsalException)
  parent: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback
  href: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.yml
  langs:
  - java
  name: onError(MsalException exception)
  nameWithType: IMultipleAccountPublicClientApplication.GetAccountCallback.onError(MsalException exception)
  fullName: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onError(MsalException exception)
  overload: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onError*
  type: Method
  source:
    remote: *o0
    path: msal/src/main/java/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.java
    startLine: 164
  package: com.microsoft.identity.client
  summary: "<p>Called once exception thrown.</p>\r\n<p></p>"
  syntax:
    content: public void onError(MsalException exception)
    parameters:
    - id: exception
      type: com.microsoft.identity.client.exception.MsalException
- uid: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted(IAccount)
  id: onTaskCompleted(IAccount)
  parent: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback
  href: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.yml
  langs:
  - java
  name: onTaskCompleted(IAccount result)
  nameWithType: IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted(IAccount result)
  fullName: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted(IAccount result)
  overload: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted*
  type: Method
  source:
    remote: *o0
    path: msal/src/main/java/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.java
    startLine: 157
  package: com.microsoft.identity.client
  summary: "<p>Called once succeed and pass the result object.</p>\r\n<p></p>"
  syntax:
    content: public void onTaskCompleted(IAccount result)
    parameters:
    - id: result
      type: com.microsoft.identity.client.IAccount
      description: <p>the success result. </p>
references:
- uid: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted*
  name: onTaskCompleted
  nameWithType: IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted
  fullName: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onTaskCompleted
  package: com.microsoft.identity.client
- uid: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onError*
  name: onError
  nameWithType: IMultipleAccountPublicClientApplication.GetAccountCallback.onError
  fullName: com.microsoft.identity.client.IMultipleAccountPublicClientApplication.GetAccountCallback.onError
  package: com.microsoft.identity.client
- uid: com.microsoft.identity.client.IAccount
  parent: com.microsoft.identity.client
  href: com.microsoft.identity.client.IAccount.yml
  name: IAccount
  nameWithType: IAccount
  fullName: com.microsoft.identity.client.IAccount
  type: Interface
  syntax:
    content: public interface IAccount
- uid: com.microsoft.identity.client.exception.MsalException
  parent: com.microsoft.identity.client.exception
  href: com.microsoft.identity.client.exception.MsalException.yml
  name: MsalException
  nameWithType: MsalException
  fullName: com.microsoft.identity.client.exception.MsalException
  type: Class
  summary: "<p>\r\n  <xref uid=\"com.microsoft.identity.client.exception.MsalException\" data-throw-if-not-resolved=\"false\">MsalException</xref> thrown or sent back via callback, representing the detailed exception thrown by the sdk. It will contain the error code, error description (could be null) or throwable (could be null). </p>"
  syntax:
    content: public class MsalException
