items:
- uid: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings
  id: _with_os_disk_settings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a2cac41e42041c26fcc8e0d341322b518
  - com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a58f7eb9e33c61fc89235412588dfab48
  - com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a0ce16b0754d7a70d5e229a9c00eb8b9f
  - com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a11741aece6b2f4094e7c347c6cd4f0d5
  - com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a54ee4dc98ceb9b31b2765ce12983d2c4
  href: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings.yml
  langs:
  - java
  name: VirtualMachine.DefinitionStages.WithOsDiskSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOsDiskSettings
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 603
  package: com.microsoft.azure.management.compute
  summary: <p>The stage of the virtual machine definition allowing to specify OS disk configurations. </p>
  syntax:
    content: public interface WithOsDiskSettings
- uid: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a2cac41e42041c26fcc8e0d341322b518
  id: _with_os_disk_settings_1a2cac41e42041c26fcc8e0d341322b518
  parent: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings
  href: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings.yml
  langs:
  - java
  name: withOsDiskCaching(CachingTypes cachingType)
  fullName: WithCreate com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOsDiskSettings.withOsDiskCaching(CachingTypes cachingType)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 610
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies the caching type for the Operating System disk.</p>

    <p></p>
  syntax:
    content: public WithCreate withOsDiskCaching(CachingTypes cachingType)
    parameters:
    - id: cachingType
      type: com.microsoft.azure.management.compute._caching_types
      description: <p>the caching type. </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_create
      description: <p>the stage representing creatable VM definition </p>
- uid: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a58f7eb9e33c61fc89235412588dfab48
  id: _with_os_disk_settings_1a58f7eb9e33c61fc89235412588dfab48
  parent: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings
  href: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings.yml
  langs:
  - java
  name: withOsDiskEncryptionSettings(DiskEncryptionSettings settings)
  fullName: WithCreate com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOsDiskSettings.withOsDiskEncryptionSettings(DiskEncryptionSettings settings)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 627
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies the encryption settings for the OS Disk.</p>

    <p></p>
  syntax:
    content: public WithCreate withOsDiskEncryptionSettings(DiskEncryptionSettings settings)
    parameters:
    - id: settings
      type: com.microsoft.azure.management.compute._disk_encryption_settings
      description: <p>the encryption settings. </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_create
      description: <p>the stage representing creatable VM definition </p>
- uid: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a0ce16b0754d7a70d5e229a9c00eb8b9f
  id: _with_os_disk_settings_1a0ce16b0754d7a70d5e229a9c00eb8b9f
  parent: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings
  href: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings.yml
  langs:
  - java
  name: withOsDiskName(String name)
  fullName: WithCreate com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOsDiskSettings.withOsDiskName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 643
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies the name for the OS Disk.</p>

    <p></p>
  syntax:
    content: public WithCreate withOsDiskName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the OS Disk name. </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_create
      description: <p>the stage representing creatable VM definition </p>
- uid: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a11741aece6b2f4094e7c347c6cd4f0d5
  id: _with_os_disk_settings_1a11741aece6b2f4094e7c347c6cd4f0d5
  parent: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings
  href: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings.yml
  langs:
  - java
  name: withOsDiskSizeInGb(Integer size)
  fullName: WithCreate com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOsDiskSettings.withOsDiskSizeInGb(Integer size)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 635
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies the size of the <xref href="com.microsoft.azure.management.compute._o_s_disk" data-throw-if-not-resolved="false"></xref> in GB.</p>

    <p></p>
  syntax:
    content: public WithCreate withOsDiskSizeInGb(Integer size)
    parameters:
    - id: size
      type: 08effaa0
      description: <p>the VHD size. </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_create
      description: <p>the stage representing creatable VM definition </p>
- uid: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings_1a54ee4dc98ceb9b31b2765ce12983d2c4
  id: _with_os_disk_settings_1a54ee4dc98ceb9b31b2765ce12983d2c4
  parent: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings
  href: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_os_disk_settings.yml
  langs:
  - java
  name: withOsDiskVhdLocation(String containerName, String vhdName)
  fullName: WithCreate com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOsDiskSettings.withOsDiskVhdLocation(String containerName, String vhdName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 619
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies the name of the OS Disk Vhd file and it's parent container.</p>

    <p></p>
  syntax:
    content: public WithCreate withOsDiskVhdLocation(String containerName, String vhdName)
    parameters:
    - id: containerName
      type: "26831127"
      description: <p>the name of the container in the selected storage account. </p>
    - id: vhdName
      type: "26831127"
      description: <p>the name for the OS Disk vhd. </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_create
      description: <p>the stage representing creatable VM definition </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_create
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._virtual_machine._definition_stages._with_create.yml
  name: VirtualMachine.DefinitionStages.WithCreate
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
  type: Interface
  summary: <p>The stage of the definition which contains all the minimum required inputs for the resource to be created (via <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable_1acf3889a24f1bb5e64f8e6a751397f991" data-throw-if-not-resolved="false"></xref>), but also allows for any other optional settings to be specified. </p>
  syntax:
    content: public interface WithCreate extends Creatable< VirtualMachine >,Resource.DefinitionWithTags< WithCreate >,VirtualMachine.DefinitionStages.WithPassword,VirtualMachine.DefinitionStages.WithOsDiskSettings,VirtualMachine.DefinitionStages.WithVMSize,VirtualMachine.DefinitionStages.WithStorageAccount,VirtualMachine.DefinitionStages.WithDataDisk,VirtualMachine.DefinitionStages.WithAvailabilitySet,VirtualMachine.DefinitionStages.WithSecondaryNetworkInterface
- uid: com.microsoft.azure.management.compute._caching_types
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._caching_types.yml
  name: CachingTypes
  fullName: com.microsoft.azure.management.compute.CachingTypes
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.compute._caching_types" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum CachingTypes
- uid: com.microsoft.azure.management.compute._disk_encryption_settings
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  name: DiskEncryptionSettings
  fullName: com.microsoft.azure.management.compute.DiskEncryptionSettings
  type: Class
  summary: <p>Describes a Encryption Settings for a Disk. </p>
  syntax:
    content: public class DiskEncryptionSettings
- uid: com.microsoft.azure.management.compute._o_s_disk
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._o_s_disk.yml
  name: OSDisk
  fullName: com.microsoft.azure.management.compute.OSDisk
  type: Class
  summary: <p>Describes an Operating System disk. </p>
  syntax:
    content: public class OSDisk
