items:
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
  id: _with_template
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_template.withTemplate(Object)
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_template.withTemplate(String)
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_template.withTemplateLink(String,String)
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.yml
  langs:
  - java
  name: Deployment.DefinitionStages.WithTemplate
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithTemplate
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 170
  package: com.microsoft.azure.management.resources
  summary: <p>A deployment definition allowing the template to be specified. </p>
  syntax:
    content: public interface WithTemplate
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.withTemplate(Object)
  id: withTemplate(Object)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.yml
  langs:
  - java
  name: withTemplate(Object template)
  fullName: WithParameters com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithTemplate.withTemplate(Object template)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 177
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the template as a Java object.</p>

    <p></p>
  syntax:
    content: public WithParameters withTemplate(Object template)
    parameters:
    - id: template
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
      description: <p>the next stage of the deployment definition </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.withTemplate(String)
  id: withTemplate(String)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.yml
  langs:
  - java
  name: withTemplate(String templateJson)
  fullName: WithParameters com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithTemplate.withTemplate(String templateJson)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 186
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the template as a JSON string.</p>

    <p></p>
  syntax:
    content: public WithParameters withTemplate(String templateJson)
    parameters:
    - id: templateJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
      description: <p>the next stage of the deployment definition </p>
  exceptions:
  - type: cbf33bbe
    description: <p>exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.withTemplateLink(String,String)
  id: withTemplateLink(String,String)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.yml
  langs:
  - java
  name: withTemplateLink(String uri, String contentVersion)
  fullName: WithParameters com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithTemplate.withTemplateLink(String uri, String contentVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 195
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the template as a URL.</p>

    <p></p>
  syntax:
    content: public WithParameters withTemplateLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote template file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the template file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
      description: <p>the next stage of the deployment definition </p>
references:
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources._deployment._definition
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition.yml
  name: Deployment.Definition
  fullName: com.microsoft.azure.management.resources.Deployment.Definition
  type: Interface
  summary: <p>Container interface for all the deployment definitions. </p>
  syntax:
    content: public interface Definition extends Deployment.DefinitionStages.Blank,Deployment.DefinitionStages.WithGroup,Deployment.DefinitionStages.WithTemplate,Deployment.DefinitionStages.WithParameters,Deployment.DefinitionStages.WithMode,Deployment.DefinitionStages.WithCreate
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.yml
  name: Deployment.DefinitionStages.WithParameters
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithParameters
  type: Interface
  summary: <p>A deployment definition allowing the parameters to be specified. </p>
  syntax:
    content: public interface WithParameters
