items:
- uid: com.microsoft.azure.management.website._slot_config_names
  id: _slot_config_names
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._slot_config_names_1ab62aec20f477499d1d4f1bc56e8b0443
  - com.microsoft.azure.management.website._slot_config_names_1a464307e442b6b86507e2f75122ec4ff8
  - com.microsoft.azure.management.website._slot_config_names_1a606a370c26612c8de17e4081bb716d8c
  - com.microsoft.azure.management.website._slot_config_names_1ac189e97d96da3a5439dc7bf91afa464e
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: SlotConfigNames
  fullName: com.microsoft.azure.management.website.SlotConfigNames
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 18
  package: com.microsoft.azure.management.website
  summary: <p>Class containing names for connection strings and application settings to be marked as sticky to the slot and not moved during swap operation This is valid for all deployment slots under the site. </p>
  syntax: &o1
    content: public class SlotConfigNames
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._slot_config_names_1ab62aec20f477499d1d4f1bc56e8b0443
  id: _slot_config_names_1ab62aec20f477499d1d4f1bc56e8b0443
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: appSettingNames()
  fullName: List<String> com.microsoft.azure.management.website.SlotConfigNames.appSettingNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 54
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public List< String > appSettingNames()
    return:
      type: f35af49b
      description: <p>the appSettingNames value </p>
- uid: com.microsoft.azure.management.website._slot_config_names_1a464307e442b6b86507e2f75122ec4ff8
  id: _slot_config_names_1a464307e442b6b86507e2f75122ec4ff8
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: connectionStringNames()
  fullName: List<String> com.microsoft.azure.management.website.SlotConfigNames.connectionStringNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 34
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public List< String > connectionStringNames()
    return:
      type: f35af49b
      description: <p>the connectionStringNames value </p>
- uid: com.microsoft.azure.management.website._slot_config_names_1a606a370c26612c8de17e4081bb716d8c
  id: _slot_config_names_1a606a370c26612c8de17e4081bb716d8c
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: withAppSettingNames(List< String > appSettingNames)
  fullName: SlotConfigNames com.microsoft.azure.management.website.SlotConfigNames.withAppSettingNames(List< String > appSettingNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 64
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNames withAppSettingNames(List< String > appSettingNames)
    parameters:
    - id: appSettingNames
      type: f35af49b
      description: <p>the appSettingNames value to set </p>
    return:
      type: com.microsoft.azure.management.website._slot_config_names
      description: <p>the <xref href="com.microsoft.azure.management.website._slot_config_names" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._slot_config_names_1ac189e97d96da3a5439dc7bf91afa464e
  id: _slot_config_names_1ac189e97d96da3a5439dc7bf91afa464e
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: withConnectionStringNames(List< String > connectionStringNames)
  fullName: SlotConfigNames com.microsoft.azure.management.website.SlotConfigNames.withConnectionStringNames(List< String > connectionStringNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 44
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNames withConnectionStringNames(List< String > connectionStringNames)
    parameters:
    - id: connectionStringNames
      type: f35af49b
      description: <p>the connectionStringNames value to set </p>
    return:
      type: com.microsoft.azure.management.website._slot_config_names
      description: <p>the <xref href="com.microsoft.azure.management.website._slot_config_names" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: com.microsoft.azure.management.website._slot_config_names
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._slot_config_names.yml
  name: SlotConfigNames
  fullName: com.microsoft.azure.management.website.SlotConfigNames
  type: Class
  summary: <p>Class containing names for connection strings and application settings to be marked as sticky to the slot and not moved during swap operation This is valid for all deployment slots under the site. </p>
  syntax: *o1
