items:
- uid: com.microsoft.azure.management.resources._deployments_tests
  id: _deployments_tests
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployments_tests_1a54db759fdd448c06a3ca8ea6146b9da4
  - com.microsoft.azure.management.resources._deployments_tests_1a1252122ef742cc35c79c6d0a15a08410
  - com.microsoft.azure.management.resources._deployments_tests_1a6d1db4a477af6fb94e73797527934811
  - com.microsoft.azure.management.resources._deployments_tests_1a3fb8bace29393cf28139151b4f5d7b4e
  - com.microsoft.azure.management.resources._deployments_tests_1aabd63b19790a6b2e1ec667986ae90179
  href: com.microsoft.azure.management.resources._deployments_tests.yml
  langs:
  - java
  name: DeploymentsTests
  fullName: com.microsoft.azure.management.resources.DeploymentsTests
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
    startLine: 11
  package: com.microsoft.azure.management.resources
  syntax:
    content: public class DeploymentsTests
  inheritance:
  - java.lang.Object
  - com.microsoft.azure.management.resources.ResourceManagerTestBase
  inheritedMembers:
  - com.microsoft.azure.management.resources._resource_manager_test_base_1a6dd4b2af09f8fa1082c3d1735cafb24d
  - com.microsoft.azure.management.resources._resource_manager_test_base_1a0c823f2e723a584a02723e49e13bb940
- uid: com.microsoft.azure.management.resources._deployments_tests_1a54db759fdd448c06a3ca8ea6146b9da4
  id: _deployments_tests_1a54db759fdd448c06a3ca8ea6146b9da4
  parent: com.microsoft.azure.management.resources._deployments_tests
  href: com.microsoft.azure.management.resources._deployments_tests.yml
  langs:
  - java
  name: canCancelVirtualNetworkDeployment()
  fullName: void com.microsoft.azure.management.resources.DeploymentsTests.canCancelVirtualNetworkDeployment()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
    startLine: 79
  package: com.microsoft.azure.management.resources
  syntax:
    content: public void canCancelVirtualNetworkDeployment()
- uid: com.microsoft.azure.management.resources._deployments_tests_1a1252122ef742cc35c79c6d0a15a08410
  id: _deployments_tests_1a1252122ef742cc35c79c6d0a15a08410
  parent: com.microsoft.azure.management.resources._deployments_tests
  href: com.microsoft.azure.management.resources._deployments_tests.yml
  langs:
  - java
  name: canDeployVirtualNetwork()
  fullName: void com.microsoft.azure.management.resources.DeploymentsTests.canDeployVirtualNetwork()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
    startLine: 42
  package: com.microsoft.azure.management.resources
  syntax:
    content: public void canDeployVirtualNetwork()
- uid: com.microsoft.azure.management.resources._deployments_tests_1a6d1db4a477af6fb94e73797527934811
  id: _deployments_tests_1a6d1db4a477af6fb94e73797527934811
  parent: com.microsoft.azure.management.resources._deployments_tests
  href: com.microsoft.azure.management.resources._deployments_tests.yml
  langs:
  - java
  name: canUpdateVirtualNetworkDeployment()
  fullName: void com.microsoft.azure.management.resources.DeploymentsTests.canUpdateVirtualNetworkDeployment()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
    startLine: 98
  package: com.microsoft.azure.management.resources
  syntax:
    content: public void canUpdateVirtualNetworkDeployment()
- uid: com.microsoft.azure.management.resources._deployments_tests_1a3fb8bace29393cf28139151b4f5d7b4e
  id: _deployments_tests_1a3fb8bace29393cf28139151b4f5d7b4e
  parent: com.microsoft.azure.management.resources._deployments_tests
  href: com.microsoft.azure.management.resources._deployments_tests.yml
  langs:
  - java
  name: cleanup()
  fullName: static void com.microsoft.azure.management.resources.DeploymentsTests.cleanup()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
    startLine: 37
  package: com.microsoft.azure.management.resources
  syntax:
    content: public static void cleanup()
- uid: com.microsoft.azure.management.resources._deployments_tests_1aabd63b19790a6b2e1ec667986ae90179
  id: _deployments_tests_1aabd63b19790a6b2e1ec667986ae90179
  parent: com.microsoft.azure.management.resources._deployments_tests
  href: com.microsoft.azure.management.resources._deployments_tests.yml
  langs:
  - java
  name: setup()
  fullName: static void com.microsoft.azure.management.resources.DeploymentsTests.setup()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
    startLine: 27
  package: com.microsoft.azure.management.resources
  syntax:
    content: public static void setup()
references:
- uid: com.microsoft.azure.management.resources._resource_manager_test_base_1a6dd4b2af09f8fa1082c3d1735cafb24d
- uid: com.microsoft.azure.management.resources._resource_manager_test_base_1a0c823f2e723a584a02723e49e13bb940
- uid: com.microsoft.azure.management.resources._resource_groups
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._resource_groups.yml
  name: ResourceGroups
  fullName: com.microsoft.azure.management.resources.ResourceGroups
  type: Interface
  summary: <p>Entry point to resource group management API. </p>
  syntax:
    content: public interface ResourceGroups
- uid: com.microsoft.azure.management.resources._resource_group
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._resource_group.yml
  name: ResourceGroup
  fullName: com.microsoft.azure.management.resources.ResourceGroup
  type: Interface
  summary: <p>An immutable client-side representation of an <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> resource group. </p>
  syntax:
    content: public interface ResourceGroup
- uid: com.microsoft.azure.management.resources._deployments
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployments.yml
  name: Deployments
  fullName: com.microsoft.azure.management.resources.Deployments
  type: Interface
  summary: <p>Entry point to template deployment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Deployments extends SupportsCreating< Deployment.DefinitionStages.Blank >,SupportsListing< Deployment >,SupportsListingByGroup< Deployment >,SupportsGettingByName< Deployment >,SupportsGettingByGroup< Deployment >,SupportsGettingById< Deployment >,SupportsDeleting,SupportsDeletingByGroup
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.management.network._subnet
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._subnet.yml
  name: Subnet
  fullName: com.microsoft.azure.management.network.Subnet
  type: Interface
  summary: <p>An immutable client-side representation of a subnet of a virtual network. </p>
  syntax:
    content: public interface Subnet
