items:
- uid: com.microsoft.azure.management.website._virtual_application
  id: _virtual_application
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._virtual_application_1a252b4342a624e3ad24268c76c974882e
  - com.microsoft.azure.management.website._virtual_application_1a859824d928b8430a887f8a1fed0e54f5
  - com.microsoft.azure.management.website._virtual_application_1a7c8c0c48f104fb02331278d71cfb624a
  - com.microsoft.azure.management.website._virtual_application_1ab0b1dbf461127aca1b3fede061db88f4
  - com.microsoft.azure.management.website._virtual_application_1a2a160a30b046724b1dda6d067dcae0eb
  - com.microsoft.azure.management.website._virtual_application_1a410a8da057eb5753d41f43036149f529
  - com.microsoft.azure.management.website._virtual_application_1ae3b6d70d2107e61a1d2cf3c045e2e476
  - com.microsoft.azure.management.website._virtual_application_1a79ccc231e66ad3771b48ed6268d8857b
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: VirtualApplication
  fullName: com.microsoft.azure.management.website.VirtualApplication
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 15
  package: com.microsoft.azure.management.website
  summary: <p>The <xref href="com.microsoft.azure.management.website._virtual_application" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: &o1
    content: public class VirtualApplication
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._virtual_application_1a252b4342a624e3ad24268c76c974882e
  id: _virtual_application_1a252b4342a624e3ad24268c76c974882e
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: physicalPath()
  fullName: String com.microsoft.azure.management.website.VirtualApplication.physicalPath()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 61
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the physicalPath value.</p>

    <p></p>
  syntax:
    content: public String physicalPath()
    return:
      type: "26831127"
      description: <p>the physicalPath value </p>
- uid: com.microsoft.azure.management.website._virtual_application_1a859824d928b8430a887f8a1fed0e54f5
  id: _virtual_application_1a859824d928b8430a887f8a1fed0e54f5
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: preloadEnabled()
  fullName: Boolean com.microsoft.azure.management.website.VirtualApplication.preloadEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 81
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the preloadEnabled value.</p>

    <p></p>
  syntax:
    content: public Boolean preloadEnabled()
    return:
      type: 866c2227
      description: <p>the preloadEnabled value </p>
- uid: com.microsoft.azure.management.website._virtual_application_1a7c8c0c48f104fb02331278d71cfb624a
  id: _virtual_application_1a7c8c0c48f104fb02331278d71cfb624a
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: virtualDirectories()
  fullName: List<VirtualDirectory> com.microsoft.azure.management.website.VirtualApplication.virtualDirectories()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 101
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the virtualDirectories value.</p>

    <p></p>
  syntax:
    content: public List< VirtualDirectory > virtualDirectories()
    return:
      type: f6a6204dcom.microsoft.azure.management.website._virtual_directory9ec3e006
      description: <p>the virtualDirectories value </p>
- uid: com.microsoft.azure.management.website._virtual_application_1ab0b1dbf461127aca1b3fede061db88f4
  id: _virtual_application_1ab0b1dbf461127aca1b3fede061db88f4
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: virtualPath()
  fullName: String com.microsoft.azure.management.website.VirtualApplication.virtualPath()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 41
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the virtualPath value.</p>

    <p></p>
  syntax:
    content: public String virtualPath()
    return:
      type: "26831127"
      description: <p>the virtualPath value </p>
- uid: com.microsoft.azure.management.website._virtual_application_1a2a160a30b046724b1dda6d067dcae0eb
  id: _virtual_application_1a2a160a30b046724b1dda6d067dcae0eb
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: withPhysicalPath(String physicalPath)
  fullName: VirtualApplication com.microsoft.azure.management.website.VirtualApplication.withPhysicalPath(String physicalPath)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 71
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the physicalPath value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withPhysicalPath(String physicalPath)
    parameters:
    - id: physicalPath
      type: "26831127"
      description: <p>the physicalPath value to set </p>
    return:
      type: com.microsoft.azure.management.website._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._virtual_application_1a410a8da057eb5753d41f43036149f529
  id: _virtual_application_1a410a8da057eb5753d41f43036149f529
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: withPreloadEnabled(Boolean preloadEnabled)
  fullName: VirtualApplication com.microsoft.azure.management.website.VirtualApplication.withPreloadEnabled(Boolean preloadEnabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 91
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the preloadEnabled value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withPreloadEnabled(Boolean preloadEnabled)
    parameters:
    - id: preloadEnabled
      type: 866c2227
      description: <p>the preloadEnabled value to set </p>
    return:
      type: com.microsoft.azure.management.website._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._virtual_application_1ae3b6d70d2107e61a1d2cf3c045e2e476
  id: _virtual_application_1ae3b6d70d2107e61a1d2cf3c045e2e476
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: withVirtualDirectories(List< VirtualDirectory > virtualDirectories)
  fullName: VirtualApplication com.microsoft.azure.management.website.VirtualApplication.withVirtualDirectories(List< VirtualDirectory > virtualDirectories)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 111
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the virtualDirectories value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withVirtualDirectories(List< VirtualDirectory > virtualDirectories)
    parameters:
    - id: virtualDirectories
      type: f6a6204dcom.microsoft.azure.management.website._virtual_directory9ec3e006
      description: <p>the virtualDirectories value to set </p>
    return:
      type: com.microsoft.azure.management.website._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._virtual_application_1a79ccc231e66ad3771b48ed6268d8857b
  id: _virtual_application_1a79ccc231e66ad3771b48ed6268d8857b
  parent: com.microsoft.azure.management.website._virtual_application
  href: com.microsoft.azure.management.website._virtual_application.yml
  langs:
  - java
  name: withVirtualPath(String virtualPath)
  fullName: VirtualApplication com.microsoft.azure.management.website.VirtualApplication.withVirtualPath(String virtualPath)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/VirtualApplication.java
    startLine: 51
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the virtualPath value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withVirtualPath(String virtualPath)
    parameters:
    - id: virtualPath
      type: "26831127"
      description: <p>the virtualPath value to set </p>
    return:
      type: com.microsoft.azure.management.website._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: f6a6204dcom.microsoft.azure.management.website._virtual_directory9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.website._virtual_directory
    name: VirtualDirectory
    fullName: com.microsoft.azure.management.website.VirtualDirectory
    href: com.microsoft.azure.management.website._virtual_directory.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.management.website._virtual_directory
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._virtual_directory.yml
  name: VirtualDirectory
  fullName: com.microsoft.azure.management.website.VirtualDirectory
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.website._virtual_directory" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class VirtualDirectory
- uid: com.microsoft.azure.management.website._virtual_application
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._virtual_application.yml
  name: VirtualApplication
  fullName: com.microsoft.azure.management.website.VirtualApplication
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.website._virtual_application" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: *o1
