items:
- uid: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings
  id: _with_settings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withProtectedSetting(String,Object)
  - com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withProtectedSettings(HashMap< String, Object >)
  - com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withPublicSetting(String,Object)
  - com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withPublicSettings(HashMap< String, Object >)
  href: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.yml
  langs:
  - java
  name: VirtualMachineExtension.UpdateStages.WithSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 471
  package: com.microsoft.azure.management.compute
  summary: <p>The stage of the virtual machine extension update allowing to add or update public and private settings. </p>
  syntax:
    content: public interface WithSettings
- uid: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withProtectedSetting(String,Object)
  id: withProtectedSetting(String,Object)
  parent: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings
  href: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.yml
  langs:
  - java
  name: withProtectedSetting(String key, Object value)
  fullName: Update com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting(String key, Object value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 488
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies a private settings entry.</p>

    <p></p>
  syntax:
    content: public Update withProtectedSetting(String key, Object value)
    parameters:
    - id: key
      type: "26831127"
      description: <p>the key of a private settings entry </p>
    - id: value
      type: "79317049"
      description: <p>the value of the private settings entry </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_extension._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withProtectedSettings(HashMap< String, Object >)
  id: withProtectedSettings(HashMap< String, Object >)
  parent: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings
  href: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.yml
  langs:
  - java
  name: withProtectedSettings(HashMap< String, Object > settings)
  fullName: Update com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings(HashMap< String, Object > settings)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 504
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies private settings.</p>

    <p></p>
  syntax:
    content: public Update withProtectedSettings(HashMap< String, Object > settings)
    parameters:
    - id: settings
      type: cdf57bcd
      description: <p>the private settings </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_extension._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withPublicSetting(String,Object)
  id: withPublicSetting(String,Object)
  parent: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings
  href: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.yml
  langs:
  - java
  name: withPublicSetting(String key, Object value)
  fullName: Update com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting(String key, Object value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 479
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies a public settings entry.</p>

    <p></p>
  syntax:
    content: public Update withPublicSetting(String key, Object value)
    parameters:
    - id: key
      type: "26831127"
      description: <p>the key of a public settings entry </p>
    - id: value
      type: "79317049"
      description: <p>the value of the public settings entry </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_extension._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.withPublicSettings(HashMap< String, Object >)
  id: withPublicSettings(HashMap< String, Object >)
  parent: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings
  href: com.microsoft.azure.management.compute._virtual_machine_extension._update_stages._with_settings.yml
  langs:
  - java
  name: withPublicSettings(HashMap< String, Object > settings)
  fullName: Update com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings(HashMap< String, Object > settings)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 496
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Specifies public settings.</p>

    <p></p>
  syntax:
    content: public Update withPublicSettings(HashMap< String, Object > settings)
    parameters:
    - id: settings
      type: cdf57bcd
      description: <p>the public settings </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_extension._update
      description: <p>the next stage of the update </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: cdf57bcd
  spec.java:
  - name: HashMap< String, Object >
    fullName: HashMap< String, Object >
- uid: com.microsoft.azure.management.compute._virtual_machine_extension._update
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._virtual_machine_extension._update.yml
  name: VirtualMachineExtension.Update
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.Update
  type: Interface
  summary: <p>The entirety of virtual machine extension update as a part of parent virtual machine update. </p>
  syntax:
    content: public interface Update extends Settable< VirtualMachine.Update >,VirtualMachineExtension.UpdateStages.WithAutoUpgradeMinorVersion,VirtualMachineExtension.UpdateStages.WithSettings,VirtualMachineExtension.UpdateStages.WithTags
