items:
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers
  id: _application_get_headers
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1ae387157f4437c02f2390550e6f05b257
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1a7863004c275b369cd0f8cd37ce0d0e6d
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1a777306adf9d4107c497c5ac07c072a46
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1afc7bb7c6a591a9ef6899d2af507242c2
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1a1918f273f1fa6a61a66ef84cb4b79c2f
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1a68f2b06d472e6251c79da02840d56ec8
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1a442d4ad2714a5e30b862c4e31ee48871
  - com.microsoft.azure.batch.protocol.models._application_get_headers_1ab8f744aee6bb4cef598fecf11d7fbd3f
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: ApplicationGetHeaders
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Defines headers for Get operation. </p>
  syntax: &o1
    content: public class ApplicationGetHeaders
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1ae387157f4437c02f2390550e6f05b257
  id: _application_get_headers_1ae387157f4437c02f2390550e6f05b257
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 48
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1a7863004c275b369cd0f8cd37ce0d0e6d
  id: _application_get_headers_1a7863004c275b369cd0f8cd37ce0d0e6d
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: eTag()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.eTag()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 88
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the eTag value.</p>

    <p></p>
  syntax:
    content: public String eTag()
    return:
      type: "26831127"
      description: <p>the eTag value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1a777306adf9d4107c497c5ac07c072a46
  id: _application_get_headers_1a777306adf9d4107c497c5ac07c072a46
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: lastModified()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.lastModified()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 108
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the lastModified value.</p>

    <p></p>
  syntax:
    content: public DateTime lastModified()
    return:
      type: 230df18c
      description: <p>the lastModified value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1afc7bb7c6a591a9ef6899d2af507242c2
  id: _application_get_headers_1afc7bb7c6a591a9ef6899d2af507242c2
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: requestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.requestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 68
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the requestId value.</p>

    <p></p>
  syntax:
    content: public String requestId()
    return:
      type: "26831127"
      description: <p>the requestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1a1918f273f1fa6a61a66ef84cb4b79c2f
  id: _application_get_headers_1a1918f273f1fa6a61a66ef84cb4b79c2f
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ApplicationGetHeaders com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 58
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetHeaders withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1a68f2b06d472e6251c79da02840d56ec8
  id: _application_get_headers_1a68f2b06d472e6251c79da02840d56ec8
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: withETag(String eTag)
  fullName: ApplicationGetHeaders com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.withETag(String eTag)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 98
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the eTag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetHeaders withETag(String eTag)
    parameters:
    - id: eTag
      type: "26831127"
      description: <p>the eTag value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1a442d4ad2714a5e30b862c4e31ee48871
  id: _application_get_headers_1a442d4ad2714a5e30b862c4e31ee48871
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: withLastModified(DateTime lastModified)
  fullName: ApplicationGetHeaders com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.withLastModified(DateTime lastModified)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 121
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the lastModified value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetHeaders withLastModified(DateTime lastModified)
    parameters:
    - id: lastModified
      type: 230df18c
      description: <p>the lastModified value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers_1ab8f744aee6bb4cef598fecf11d7fbd3f
  id: _application_get_headers_1ab8f744aee6bb4cef598fecf11d7fbd3f
  parent: com.microsoft.azure.batch.protocol.models._application_get_headers
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  langs:
  - java
  name: withRequestId(String requestId)
  fullName: ApplicationGetHeaders com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders.withRequestId(String requestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetHeaders.java
    startLine: 78
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the requestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetHeaders withRequestId(String requestId)
    parameters:
    - id: requestId
      type: "26831127"
      description: <p>the requestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.rest._date_time_rfc1123
  parent: com.microsoft.rest
  href: com.microsoft.rest._date_time_rfc1123.yml
  name: DateTimeRfc1123
  fullName: com.microsoft.rest.DateTimeRfc1123
  type: Class
  summary: <p>Simple wrapper over joda.time.DateTime used for specifying RFC1123 format during serialization/deserialization. </p>
  syntax:
    content: public class DateTimeRfc1123
- uid: com.microsoft.azure.batch.protocol.models._application_get_headers
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_get_headers.yml
  name: ApplicationGetHeaders
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationGetHeaders
  type: Class
  summary: <p>Defines headers for Get operation. </p>
  syntax: *o1
