items:
- uid: com.microsoft.azure.management.batch._application._update_definition_stages._blank
  id: _blank
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update_definition_stages._blank.yml
  langs:
  - java
  name: Application.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 132
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>The first stage of a application definition.</p>

    <p></p>
  syntax:
    content: public interface Blank<ParentT> extends Application.UpdateDefinitionStages.WithAttach< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  - com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746.defineNewApplicationPackage(String)
  - com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.withAllowUpdates(boolean)
  - com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.withDisplayName(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.InUpdate< ParentT >.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746.defineNewApplicationPackage(String)
  parent: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746
  href: com.microsoft.azure.management.batch._application._update_definition_af002c8421e16b745af55a95ece4e746.yml
  name: defineNewApplicationPackage(String version)
  fullName: UpdateDefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.WithApplicationPackage< ParentT >.defineNewApplicationPackage(String version)
  type: Method
  summary: >-
    <p>First stage to create new application package in Batch account application.</p>

    <p></p>
  syntax:
    content: public UpdateDefinitionStages.WithAttach< ParentT > defineNewApplicationPackage(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version of the application </p>
    return:
      type: 25536b4e
      description: <p>next stage to create the application. </p>
- uid: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.withAllowUpdates(boolean)
  parent: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach
  href: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.yml
  name: withAllowUpdates(boolean allowUpdates)
  fullName: UpdateDefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.WithAttach< ParentT >.withAllowUpdates(boolean allowUpdates)
  type: Method
  summary: >-
    <p>Allow automatic application updates.</p>

    <p></p>
  syntax:
    content: public UpdateDefinitionStages.WithAttach< ParentT > withAllowUpdates(boolean allowUpdates)
    parameters:
    - id: allowUpdates
      type: 4fc6e284
      description: <p>true to allow the automatic updates of application, otherwise false </p>
    return:
      type: 25536b4e
      description: <p>parent batch account update definition. </p>
- uid: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.withDisplayName(String)
  parent: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach
  href: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.yml
  name: withDisplayName(String displayName)
  fullName: UpdateDefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.WithAttach< ParentT >.withDisplayName(String displayName)
  type: Method
  summary: >-
    <p>Specifies the display name for the application.</p>

    <p></p>
  syntax:
    content: public UpdateDefinitionStages.WithAttach< ParentT > withDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
      description: <p>display name for the application. </p>
    return:
      type: 25536b4e
      description: <p>parent batch account update definition. </p>
- uid: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update_definition_stages._with_attach.yml
  name: Application.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of the application definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the application definition can be attached to the parent batch account definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.batch._application._update_definition
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update_definition.yml
  name: Application.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of a application definition as a part of parent update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
