items:
- uid: com.microsoft.azure.management.batch._application._update_definition_stages
  id: _update_definition_stages
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update_definition_stages.yml
  langs:
  - java
  name: Application.UpdateDefinitionStages
  fullName: com.microsoft.azure.management.batch.Application.UpdateDefinitionStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 126
  package: com.microsoft.azure.management.batch
  summary: <p>Grouping of application definition stages as part of parent batch account update. </p>
  syntax:
    content: public interface UpdateDefinitionStages
references: []
