items:
- uid: com.microsoft.azure.management.resources._deployment_operations
  id: _deployment_operations
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment_operations.yml
  langs:
  - java
  name: DeploymentOperations
  fullName: com.microsoft.azure.management.resources.DeploymentOperations
  type: Interface
  source:
    remote:
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperations.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperations.java
    startLine: 16
  package: com.microsoft.azure.management.resources
  summary: <p>Entry point to deployment operation management API. </p>
  syntax:
    content: public interface DeploymentOperations extends SupportsListing< DeploymentOperation >,SupportsGettingById< DeploymentOperation >
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.getById(String)
  - com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.list()
references:
- uid: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.getById(String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id
  href: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.yml
  name: getById(String id)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.collection.SupportsGettingById< T >.getById(String id)
  type: Method
  summary: >-
    <p>Gets the information about a resource from <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> based on the resource id.</p>

    <p></p>
  syntax:
    content: public T getById(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id of the resource. </p>
    return:
      type: 8ce1ecb9
      description: <p>an immutable representation of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.list()
  parent: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.yml
  name: list()
  fullName: PagedList<T> com.microsoft.azure.management.resources.fluentcore.collection.SupportsListing< T >.list()
  type: Method
  summary: >-
    <p>Lists all the resources of the specified type in the currently selected subscription.</p>

    <p></p>
  syntax:
    content: public PagedList< T > list()
    return:
      type: com.microsoft.azure._paged_list34132889
      description: <p>list of resources </p>
- uid: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing
  parent: com.microsoft.azure.management.resources.fluentcore.collection
  href: com.microsoft.azure.management.resources.fluentcore.collection._supports_listing.yml
  name: SupportsListing<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.collection.SupportsListing<T>
  type: Interface
  summary: >-
    <p>Provides access to listing <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> resources of a specific type in a subscription. </p>

    <p>(Note: this interface is not intended to be implemented by user code)</p>

    <p></p>
  syntax:
    content: public interface SupportsListing<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the fluent type of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id
  parent: com.microsoft.azure.management.resources.fluentcore.arm.collection
  href: com.microsoft.azure.management.resources.fluentcore.arm.collection._supports_getting_by_id.yml
  name: SupportsGettingById<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.collection.SupportsGettingById<T>
  type: Interface
  summary: >-
    <p>Provides access to getting a specific <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> resource based on its resource ID.</p>

    <p></p>
  syntax:
    content: public interface SupportsGettingById<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the resource collection </p>
- uid: com.microsoft.azure.management.resources.implementation._deployment_operations_impl
