items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  id: _with_private_ip
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.withPrivateIpVersion(IPVersion)
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateStages.WithPrivateIp
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 384
  package: com.microsoft.azure.management.network
  summary: <p>The stage of the network interface IP configuration update allowing to specify private IP. </p>
  syntax:
    content: public interface WithPrivateIp extends HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress< Update >
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressStatic(String)
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.withPrivateIpVersion(IPVersion)
  id: withPrivateIpVersion(IPVersion)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  langs:
  - java
  name: withPrivateIpVersion(IPVersion ipVersion)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp.withPrivateIpVersion(IPVersion ipVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 390
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the IP version for the private IP address. </p>
  syntax:
    content: public Update withPrivateIpVersion(IPVersion ipVersion)
    parameters:
    - id: ipVersion
      type: com.microsoft.azure.management.network._i_p_version
      description: <p>an IP version </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the update </p>
references:
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>
  type: Interface
  summary: <p>The stage of an update allowing to modify the private IP address. </p>
  syntax:
    content: public interface WithPrivateIpAddress<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update.yml
  name: NicIpConfiguration.Update
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Update
  type: Interface
  summary: <p>The entirety of a network interface IP configuration update as part of a network interface update. </p>
  syntax:
    content: public interface Update extends Settable< NetworkInterface.Update >,NicIpConfiguration.UpdateStages.WithSubnet,NicIpConfiguration.UpdateStages.WithPrivateIp,NicIpConfiguration.UpdateStages.WithPublicIpAddress,NicIpConfiguration.UpdateStages.WithLoadBalancer
- uid: com.microsoft.azure.management.network._i_p_version
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._i_p_version.yml
  name: IPVersion
  fullName: com.microsoft.azure.management.network.IPVersion
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._i_p_version" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class IPVersion
