items:
- uid: com.microsoft.azure.management.website._enabled_config
  id: _enabled_config
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._enabled_config.enabled()
  - com.microsoft.azure.management.website._enabled_config.withEnabled(Boolean)
  href: com.microsoft.azure.management.website._enabled_config.yml
  langs:
  - java
  name: EnabledConfig
  fullName: com.microsoft.azure.management.website.EnabledConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/EnabledConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/EnabledConfig.java
    startLine: 14
  package: com.microsoft.azure.management.website
  summary: <p>Enabled configuration. </p>
  syntax: &o1
    content: public class EnabledConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._enabled_config.enabled()
  id: enabled()
  parent: com.microsoft.azure.management.website._enabled_config
  href: com.microsoft.azure.management.website._enabled_config.yml
  langs:
  - java
  name: enabled()
  fullName: Boolean com.microsoft.azure.management.website.EnabledConfig.enabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/EnabledConfig.java
    startLine: 25
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the enabled value.</p>

    <p></p>
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.website._enabled_config.withEnabled(Boolean)
  id: withEnabled(Boolean)
  parent: com.microsoft.azure.management.website._enabled_config
  href: com.microsoft.azure.management.website._enabled_config.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  fullName: EnabledConfig com.microsoft.azure.management.website.EnabledConfig.withEnabled(Boolean enabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/EnabledConfig.java
    startLine: 35
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the enabled value.</p>

    <p></p>
  syntax:
    content: public EnabledConfig withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.website._enabled_config
      description: <p>the <xref href="com.microsoft.azure.management.website._enabled_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.website._enabled_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._enabled_config.yml
  name: EnabledConfig
  fullName: com.microsoft.azure.management.website.EnabledConfig
  type: Class
  summary: <p>Enabled configuration. </p>
  syntax: *o1
