items:
- uid: com.microsoft.azure.management.website.implementation._deployment_collection_inner
  id: _deployment_collection_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._deployment_collection_inner.nextLink()
  - com.microsoft.azure.management.website.implementation._deployment_collection_inner.value()
  - com.microsoft.azure.management.website.implementation._deployment_collection_inner.withNextLink(String)
  - com.microsoft.azure.management.website.implementation._deployment_collection_inner.withValue(List< DeploymentInner >)
  href: com.microsoft.azure.management.website.implementation._deployment_collection_inner.yml
  langs:
  - java
  name: DeploymentCollectionInner
  fullName: com.microsoft.azure.management.website.implementation.DeploymentCollectionInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/DeploymentCollectionInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/DeploymentCollectionInner.java
    startLine: 15
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Collection of app deployments. </p>
  syntax: &o1
    content: public class DeploymentCollectionInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation._deployment_collection_inner.nextLink()
  id: nextLink()
  parent: com.microsoft.azure.management.website.implementation._deployment_collection_inner
  href: com.microsoft.azure.management.website.implementation._deployment_collection_inner.yml
  langs:
  - java
  name: nextLink()
  fullName: String com.microsoft.azure.management.website.implementation.DeploymentCollectionInner.nextLink()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/DeploymentCollectionInner.java
    startLine: 51
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the nextLink value.</p>

    <p></p>
  syntax:
    content: public String nextLink()
    return:
      type: "26831127"
      description: <p>the nextLink value </p>
- uid: com.microsoft.azure.management.website.implementation._deployment_collection_inner.value()
  id: value()
  parent: com.microsoft.azure.management.website.implementation._deployment_collection_inner
  href: com.microsoft.azure.management.website.implementation._deployment_collection_inner.yml
  langs:
  - java
  name: value()
  fullName: List<DeploymentInner> com.microsoft.azure.management.website.implementation.DeploymentCollectionInner.value()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/DeploymentCollectionInner.java
    startLine: 31
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the value value.</p>

    <p></p>
  syntax:
    content: public List< DeploymentInner > value()
    return:
      type: f6a6204dcom.microsoft.azure.management.website.implementation._deployment_inner9ec3e006
      description: <p>the value value </p>
- uid: com.microsoft.azure.management.website.implementation._deployment_collection_inner.withNextLink(String)
  id: withNextLink(String)
  parent: com.microsoft.azure.management.website.implementation._deployment_collection_inner
  href: com.microsoft.azure.management.website.implementation._deployment_collection_inner.yml
  langs:
  - java
  name: withNextLink(String nextLink)
  fullName: DeploymentCollectionInner com.microsoft.azure.management.website.implementation.DeploymentCollectionInner.withNextLink(String nextLink)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/DeploymentCollectionInner.java
    startLine: 61
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the nextLink value.</p>

    <p></p>
  syntax:
    content: public DeploymentCollectionInner withNextLink(String nextLink)
    parameters:
    - id: nextLink
      type: "26831127"
      description: <p>the nextLink value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._deployment_collection_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._deployment_collection_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._deployment_collection_inner.withValue(List< DeploymentInner >)
  id: withValue(List< DeploymentInner >)
  parent: com.microsoft.azure.management.website.implementation._deployment_collection_inner
  href: com.microsoft.azure.management.website.implementation._deployment_collection_inner.yml
  langs:
  - java
  name: withValue(List< DeploymentInner > value)
  fullName: DeploymentCollectionInner com.microsoft.azure.management.website.implementation.DeploymentCollectionInner.withValue(List< DeploymentInner > value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/DeploymentCollectionInner.java
    startLine: 41
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the value value.</p>

    <p></p>
  syntax:
    content: public DeploymentCollectionInner withValue(List< DeploymentInner > value)
    parameters:
    - id: value
      type: f6a6204dcom.microsoft.azure.management.website.implementation._deployment_inner9ec3e006
      description: <p>the value value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._deployment_collection_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._deployment_collection_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.website.implementation._deployment_inner9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.website.implementation._deployment_inner
    name: DeploymentInner
    fullName: com.microsoft.azure.management.website.implementation.DeploymentInner
    href: com.microsoft.azure.management.website.implementation._deployment_inner.yml
  - name: " >"
    fullName: " >"
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website.implementation._deployment_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._deployment_inner.yml
  name: DeploymentInner
  fullName: com.microsoft.azure.management.website.implementation.DeploymentInner
  type: Class
  summary: <p>Represents user crendentials used for publishing activity. </p>
  syntax:
    content: public class DeploymentInner
- uid: com.microsoft.azure.management.website.implementation._deployment_collection_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._deployment_collection_inner.yml
  name: DeploymentCollectionInner
  fullName: com.microsoft.azure.management.website.implementation.DeploymentCollectionInner
  type: Class
  summary: <p>Collection of app deployments. </p>
  syntax: *o1
