items:
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  id: _application_gateway_path_rule_inner
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.backendAddressPool()
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.backendHttpSettings()
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.etag()
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.name()
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.paths()
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.provisioningState()
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withBackendAddressPool(SubResource)
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withBackendHttpSettings(SubResource)
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withEtag(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withName(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withPaths(List< String >)
  - com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withProvisioningState(String)
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: ApplicationGatewayPathRuleInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 19
  package: com.microsoft.azure.management.network.implementation
  summary: <p>Path rule of URL path map of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayPathRuleInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.backendAddressPool()
  id: backendAddressPool()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: backendAddressPool()
  fullName: SubResource com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.backendAddressPool()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 80
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the backendAddressPool value.</p>

    <p></p>
  syntax:
    content: public SubResource backendAddressPool()
    return:
      type: 4151c390
      description: <p>the backendAddressPool value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.backendHttpSettings()
  id: backendHttpSettings()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: backendHttpSettings()
  fullName: SubResource com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.backendHttpSettings()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 100
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the backendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public SubResource backendHttpSettings()
    return:
      type: 4151c390
      description: <p>the backendHttpSettings value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 160
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 140
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.paths()
  id: paths()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: paths()
  fullName: List<String> com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.paths()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 60
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the paths value.</p>

    <p></p>
  syntax:
    content: public List< String > paths()
    return:
      type: f35af49b
      description: <p>the paths value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 120
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withBackendAddressPool(SubResource)
  id: withBackendAddressPool(SubResource)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: withBackendAddressPool(SubResource backendAddressPool)
  fullName: ApplicationGatewayPathRuleInner com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.withBackendAddressPool(SubResource backendAddressPool)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 90
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the backendAddressPool value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRuleInner withBackendAddressPool(SubResource backendAddressPool)
    parameters:
    - id: backendAddressPool
      type: 4151c390
      description: <p>the backendAddressPool value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withBackendHttpSettings(SubResource)
  id: withBackendHttpSettings(SubResource)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: withBackendHttpSettings(SubResource backendHttpSettings)
  fullName: ApplicationGatewayPathRuleInner com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.withBackendHttpSettings(SubResource backendHttpSettings)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 110
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the backendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRuleInner withBackendHttpSettings(SubResource backendHttpSettings)
    parameters:
    - id: backendHttpSettings
      type: 4151c390
      description: <p>the backendHttpSettings value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayPathRuleInner com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 170
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRuleInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayPathRuleInner com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 150
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRuleInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withPaths(List< String >)
  id: withPaths(List< String >)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: withPaths(List< String > paths)
  fullName: ApplicationGatewayPathRuleInner com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.withPaths(List< String > paths)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 70
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the paths value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRuleInner withPaths(List< String > paths)
    parameters:
    - id: paths
      type: f35af49b
      description: <p>the paths value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayPathRuleInner com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayPathRuleInner.java
    startLine: 130
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRuleInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: 4151c390
  spec.java:
  - name: SubResource
    fullName: SubResource
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._backend
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._backend.yml
  name: Backend
  fullName: com.microsoft.azure.management.network.Backend
  type: Interface
  summary: <p>An immutable client-side representation of an load balancer's backend address pool. </p>
  syntax:
    content: public interface Backend
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  name: ApplicationGatewayPathRuleInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner
  type: Class
  summary: <p>Path rule of URL path map of application gateway. </p>
  syntax: *o1
