items:
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_application_package
  id: _with_application_package
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._application._definition_stages._with_application_package.defineNewApplicationPackage(String)
  href: com.microsoft.azure.management.batch._application._definition_stages._with_application_package.yml
  langs:
  - java
  name: Application.DefinitionStages.WithApplicationPackage<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.DefinitionStages.WithApplicationPackage<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 76
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>A application definition to allow creation of application package.</p>

    <p></p>
  syntax:
    content: public interface WithApplicationPackage<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_application_package.defineNewApplicationPackage(String)
  id: defineNewApplicationPackage(String)
  parent: com.microsoft.azure.management.batch._application._definition_stages._with_application_package
  href: com.microsoft.azure.management.batch._application._definition_stages._with_application_package.yml
  langs:
  - java
  name: defineNewApplicationPackage(String applicationPackageName)
  fullName: DefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.DefinitionStages.WithApplicationPackage< ParentT >.defineNewApplicationPackage(String applicationPackageName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 83
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>First stage to create new application package in Batch account application.</p>

    <p></p>
  syntax:
    content: public DefinitionStages.WithAttach< ParentT > defineNewApplicationPackage(String applicationPackageName)
    parameters:
    - id: applicationPackageName
      type: "26831127"
      description: <p>the version of the application </p>
    return:
      type: 350be077
      description: <p>next stage to create the application. </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 350be077
  spec.java:
  - name: DefinitionStages.WithAttach< ParentT >
    fullName: DefinitionStages.WithAttach< ParentT >
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_attach
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._definition_stages._with_attach.yml
  name: Application.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of the application definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the application definition can be attached to the parent batch account definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.InDefinition< ParentT >.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
