items:
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._blank
  id: _blank
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition_stages._blank.yml
  langs:
  - java
  name: Deployment.DefinitionStages.Blank
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.Blank
  type: Interface
  source:
    remote:
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 138
  package: com.microsoft.azure.management.resources
  summary: <p>The first stage of deployment definition. </p>
  syntax:
    content: public interface Blank extends Deployment.DefinitionStages.WithGroup
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.withExistingResourceGroup(String)
  - com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.withExistingResourceGroup(ResourceGroup)
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_group.withNewResourceGroup(String,Region)
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_group.withNewResourceGroup(Creatable< ResourceGroup >)
references:
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.withExistingResourceGroup(String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.yml
  name: withExistingResourceGroup(String groupName)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.models.GroupableResource.DefinitionStages.WithExistingResourceGroup< T >.withExistingResourceGroup(String groupName)
  type: Method
  summary: <p>Associates the resource with an existing resource group. </p>
  syntax:
    content: public T withExistingResourceGroup(String groupName)
    parameters:
    - id: groupName
      type: "26831127"
      description: <p>the name of an existing resource group to put this resource in. </p>
    return:
      type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.withExistingResourceGroup(ResourceGroup)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.yml
  name: withExistingResourceGroup(ResourceGroup group)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.models.GroupableResource.DefinitionStages.WithExistingResourceGroup< T >.withExistingResourceGroup(ResourceGroup group)
  type: Method
  summary: <p>Associates the resource with an existing resource group. </p>
  syntax:
    content: public T withExistingResourceGroup(ResourceGroup group)
    parameters:
    - id: group
      type: com.microsoft.azure.management.resources._resource_group
      description: <p>an existing resource group to put the resource in </p>
    return:
      type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.withNewResourceGroup(String,Region)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_group
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.yml
  name: withNewResourceGroup(String name, Region region)
  fullName: WithTemplate com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithGroup.withNewResourceGroup(String name, Region region)
  type: Method
  summary: <p>Creates a new resource group to put the deployment in. </p>
  syntax:
    content: public WithTemplate withNewResourceGroup(String name, Region region)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the new group </p>
    - id: region
      type: com.microsoft.azure.management.resources.fluentcore.arm._region
      description: <p>the region to create the resource group in </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
      description: <p>the next stage of the deployment definition </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.withNewResourceGroup(Creatable< ResourceGroup >)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_group
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.yml
  name: withNewResourceGroup(Creatable< ResourceGroup > groupDefinition)
  fullName: WithTemplate com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithGroup.withNewResourceGroup(Creatable< ResourceGroup > groupDefinition)
  type: Method
  summary: <p>Creates a new resource group to put the resource in, based on the definition specified. </p>
  syntax:
    content: public WithTemplate withNewResourceGroup(Creatable< ResourceGroup > groupDefinition)
    parameters:
    - id: groupDefinition
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.resources._resource_group9ec3e006
      description: <p>a creatable definition for a new resource group </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
      description: <p>the next stage of the deployment definition </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_group
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.yml
  name: Deployment.DefinitionStages.WithGroup
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithGroup
  type: Interface
  summary: <p>A deployment definition allowing resource group to be specified. </p>
  syntax:
    content: public interface WithGroup
- uid: com.microsoft.azure.management.resources._deployment._definition
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition.yml
  name: Deployment.Definition
  fullName: com.microsoft.azure.management.resources.Deployment.Definition
  type: Interface
  summary: <p>Container interface for all the deployment definitions. </p>
  syntax:
    content: public interface Definition
