items:
- uid: com.microsoft.azure._azure_environment
  id: _azure_environment
  parent: com.microsoft.azure
  children:
  - com.microsoft.azure._azure_environment_1a1673a5df55970e40e56fe06dd10b0e32
  - com.microsoft.azure._azure_environment_1aa9acafa8cb22d8813c8f85f388c41513
  - com.microsoft.azure._azure_environment_1a64665e171024f33d4dfdec557707d750
  - com.microsoft.azure._azure_environment_1a157b57257ae663cb043c5ab3c8a5560a
  - com.microsoft.azure._azure_environment_1a3a50f2edd3a3b4cbd9bd0d58fdd14a48
  - com.microsoft.azure._azure_environment_1a6b65f6ffc53f47f3d59d8fd4bbba9b55
  - com.microsoft.azure._azure_environment_1a73d6f251560aafb6547aca8cabceab70
  - com.microsoft.azure._azure_environment_1ac3fd47a915f15d202f4327293c9e2ed1
  - com.microsoft.azure._azure_environment_1a668a4937ddd5fe3904e6f37e0aa3b3f5
  - com.microsoft.azure._azure_environment_1a46c6f6f1cfc65b282656b550a883113f
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AzureEnvironment
  fullName: com.microsoft.azure.AzureEnvironment
  type: Class
  source:
    remote: &o0
      path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 12
  package: com.microsoft.azure
  summary: <p>An instance of this class describes an environment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class AzureEnvironment
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure._azure_environment_1a1673a5df55970e40e56fe06dd10b0e32
  id: _azure_environment_1a1673a5df55970e40e56fe06dd10b0e32
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 57
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE= new AzureEnvironment(
                  "https://login.windows.net/",
                  "https://management.core.windows.net/",
                  true,
                  "https://management.azure.com/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment_1aa9acafa8cb22d8813c8f85f388c41513
  id: _azure_environment_1aa9acafa8cb22d8813c8f85f388c41513
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE_CHINA
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE_CHINA
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 66
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> China. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE_CHINA= new AzureEnvironment(
                  "https://login.chinacloudapi.cn/",
                  "https://management.core.chinacloudapi.cn/",
                  true,
                  "https://management.chinacloudapi.cn/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment_1a64665e171024f33d4dfdec557707d750
  id: _azure_environment_1a64665e171024f33d4dfdec557707d750
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE_GERMANY
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE_GERMANY
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 84
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Germany. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE_GERMANY= new AzureEnvironment(
                  "https://login.microsoftonline.de/",
                  "https://management.core.cloudapi.de/",
                  true,
                  "https://management.microsoftazure.de/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment_1a157b57257ae663cb043c5ab3c8a5560a
  id: _azure_environment_1a157b57257ae663cb043c5ab3c8a5560a
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE_US_GOVERNMENT
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE_US_GOVERNMENT
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 75
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> US Government. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE_US_GOVERNMENT= new AzureEnvironment(
                  "https://login.microsoftonline.com/",
                  "https://management.core.usgovcloudapi.net/",
                  true,
                  "https://management.usgovcloudapi.net/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment_1a3a50f2edd3a3b4cbd9bd0d58fdd14a48
  id: _azure_environment_1a3a50f2edd3a3b4cbd9bd0d58fdd14a48
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AzureEnvironment(String authenticationEndpoint, String tokenAudience, boolean validateAuthority, String baseUrl)
  fullName: com.microsoft.azure.AzureEnvironment.AzureEnvironment(String authenticationEndpoint, String tokenAudience, boolean validateAuthority, String baseUrl)
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 43
  package: com.microsoft.azure
  summary: >-
    <p>Initializes an instance of <xref href="com.microsoft.azure._azure_environment" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public AzureEnvironment(String authenticationEndpoint, String tokenAudience, boolean validateAuthority, String baseUrl)
    parameters:
    - id: authenticationEndpoint
      type: "26831127"
      description: <p>ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment. </p>
    - id: tokenAudience
      type: "26831127"
      description: <p>token audience for an endpoint. </p>
    - id: validateAuthority
      type: 4fc6e284
      description: <p>whether the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD. </p>
    - id: baseUrl
      type: "26831127"
      description: <p>the base URL for the current environment. </p>
- uid: com.microsoft.azure._azure_environment_1a6b65f6ffc53f47f3d59d8fd4bbba9b55
  id: _azure_environment_1a6b65f6ffc53f47f3d59d8fd4bbba9b55
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: getAuthenticationEndpoint()
  fullName: String com.microsoft.azure.AzureEnvironment.getAuthenticationEndpoint()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 115
  package: com.microsoft.azure
  summary: >-
    <p>Gets the ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment.</p>

    <p></p>
  syntax:
    content: public String getAuthenticationEndpoint()
    return:
      type: "26831127"
      description: <p>the ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment. </p>
- uid: com.microsoft.azure._azure_environment_1a73d6f251560aafb6547aca8cabceab70
  id: _azure_environment_1a73d6f251560aafb6547aca8cabceab70
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: getBaseUrl()
  fullName: String com.microsoft.azure.AzureEnvironment.getBaseUrl()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 95
  package: com.microsoft.azure
  summary: >-
    <p>Gets the base URL of the management service.</p>

    <p></p>
  syntax:
    content: public String getBaseUrl()
    return:
      type: "26831127"
      description: <p>the Base URL for the management service. </p>
- uid: com.microsoft.azure._azure_environment_1ac3fd47a915f15d202f4327293c9e2ed1
  id: _azure_environment_1ac3fd47a915f15d202f4327293c9e2ed1
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: getTokenAudience()
  fullName: String com.microsoft.azure.AzureEnvironment.getTokenAudience()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 124
  package: com.microsoft.azure
  summary: >-
    <p>Gets the token audience for an endpoint.</p>

    <p></p>
  syntax:
    content: public String getTokenAudience()
    return:
      type: "26831127"
      description: <p>the token audience for an endpoint. </p>
- uid: com.microsoft.azure._azure_environment_1a668a4937ddd5fe3904e6f37e0aa3b3f5
  id: _azure_environment_1a668a4937ddd5fe3904e6f37e0aa3b3f5
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: isValidateAuthority()
  fullName: boolean com.microsoft.azure.AzureEnvironment.isValidateAuthority()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 135
  package: com.microsoft.azure
  summary: >-
    <p>Gets whether the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD.</p>

    <p></p>
  syntax:
    content: public boolean isValidateAuthority()
    return:
      type: 4fc6e284
      description: <p>true if the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD, false otherwise. </p>
- uid: com.microsoft.azure._azure_environment_1a46c6f6f1cfc65b282656b550a883113f
  id: _azure_environment_1a46c6f6f1cfc65b282656b550a883113f
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: newRestClientBuilder()
  fullName: RestClient.Builder.Buildable com.microsoft.azure.AzureEnvironment.newRestClientBuilder()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 104
  package: com.microsoft.azure
  summary: >-
    <p>Gets a builder for <xref href="com.microsoft.azure._rest_client" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public RestClient.Builder.Buildable newRestClientBuilder()
    return:
      type: 9ab08eaf
      description: <p>a builder for the rest client. </p>
references:
- uid: 93de0ef9com.microsoft.azure._azure_environment
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure._azure_environment
    name: AzureEnvironment
    fullName: com.microsoft.azure.AzureEnvironment
    href: com.microsoft.azure._azure_environment.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 9ab08eaf
  spec.java:
  - name: RestClient.Builder.Buildable
    fullName: RestClient.Builder.Buildable
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure._azure_environment
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure_environment.yml
  name: AzureEnvironment
  fullName: com.microsoft.azure.AzureEnvironment
  type: Class
  summary: <p>An instance of this class describes an environment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
- uid: com.microsoft.azure._rest_client
  parent: com.microsoft.azure
  href: com.microsoft.azure._rest_client.yml
  name: RestClient
  fullName: com.microsoft.azure.RestClient
  type: Class
  summary: <p>An instance of this class stores the client information for making REST calls. </p>
  syntax:
    content: public class RestClient
