items:
- uid: com.microsoft.azure.management.network._application_gateway_protocol
  id: _application_gateway_protocol
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_protocol_1a1dd89bb846e73fcb1fbe52d8d18f2ebd
  - com.microsoft.azure.management.network._application_gateway_protocol_1ad59834c01a41885ba09c0381e272dc8a
  - com.microsoft.azure.management.network._application_gateway_protocol_1ad939cffcb0c591f746e139a31993c7b4
  - com.microsoft.azure.management.network._application_gateway_protocol_1a0fda723e72f1c8142d451fcf67c878a2
  - com.microsoft.azure.management.network._application_gateway_protocol_1a7b37ec8ffa5101c5104b783242331a27
  - com.microsoft.azure.management.network._application_gateway_protocol_1ac48f1948df04ec34e476d41161ca9a49
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  langs:
  - java
  name: ApplicationGatewayProtocol
  fullName: com.microsoft.azure.management.network.ApplicationGatewayProtocol
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayProtocol
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_protocol_1a1dd89bb846e73fcb1fbe52d8d18f2ebd
  id: _application_gateway_protocol_1a1dd89bb846e73fcb1fbe52d8d18f2ebd
  parent: com.microsoft.azure.management.network._application_gateway_protocol
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  langs:
  - java
  name: ApplicationGatewayProtocol(String value)
  fullName: com.microsoft.azure.management.network.ApplicationGatewayProtocol.ApplicationGatewayProtocol(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
    startLine: 28
  package: com.microsoft.azure.management.network
  summary: <p>Creates a custom value for <xref href="com.microsoft.azure.management.network._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public ApplicationGatewayProtocol(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the custom value </p>
- uid: com.microsoft.azure.management.network._application_gateway_protocol_1ad59834c01a41885ba09c0381e272dc8a
  id: _application_gateway_protocol_1ad59834c01a41885ba09c0381e272dc8a
  parent: com.microsoft.azure.management.network._application_gateway_protocol
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  langs:
  - java
  name: equals(Object obj)
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewayProtocol.equals(Object obj)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
    startLine: 44
  package: com.microsoft.azure.management.network
  syntax:
    content: public boolean equals(Object obj)
    parameters:
    - id: obj
      type: "79317049"
    return:
      type: 4fc6e284
- uid: com.microsoft.azure.management.network._application_gateway_protocol_1ad939cffcb0c591f746e139a31993c7b4
  id: _application_gateway_protocol_1ad939cffcb0c591f746e139a31993c7b4
  parent: com.microsoft.azure.management.network._application_gateway_protocol
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  langs:
  - java
  name: hashCode()
  fullName: int com.microsoft.azure.management.network.ApplicationGatewayProtocol.hashCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
    startLine: 39
  package: com.microsoft.azure.management.network
  syntax:
    content: public int hashCode()
    return:
      type: f75371fa
- uid: com.microsoft.azure.management.network._application_gateway_protocol_1a0fda723e72f1c8142d451fcf67c878a2
  id: _application_gateway_protocol_1a0fda723e72f1c8142d451fcf67c878a2
  parent: com.microsoft.azure.management.network._application_gateway_protocol
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  langs:
  - java
  name: HTTP
  fullName: final ApplicationGatewayProtocol com.microsoft.azure.management.network.ApplicationGatewayProtocol.HTTP
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>Static value Http for <xref href="com.microsoft.azure.management.network._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayProtocol HTTP= new ApplicationGatewayProtocol("Http")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_protocol
- uid: com.microsoft.azure.management.network._application_gateway_protocol_1a7b37ec8ffa5101c5104b783242331a27
  id: _application_gateway_protocol_1a7b37ec8ffa5101c5104b783242331a27
  parent: com.microsoft.azure.management.network._application_gateway_protocol
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  langs:
  - java
  name: HTTPS
  fullName: final ApplicationGatewayProtocol com.microsoft.azure.management.network.ApplicationGatewayProtocol.HTTPS
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
    startLine: 20
  package: com.microsoft.azure.management.network
  summary: <p>Static value Https for <xref href="com.microsoft.azure.management.network._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayProtocol HTTPS= new ApplicationGatewayProtocol("Https")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_protocol
- uid: com.microsoft.azure.management.network._application_gateway_protocol_1ac48f1948df04ec34e476d41161ca9a49
  id: _application_gateway_protocol_1ac48f1948df04ec34e476d41161ca9a49
  parent: com.microsoft.azure.management.network._application_gateway_protocol
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayProtocol.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayProtocol.java
    startLine: 34
  package: com.microsoft.azure.management.network
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 93de0ef9com.microsoft.azure.management.network._application_gateway_protocol
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.management.network._application_gateway_protocol
    name: ApplicationGatewayProtocol
    fullName: com.microsoft.azure.management.network.ApplicationGatewayProtocol
    href: com.microsoft.azure.management.network._application_gateway_protocol.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure.management.network._application_gateway_protocol
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_protocol.yml
  name: ApplicationGatewayProtocol
  fullName: com.microsoft.azure.management.network.ApplicationGatewayProtocol
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
