items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_subnet
  id: _with_subnet
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_subnet.withSubnet(String)
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_subnet.yml
  langs:
  - java
  name: NicIpConfiguration.DefinitionStages.WithSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithSubnet<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 150
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify subnet.</p>

    <p></p>
  syntax:
    content: public interface WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_subnet.withSubnet(String)
  id: withSubnet(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_subnet
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_subnet.yml
  langs:
  - java
  name: withSubnet(String name)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithSubnet< ParentT >.withSubnet(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 157
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Associate a subnet with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withSubnet(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the subnet name </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ipa6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ipa6da57ba
  spec.java:
  - uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip
    name: NicIpConfiguration.DefinitionStages.WithPrivateIp
    fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithPrivateIp
    href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip.yml
  - name: < ParentT >
    fullName: < ParentT >
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition.yml
  name: NicIpConfiguration.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of the network interface IP configuration definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends NicIpConfiguration.DefinitionStages.Blank< ParentT >,NicIpConfiguration.DefinitionStages.WithAttach< ParentT >,NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.DefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.DefinitionStages.WithPrivateIp< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip.yml
  name: NicIpConfiguration.DefinitionStages.WithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithPrivateIp<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify private IP address within a virtual network subnet.</p>

    <p></p>
  syntax:
    content: public interface WithPrivateIp<ParentT> extends HasPrivateIpAddress.DefinitionStages.WithPrivateIpAddress< WithAttach< ParentT > >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
