items:
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
  id: _with_parameters
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.withParameters(Object)
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.withParameters(String)
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.withParametersLink(String,String)
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.yml
  langs:
  - java
  name: Deployment.DefinitionStages.WithParameters
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithParameters
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 195
  package: com.microsoft.azure.management.resources
  summary: <p>A deployment definition allowing the parameters to be specified. </p>
  syntax:
    content: public interface WithParameters
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.withParameters(Object)
  id: withParameters(Object)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.yml
  langs:
  - java
  name: withParameters(Object parameters)
  fullName: WithMode com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithParameters.withParameters(Object parameters)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 202
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the parameters as a Java object.</p>

    <p></p>
  syntax:
    content: public WithMode withParameters(Object parameters)
    parameters:
    - id: parameters
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_mode
      description: <p>the next stage of the deployment definition </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.withParameters(String)
  id: withParameters(String)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.yml
  langs:
  - java
  name: withParameters(String parametersJson)
  fullName: WithMode com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithParameters.withParameters(String parametersJson)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 210
  package: com.microsoft.azure.management.resources
  summary: <p>Specifies the parameters as a JSON string. </p>
  syntax:
    content: public WithMode withParameters(String parametersJson)
    parameters:
    - id: parametersJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_mode
      description: <p>the next stage of the deployment definition </p>
  exceptions:
  - type: cbf33bbe
    description: <p>exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.withParametersLink(String,String)
  id: withParametersLink(String,String)
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_parameters.yml
  langs:
  - java
  name: withParametersLink(String uri, String contentVersion)
  fullName: WithMode com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithParameters.withParametersLink(String uri, String contentVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 219
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the parameters as a URL.</p>

    <p></p>
  syntax:
    content: public WithMode withParametersLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote parameters file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the parameters file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_mode
      description: <p>the next stage of the deployment definition </p>
references:
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources._deployment._definition
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition.yml
  name: Deployment.Definition
  fullName: com.microsoft.azure.management.resources.Deployment.Definition
  type: Interface
  summary: <p>Container interface for all the deployment definitions. </p>
  syntax:
    content: public interface Definition extends Deployment.DefinitionStages.Blank,Deployment.DefinitionStages.WithGroup,Deployment.DefinitionStages.WithTemplate,Deployment.DefinitionStages.WithParameters,Deployment.DefinitionStages.WithMode,Deployment.DefinitionStages.WithCreate
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_mode
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_mode.yml
  name: Deployment.DefinitionStages.WithMode
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithMode
  type: Interface
  summary: <p>A deployment definition allowing the deployment mode to be specified. </p>
  syntax:
    content: public interface WithMode
