items:
- uid: com.microsoft.azure.batch.protocol.models._network_configuration
  id: _network_configuration
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._network_configuration.subnetId()
  - com.microsoft.azure.batch.protocol.models._network_configuration.withSubnetId(String)
  href: com.microsoft.azure.batch.protocol.models._network_configuration.yml
  langs:
  - java
  name: NetworkConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.NetworkConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/NetworkConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/NetworkConfiguration.java
    startLine: 14
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>The network configuration for a pool. </p>
  syntax: &o1
    content: public class NetworkConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._network_configuration.subnetId()
  id: subnetId()
  parent: com.microsoft.azure.batch.protocol.models._network_configuration
  href: com.microsoft.azure.batch.protocol.models._network_configuration.yml
  langs:
  - java
  name: subnetId()
  fullName: String com.microsoft.azure.batch.protocol.models.NetworkConfiguration.subnetId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/NetworkConfiguration.java
    startLine: 29
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the subnetId value.</p>

    <p></p>
  syntax:
    content: public String subnetId()
    return:
      type: "26831127"
      description: <p>the subnetId value </p>
- uid: com.microsoft.azure.batch.protocol.models._network_configuration.withSubnetId(String)
  id: withSubnetId(String)
  parent: com.microsoft.azure.batch.protocol.models._network_configuration
  href: com.microsoft.azure.batch.protocol.models._network_configuration.yml
  langs:
  - java
  name: withSubnetId(String subnetId)
  fullName: NetworkConfiguration com.microsoft.azure.batch.protocol.models.NetworkConfiguration.withSubnetId(String subnetId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/NetworkConfiguration.java
    startLine: 39
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the subnetId value.</p>

    <p></p>
  syntax:
    content: public NetworkConfiguration withSubnetId(String subnetId)
    parameters:
    - id: subnetId
      type: "26831127"
      description: <p>the subnetId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._network_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._network_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.batch.protocol.models._network_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._network_configuration.yml
  name: NetworkConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.NetworkConfiguration
  type: Class
  summary: <p>The network configuration for a pool. </p>
  syntax: *o1
