items:
- uid: com.microsoft.azure.management.batch._application._update_stages
  id: _update_stages
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update_stages.yml
  langs:
  - java
  name: Application.UpdateStages
  fullName: com.microsoft.azure.management.batch.Application.UpdateStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 187
  package: com.microsoft.azure.management.batch
  summary: <p>Grouping of application update stages. </p>
  syntax:
    content: public interface UpdateStages
references: []
