items:
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  id: _application_gatewafab6a4ebc0d248c30b5056839c9775a3
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.data()
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.etag()
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.name()
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.provisioningState()
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withData(String)
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withEtag(String)
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withName(String)
  - com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withProvisioningState(String)
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: ApplicationGatewayAuthenticationCertificateInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 18
  package: com.microsoft.azure.management.network.implementation
  summary: <p>Authentication certificates of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayAuthenticationCertificateInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.data()
  id: data()
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: data()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.data()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 48
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the data value.</p>

    <p></p>
  syntax:
    content: public String data()
    return:
      type: "26831127"
      description: <p>the data value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 108
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 88
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 68
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withData(String)
  id: withData(String)
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: withData(String data)
  fullName: ApplicationGatewayAuthenticationCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.withData(String data)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 58
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the data value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayAuthenticationCertificateInner withData(String data)
    parameters:
    - id: data
      type: "26831127"
      description: <p>the data value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayAuthenticationCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 118
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayAuthenticationCertificateInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayAuthenticationCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 98
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayAuthenticationCertificateInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayAuthenticationCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayAuthenticationCertificateInner.java
    startLine: 78
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayAuthenticationCertificateInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gatewafab6a4ebc0d248c30b5056839c9775a3.yml
  name: ApplicationGatewayAuthenticationCertificateInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayAuthenticationCertificateInner
  type: Class
  summary: <p>Authentication certificates of application gateway. </p>
  syntax: *o1
