items:
- uid: com.microsoft.azure.management.resources._deployment_mode
  id: _deployment_mode
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment_mode_1a022dc3167a8bdc95e3ede98ecd61c0bd
  - com.microsoft.azure.management.resources._deployment_mode_1aad85224a3286fea392b2493b09c6b085
  - com.microsoft.azure.management.resources._deployment_mode_1a170b4a19d5657ab233f747ff3fd08f99
  - com.microsoft.azure.management.resources._deployment_mode_1aaf8319352c908b837eac519e0df950bf
  - com.microsoft.azure.management.resources._deployment_mode_1a8bd48fcb94f2ad57a8381d03865f72be
  href: com.microsoft.azure.management.resources._deployment_mode.yml
  langs:
  - java
  name: DeploymentMode
  fullName: com.microsoft.azure.management.resources.DeploymentMode
  type: Enum
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentMode.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentMode.java
    startLine: 16
  package: com.microsoft.azure.management.resources
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.resources._deployment_mode" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public enum DeploymentMode
  inheritance:
  - java.lang.Object
  - java.lang.Enum<DeploymentMode>
- uid: com.microsoft.azure.management.resources._deployment_mode_1a022dc3167a8bdc95e3ede98ecd61c0bd
  id: _deployment_mode_1a022dc3167a8bdc95e3ede98ecd61c0bd
  parent: com.microsoft.azure.management.resources._deployment_mode
  href: com.microsoft.azure.management.resources._deployment_mode.yml
  langs:
  - java
  name: COMPLETE
  fullName: com.microsoft.azure.management.resources.DeploymentMode.COMPLETE
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentMode.java
    startLine: 21
  package: com.microsoft.azure.management.resources
  summary: <p>Enum value Complete. </p>
  syntax:
    content: public COMPLETE=("Complete")
- uid: com.microsoft.azure.management.resources._deployment_mode_1aad85224a3286fea392b2493b09c6b085
  id: _deployment_mode_1aad85224a3286fea392b2493b09c6b085
  parent: com.microsoft.azure.management.resources._deployment_mode
  href: com.microsoft.azure.management.resources._deployment_mode.yml
  langs:
  - java
  name: DeploymentMode(String value)
  fullName: com.microsoft.azure.management.resources.DeploymentMode.DeploymentMode(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentMode.java
    startLine: 26
  package: com.microsoft.azure.management.resources
  syntax:
    content: public DeploymentMode(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.azure.management.resources._deployment_mode_1a170b4a19d5657ab233f747ff3fd08f99
  id: _deployment_mode_1a170b4a19d5657ab233f747ff3fd08f99
  parent: com.microsoft.azure.management.resources._deployment_mode
  href: com.microsoft.azure.management.resources._deployment_mode.yml
  langs:
  - java
  name: fromString(String value)
  fullName: static DeploymentMode com.microsoft.azure.management.resources.DeploymentMode.fromString(String value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentMode.java
    startLine: 37
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Parses a serialized value to a <xref href="com.microsoft.azure.management.resources._deployment_mode" data-throw-if-not-resolved="false"></xref> instance.</p>

    <p></p>
  syntax:
    content: public static DeploymentMode fromString(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the serialized value to parse. </p>
    return:
      type: com.microsoft.azure.management.resources._deployment_mode
      description: <p>the parsed <xref href="com.microsoft.azure.management.resources._deployment_mode" data-throw-if-not-resolved="false"></xref> object, or null if unable to parse. </p>
- uid: com.microsoft.azure.management.resources._deployment_mode_1aaf8319352c908b837eac519e0df950bf
  id: _deployment_mode_1aaf8319352c908b837eac519e0df950bf
  parent: com.microsoft.azure.management.resources._deployment_mode
  href: com.microsoft.azure.management.resources._deployment_mode.yml
  langs:
  - java
  name: INCREMENTAL
  fullName: com.microsoft.azure.management.resources.DeploymentMode.INCREMENTAL
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentMode.java
    startLine: 18
  package: com.microsoft.azure.management.resources
  summary: <p>Enum value Incremental. </p>
  syntax:
    content: public INCREMENTAL=("Incremental")
- uid: com.microsoft.azure.management.resources._deployment_mode_1a8bd48fcb94f2ad57a8381d03865f72be
  id: _deployment_mode_1a8bd48fcb94f2ad57a8381d03865f72be
  parent: com.microsoft.azure.management.resources._deployment_mode
  href: com.microsoft.azure.management.resources._deployment_mode.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.resources.DeploymentMode.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentMode.java
    startLine: 49
  package: com.microsoft.azure.management.resources
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources._deployment_mode
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment_mode.yml
  name: DeploymentMode
  fullName: com.microsoft.azure.management.resources.DeploymentMode
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.resources._deployment_mode" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
