items:
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options
  id: _application_list_next_options
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_list_next_options_1aed15859da870ee52ff370e5027849d33
  - com.microsoft.azure.batch.protocol.models._application_list_next_options_1a0bfbafcc5b08ff2e39918df7bd314690
  - com.microsoft.azure.batch.protocol.models._application_list_next_options_1a358db1856579867ef619d2d314cc266f
  - com.microsoft.azure.batch.protocol.models._application_list_next_options_1a232986d997759da77542e30f38567312
  - com.microsoft.azure.batch.protocol.models._application_list_next_options_1a80caa361b705ba7bbbaca4ee8a8f2d9f
  - com.microsoft.azure.batch.protocol.models._application_list_next_options_1aebae6098c64887fd5ba169c38cf42bd5
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  langs:
  - java
  name: ApplicationListNextOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Additional parameters for the ListNext operation. </p>
  syntax: &o1
    content: public class ApplicationListNextOptions
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options_1aed15859da870ee52ff370e5027849d33
  id: _application_list_next_options_1aed15859da870ee52ff370e5027849d33
  parent: com.microsoft.azure.batch.protocol.models._application_list_next_options
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
    startLine: 45
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options_1a0bfbafcc5b08ff2e39918df7bd314690
  id: _application_list_next_options_1a0bfbafcc5b08ff2e39918df7bd314690
  parent: com.microsoft.azure.batch.protocol.models._application_list_next_options
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  langs:
  - java
  name: ocpDate()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions.ocpDate()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
    startLine: 85
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the ocpDate value.</p>

    <p></p>
  syntax:
    content: public DateTime ocpDate()
    return:
      type: 230df18c
      description: <p>the ocpDate value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options_1a358db1856579867ef619d2d314cc266f
  id: _application_list_next_options_1a358db1856579867ef619d2d314cc266f
  parent: com.microsoft.azure.batch.protocol.models._application_list_next_options
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  langs:
  - java
  name: returnClientRequestId()
  fullName: Boolean com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions.returnClientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
    startLine: 65
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public Boolean returnClientRequestId()
    return:
      type: 866c2227
      description: <p>the returnClientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options_1a232986d997759da77542e30f38567312
  id: _application_list_next_options_1a232986d997759da77542e30f38567312
  parent: com.microsoft.azure.batch.protocol.models._application_list_next_options
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ApplicationListNextOptions com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
    startLine: 55
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationListNextOptions withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_next_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_next_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options_1a80caa361b705ba7bbbaca4ee8a8f2d9f
  id: _application_list_next_options_1a80caa361b705ba7bbbaca4ee8a8f2d9f
  parent: com.microsoft.azure.batch.protocol.models._application_list_next_options
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  langs:
  - java
  name: withOcpDate(DateTime ocpDate)
  fullName: ApplicationListNextOptions com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions.withOcpDate(DateTime ocpDate)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
    startLine: 98
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the ocpDate value.</p>

    <p></p>
  syntax:
    content: public ApplicationListNextOptions withOcpDate(DateTime ocpDate)
    parameters:
    - id: ocpDate
      type: 230df18c
      description: <p>the ocpDate value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_next_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_next_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options_1aebae6098c64887fd5ba169c38cf42bd5
  id: _application_list_next_options_1aebae6098c64887fd5ba169c38cf42bd5
  parent: com.microsoft.azure.batch.protocol.models._application_list_next_options
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  langs:
  - java
  name: withReturnClientRequestId(Boolean returnClientRequestId)
  fullName: ApplicationListNextOptions com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions.withReturnClientRequestId(Boolean returnClientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListNextOptions.java
    startLine: 75
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationListNextOptions withReturnClientRequestId(Boolean returnClientRequestId)
    parameters:
    - id: returnClientRequestId
      type: 866c2227
      description: <p>the returnClientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_next_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_next_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.rest._date_time_rfc1123
  parent: com.microsoft.rest
  href: com.microsoft.rest._date_time_rfc1123.yml
  name: DateTimeRfc1123
  fullName: com.microsoft.rest.DateTimeRfc1123
  type: Class
  summary: <p>Simple wrapper over joda.time.DateTime used for specifying RFC1123 format during serialization/deserialization. </p>
  syntax:
    content: public class DateTimeRfc1123
- uid: com.microsoft.azure.batch.protocol.models._application_list_next_options
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_list_next_options.yml
  name: ApplicationListNextOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationListNextOptions
  type: Class
  summary: <p>Additional parameters for the ListNext operation. </p>
  syntax: *o1
