items:
- uid: com.microsoft.azure.management.network._application_gateway_sku_name
  id: _application_gateway_sku_name
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a1dd7dce0a15b748bb3c24ba7e15c7089
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a0c39019c0eb203d95744e4664e723226
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a13d9cd35e89a61b8ea88ae907701498b
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a9e08fca785765dd703e3b822e6eae70c
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a4b426b41dd0351f7e49ff27c2bfb16e5
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a98004eff02b4fe3954d2c358acf59bf9
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a47d6bb0fd7e29bbaa2aea37995676516
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: ApplicationGatewaySkuName
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewaySkuName
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a1dd7dce0a15b748bb3c24ba7e15c7089
  id: _application_gateway_sku_name_1a1dd7dce0a15b748bb3c24ba7e15c7089
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: ApplicationGatewaySkuName(String value)
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName.ApplicationGatewaySkuName(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 31
  package: com.microsoft.azure.management.network
  summary: <p>Creates a custom value for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public ApplicationGatewaySkuName(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the custom value </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a0c39019c0eb203d95744e4664e723226
  id: _application_gateway_sku_name_1a0c39019c0eb203d95744e4664e723226
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: equals(Object obj)
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewaySkuName.equals(Object obj)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 47
  package: com.microsoft.azure.management.network
  syntax:
    content: public boolean equals(Object obj)
    parameters:
    - id: obj
      type: "79317049"
    return:
      type: 4fc6e284
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a13d9cd35e89a61b8ea88ae907701498b
  id: _application_gateway_sku_name_1a13d9cd35e89a61b8ea88ae907701498b
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: hashCode()
  fullName: int com.microsoft.azure.management.network.ApplicationGatewaySkuName.hashCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 42
  package: com.microsoft.azure.management.network
  syntax:
    content: public int hashCode()
    return:
      type: f75371fa
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a9e08fca785765dd703e3b822e6eae70c
  id: _application_gateway_sku_name_1a9e08fca785765dd703e3b822e6eae70c
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: STANDARD_LARGE
  fullName: final ApplicationGatewaySkuName com.microsoft.azure.management.network.ApplicationGatewaySkuName.STANDARD_LARGE
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 23
  package: com.microsoft.azure.management.network
  summary: <p>Static value Standard_Large for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewaySkuName STANDARD_LARGE= new ApplicationGatewaySkuName("Standard_Large")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_sku_name
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a4b426b41dd0351f7e49ff27c2bfb16e5
  id: _application_gateway_sku_name_1a4b426b41dd0351f7e49ff27c2bfb16e5
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: STANDARD_MEDIUM
  fullName: final ApplicationGatewaySkuName com.microsoft.azure.management.network.ApplicationGatewaySkuName.STANDARD_MEDIUM
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 20
  package: com.microsoft.azure.management.network
  summary: <p>Static value Standard_Medium for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewaySkuName STANDARD_MEDIUM= new ApplicationGatewaySkuName("Standard_Medium")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_sku_name
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a98004eff02b4fe3954d2c358acf59bf9
  id: _application_gateway_sku_name_1a98004eff02b4fe3954d2c358acf59bf9
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: STANDARD_SMALL
  fullName: final ApplicationGatewaySkuName com.microsoft.azure.management.network.ApplicationGatewaySkuName.STANDARD_SMALL
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>Static value Standard_Small for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewaySkuName STANDARD_SMALL= new ApplicationGatewaySkuName("Standard_Small")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_sku_name
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a47d6bb0fd7e29bbaa2aea37995676516
  id: _application_gateway_sku_name_1a47d6bb0fd7e29bbaa2aea37995676516
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySkuName.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 37
  package: com.microsoft.azure.management.network
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 93de0ef9com.microsoft.azure.management.network._application_gateway_sku_name
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.management.network._application_gateway_sku_name
    name: ApplicationGatewaySkuName
    fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
    href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure.management.network._application_gateway_sku_name
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  name: ApplicationGatewaySkuName
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
