items:
- uid: com.microsoft.azure.batch.protocol.models._windows_configuration
  id: _windows_configuration
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._windows_configuration_1a54b582c6be9ecb03c24a38d88e7431b8
  - com.microsoft.azure.batch.protocol.models._windows_configuration_1af5068b972b3ca4cfe56b6de95d260feb
  href: com.microsoft.azure.batch.protocol.models._windows_configuration.yml
  langs:
  - java
  name: WindowsConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.WindowsConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/WindowsConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/WindowsConfiguration.java
    startLine: 14
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Windows operating system settings to apply to the virtual machine. </p>
  syntax: &o1
    content: public class WindowsConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._windows_configuration_1a54b582c6be9ecb03c24a38d88e7431b8
  id: _windows_configuration_1a54b582c6be9ecb03c24a38d88e7431b8
  parent: com.microsoft.azure.batch.protocol.models._windows_configuration
  href: com.microsoft.azure.batch.protocol.models._windows_configuration.yml
  langs:
  - java
  name: enableAutomaticUpdates()
  fullName: Boolean com.microsoft.azure.batch.protocol.models.WindowsConfiguration.enableAutomaticUpdates()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/WindowsConfiguration.java
    startLine: 26
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the enableAutomaticUpdates value.</p>

    <p></p>
  syntax:
    content: public Boolean enableAutomaticUpdates()
    return:
      type: 866c2227
      description: <p>the enableAutomaticUpdates value </p>
- uid: com.microsoft.azure.batch.protocol.models._windows_configuration_1af5068b972b3ca4cfe56b6de95d260feb
  id: _windows_configuration_1af5068b972b3ca4cfe56b6de95d260feb
  parent: com.microsoft.azure.batch.protocol.models._windows_configuration
  href: com.microsoft.azure.batch.protocol.models._windows_configuration.yml
  langs:
  - java
  name: withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
  fullName: WindowsConfiguration com.microsoft.azure.batch.protocol.models.WindowsConfiguration.withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/WindowsConfiguration.java
    startLine: 36
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the enableAutomaticUpdates value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
    parameters:
    - id: enableAutomaticUpdates
      type: 866c2227
      description: <p>the enableAutomaticUpdates value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.batch.protocol.models._windows_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._windows_configuration.yml
  name: WindowsConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.WindowsConfiguration
  type: Class
  summary: <p>Windows operating system settings to apply to the virtual machine. </p>
  syntax: *o1
