items:
- uid: com.microsoft.azure.management.website._file_system_http_logs_config
  id: _file_system_http_logs_config
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._file_system_http_logs_config_1ae300d017517aedeaf653cf92e57a4c38
  - com.microsoft.azure.management.website._file_system_http_logs_config_1a364f5bc9b1e7b24ce2e22c88b3331e94
  - com.microsoft.azure.management.website._file_system_http_logs_config_1a9a6eb0c6d65ef699afc358135594dff6
  - com.microsoft.azure.management.website._file_system_http_logs_config_1adab4aab01d1fe04ac43433ffdda9ffa3
  - com.microsoft.azure.management.website._file_system_http_logs_config_1a5b46d3938e2846cb00f53fb3bdcb6695
  - com.microsoft.azure.management.website._file_system_http_logs_config_1a33a7432473070f2bab604363facdcd37
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  langs:
  - java
  name: FileSystemHttpLogsConfig
  fullName: com.microsoft.azure.management.website.FileSystemHttpLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
    startLine: 14
  package: com.microsoft.azure.management.website
  summary: <p>Http logs to file system configuration. </p>
  syntax: &o1
    content: public class FileSystemHttpLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._file_system_http_logs_config_1ae300d017517aedeaf653cf92e57a4c38
  id: _file_system_http_logs_config_1ae300d017517aedeaf653cf92e57a4c38
  parent: com.microsoft.azure.management.website._file_system_http_logs_config
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  langs:
  - java
  name: enabled()
  fullName: Boolean com.microsoft.azure.management.website.FileSystemHttpLogsConfig.enabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
    startLine: 80
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the enabled value.</p>

    <p></p>
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.website._file_system_http_logs_config_1a364f5bc9b1e7b24ce2e22c88b3331e94
  id: _file_system_http_logs_config_1a364f5bc9b1e7b24ce2e22c88b3331e94
  parent: com.microsoft.azure.management.website._file_system_http_logs_config
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  langs:
  - java
  name: retentionInDays()
  fullName: Integer com.microsoft.azure.management.website.FileSystemHttpLogsConfig.retentionInDays()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
    startLine: 60
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.website._file_system_http_logs_config_1a9a6eb0c6d65ef699afc358135594dff6
  id: _file_system_http_logs_config_1a9a6eb0c6d65ef699afc358135594dff6
  parent: com.microsoft.azure.management.website._file_system_http_logs_config
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  langs:
  - java
  name: retentionInMb()
  fullName: Integer com.microsoft.azure.management.website.FileSystemHttpLogsConfig.retentionInMb()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
    startLine: 40
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the retentionInMb value.</p>

    <p></p>
  syntax:
    content: public Integer retentionInMb()
    return:
      type: 08effaa0
      description: <p>the retentionInMb value </p>
- uid: com.microsoft.azure.management.website._file_system_http_logs_config_1adab4aab01d1fe04ac43433ffdda9ffa3
  id: _file_system_http_logs_config_1adab4aab01d1fe04ac43433ffdda9ffa3
  parent: com.microsoft.azure.management.website._file_system_http_logs_config
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  fullName: FileSystemHttpLogsConfig com.microsoft.azure.management.website.FileSystemHttpLogsConfig.withEnabled(Boolean enabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
    startLine: 90
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the enabled value.</p>

    <p></p>
  syntax:
    content: public FileSystemHttpLogsConfig withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.website._file_system_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._file_system_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._file_system_http_logs_config_1a5b46d3938e2846cb00f53fb3bdcb6695
  id: _file_system_http_logs_config_1a5b46d3938e2846cb00f53fb3bdcb6695
  parent: com.microsoft.azure.management.website._file_system_http_logs_config
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  fullName: FileSystemHttpLogsConfig com.microsoft.azure.management.website.FileSystemHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
    startLine: 70
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public FileSystemHttpLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.website._file_system_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._file_system_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._file_system_http_logs_config_1a33a7432473070f2bab604363facdcd37
  id: _file_system_http_logs_config_1a33a7432473070f2bab604363facdcd37
  parent: com.microsoft.azure.management.website._file_system_http_logs_config
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  langs:
  - java
  name: withRetentionInMb(Integer retentionInMb)
  fullName: FileSystemHttpLogsConfig com.microsoft.azure.management.website.FileSystemHttpLogsConfig.withRetentionInMb(Integer retentionInMb)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/FileSystemHttpLogsConfig.java
    startLine: 50
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the retentionInMb value.</p>

    <p></p>
  syntax:
    content: public FileSystemHttpLogsConfig withRetentionInMb(Integer retentionInMb)
    parameters:
    - id: retentionInMb
      type: 08effaa0
      description: <p>the retentionInMb value to set </p>
    return:
      type: com.microsoft.azure.management.website._file_system_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._file_system_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.website._file_system_http_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._file_system_http_logs_config.yml
  name: FileSystemHttpLogsConfig
  fullName: com.microsoft.azure.management.website.FileSystemHttpLogsConfig
  type: Class
  summary: <p>Http logs to file system configuration. </p>
  syntax: *o1
