items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089
  id: _update_b03bb382568b5bfa54cd6309635c9089
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 374
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The final stage of network interface IP configuration. </p>

    <p>At this stage, any remaining optional settings can be specified, or the network interface IP configuration definition can be attached to the parent network interface definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable< ParentT >.InUpdate,NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withExistingPublicIpAddress(PublicIpAddress)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withNewPublicIpAddress(Creatable< PublicIpAddress >)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withNewPublicIpAddress()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withNewPublicIpAddress(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.InUpdate< ParentT >.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withExistingPublicIpAddress(PublicIpAddress)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.yml
  name: withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >.withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithAttach< ParentT > withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
    parameters:
    - id: publicIpAddress
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>an existing public IP address </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089a6da57ba
      description: <p>the next stage of the IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withNewPublicIpAddress(Creatable< PublicIpAddress >)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.yml
  name: withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >.withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  type: Method
  summary: >-
    <p>Create a new public IP address to associate with the network interface IP configuration, based on the provided definition.</p>

    <p></p>
  syntax:
    content: public WithAttach< ParentT > withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
    parameters:
    - id: creatable
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._public_ip_address9ec3e006
      description: <p>a creatable definition for a new public IP </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089a6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withNewPublicIpAddress()
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.yml
  name: withNewPublicIpAddress()
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >.withNewPublicIpAddress()
  type: Method
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource and associate it with with the network interface IP configuration. </p>

    <p>The internal name and DNS label for the public IP address will be derived from the network interface name.</p>

    <p></p>
  syntax:
    content: public WithAttach< ParentT > withNewPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089a6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.withNewPublicIpAddress(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.yml
  name: withNewPublicIpAddress(String leafDnsLabel)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >.withNewPublicIpAddress(String leafDnsLabel)
  type: Method
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource, with the specified DNS label and associate it with the network interface IP configuration. </p>

    <p>The internal name for the public IP address will be derived from the DNS label.</p>

    <p></p>
  syntax:
    content: public WithAttach< ParentT > withNewPublicIpAddress(String leafDnsLabel)
    parameters:
    - id: leafDnsLabel
      type: "26831127"
      description: <p>the leaf domain label </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089a6da57ba
      description: <p>tthe next stage of the IP configuration definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: Attachable.InUpdate<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdate<ParentT>
  type: Interface
  summary: <p>The final stage of the child object definition, as which it can be attached to the parent. </p>
  syntax:
    content: public interface InUpdate<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to associate it with a public IP address.</p>

    <p></p>
  syntax:
    content: public interface WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_definition.yml
  name: NicIpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of a network interface IP configuration definition as part of a network interface update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends NicIpConfiguration.UpdateDefinitionStages.Blank< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithAttach< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
