items:
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_attach
  id: _with_attach
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._application._definition_stages._with_attach.withAllowUpdates(boolean)
  - com.microsoft.azure.management.batch._application._definition_stages._with_attach.withDisplayName(String)
  href: com.microsoft.azure.management.batch._application._definition_stages._with_attach.yml
  langs:
  - java
  name: Application.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.DefinitionStages.WithAttach<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 93
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>The final stage of the application definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the application definition can be attached to the parent batch account definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable< ParentT >.InDefinition,Application.DefinitionStages.WithApplicationPackage< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  - com.microsoft.azure.management.batch._application._definition_stages._with_application_package.defineNewApplicationPackage(String)
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_attach.withAllowUpdates(boolean)
  id: withAllowUpdates(boolean)
  parent: com.microsoft.azure.management.batch._application._definition_stages._with_attach
  href: com.microsoft.azure.management.batch._application._definition_stages._with_attach.yml
  langs:
  - java
  name: withAllowUpdates(boolean allowUpdates)
  fullName: DefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.DefinitionStages.WithAttach< ParentT >.withAllowUpdates(boolean allowUpdates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 102
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Allow automatic application updates.</p>

    <p></p>
  syntax:
    content: public DefinitionStages.WithAttach< ParentT > withAllowUpdates(boolean allowUpdates)
    parameters:
    - id: allowUpdates
      type: 4fc6e284
      description: <p>true to allow the automatic updates of application, otherwise false </p>
    return:
      type: 350be077
      description: <p>parent batch account definition. </p>
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_attach.withDisplayName(String)
  id: withDisplayName(String)
  parent: com.microsoft.azure.management.batch._application._definition_stages._with_attach
  href: com.microsoft.azure.management.batch._application._definition_stages._with_attach.yml
  langs:
  - java
  name: withDisplayName(String displayName)
  fullName: DefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.DefinitionStages.WithAttach< ParentT >.withDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 110
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Specifies the display name for the application.</p>

    <p></p>
  syntax:
    content: public DefinitionStages.WithAttach< ParentT > withDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
      description: <p>the displayName value to set </p>
    return:
      type: 350be077
      description: <p>parent batch account definition. </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 350be077
  spec.java:
  - name: DefinitionStages.WithAttach< ParentT >
    fullName: DefinitionStages.WithAttach< ParentT >
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.InDefinition< ParentT >.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_application_package.defineNewApplicationPackage(String)
  parent: com.microsoft.azure.management.batch._application._definition_stages._with_application_package
  href: com.microsoft.azure.management.batch._application._definition_stages._with_application_package.yml
  name: defineNewApplicationPackage(String applicationPackageName)
  fullName: DefinitionStages.WithAttach<ParentT> com.microsoft.azure.management.batch.Application.DefinitionStages.WithApplicationPackage< ParentT >.defineNewApplicationPackage(String applicationPackageName)
  type: Method
  summary: >-
    <p>First stage to create new application package in Batch account application.</p>

    <p></p>
  syntax:
    content: public DefinitionStages.WithAttach< ParentT > defineNewApplicationPackage(String applicationPackageName)
    parameters:
    - id: applicationPackageName
      type: "26831127"
      description: <p>the version of the application </p>
    return:
      type: 350be077
      description: <p>next stage to create the application. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: Attachable.InDefinition<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition<ParentT>
  type: Interface
  summary: <p>The final stage of the child object definition, as which it can be attached to the parent. </p>
  syntax:
    content: public interface InDefinition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition </p>
- uid: com.microsoft.azure.management.batch._application._definition_stages._with_application_package
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._definition_stages._with_application_package.yml
  name: Application.DefinitionStages.WithApplicationPackage<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.DefinitionStages.WithApplicationPackage<ParentT>
  type: Interface
  summary: >-
    <p>A application definition to allow creation of application package.</p>

    <p></p>
  syntax:
    content: public interface WithApplicationPackage<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.batch._application._definition
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._definition.yml
  name: Application.Definition<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.Definition<ParentT>
  type: Interface
  summary: >-
    <p>The entirety of a application definition as a part of parent definition.</p>

    <p></p>
  syntax:
    content: public interface Definition<ParentT> extends Application.DefinitionStages.Blank< ParentT >,Application.DefinitionStages.WithAttach< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.batch._application._definition_stages._blank
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._definition_stages._blank.yml
  name: Application.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.batch.Application.DefinitionStages.Blank<ParentT>
  type: Interface
  summary: >-
    <p>The first stage of a batch account application definition.</p>

    <p></p>
  syntax:
    content: public interface Blank<ParentT> extends Application.DefinitionStages.WithAttach< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
