items:
- uid: com.microsoft.azure._azure._configurable
  id: _configurable
  parent: com.microsoft.azure
  children:
  - com.microsoft.azure._azure._configurable.authenticate(AzureTokenCredentials)
  - com.microsoft.azure._azure._configurable.authenticate(File)
  - com.microsoft.azure._azure._configurable.authenticate(ServiceClientCredentials,String)
  href: com.microsoft.azure._azure._configurable.yml
  langs:
  - java
  name: Azure.Configurable
  fullName: com.microsoft.azure.Azure.Configurable
  type: Interface
  source:
    remote: &o0
      path: azure/src/main/java/com/microsoft/azure/Azure.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure/src/main/java/com/microsoft/azure/Azure.java
    startLine: 133
  package: com.microsoft.azure
  summary: <p>The interface allowing configurations to be made on the client. </p>
  syntax:
    content: public interface Configurable extends AzureConfigurable< Configurable >
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withCallbackExecutor(Executor)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withConnectionTimeout(long,TimeUnit)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withInterceptor(Interceptor)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withLogLevel(HttpLoggingInterceptor.Level)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withMaxIdleConnections(int)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withProxy(Proxy)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withReadTimeout(long,TimeUnit)
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withUserAgent(String)
- uid: com.microsoft.azure._azure._configurable.authenticate(AzureTokenCredentials)
  id: authenticate(AzureTokenCredentials)
  parent: com.microsoft.azure._azure._configurable
  href: com.microsoft.azure._azure._configurable.yml
  langs:
  - java
  name: authenticate(AzureTokenCredentials credentials)
  fullName: Authenticated com.microsoft.azure.Azure.Configurable.authenticate(AzureTokenCredentials credentials)
  type: Method
  source:
    remote: *o0
    path: azure/src/main/java/com/microsoft/azure/Azure.java
    startLine: 149
  package: com.microsoft.azure
  summary: >-
    <p>Authenticates API access based on the provided credentials.</p>

    <p></p>
  syntax:
    content: public Authenticated authenticate(AzureTokenCredentials credentials)
    parameters:
    - id: credentials
      type: com.microsoft.azure.credentials._azure_token_credentials
      description: <p>The credentials to authenticate API access with </p>
    return:
      type: com.microsoft.azure._azure._authenticated
      description: <p>the authenticated <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> client </p>
- uid: com.microsoft.azure._azure._configurable.authenticate(File)
  id: authenticate(File)
  parent: com.microsoft.azure._azure._configurable
  href: com.microsoft.azure._azure._configurable.yml
  langs:
  - java
  name: authenticate(File credentialsFile)
  fullName: Authenticated com.microsoft.azure.Azure.Configurable.authenticate(File credentialsFile)
  type: Method
  source:
    remote: *o0
    path: azure/src/main/java/com/microsoft/azure/Azure.java
    startLine: 159
  package: com.microsoft.azure
  summary: >-
    <p>Authenticates API access using a properties file containing the required credentials.</p>

    <p></p>
  syntax:
    content: public Authenticated authenticate(File credentialsFile)
    parameters:
    - id: credentialsFile
      type: 8291270b
      description: <p>the file containing the credentials in the standard Java properties file format following the same schema as <xref href="com.microsoft.azure._azure.authenticate(File)" data-throw-if-not-resolved="false"></xref>.</p>
    return:
      type: com.microsoft.azure._azure._authenticated
      description: >-
        <p>

          <xref href="com.microsoft.azure._azure._authenticated" data-throw-if-not-resolved="false"></xref>

          <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> client </p>
  exceptions:
  - type: cbf33bbe
    description: <p>exceptions thrown from file access </p>
- uid: com.microsoft.azure._azure._configurable.authenticate(ServiceClientCredentials,String)
  id: authenticate(ServiceClientCredentials,String)
  parent: com.microsoft.azure._azure._configurable
  href: com.microsoft.azure._azure._configurable.yml
  langs:
  - java
  name: authenticate(ServiceClientCredentials credentials, String tenantId)
  fullName: Authenticated com.microsoft.azure.Azure.Configurable.authenticate(ServiceClientCredentials credentials, String tenantId)
  type: Method
  source:
    remote: *o0
    path: azure/src/main/java/com/microsoft/azure/Azure.java
    startLine: 141
  package: com.microsoft.azure
  summary: >-
    <p>Authenticates API access based on the provided credentials.</p>

    <p></p>
  syntax:
    content: public Authenticated authenticate(ServiceClientCredentials credentials, String tenantId)
    parameters:
    - id: credentials
      type: com.microsoft.rest.credentials._service_client_credentials
      description: <p>The credentials to authenticate API access with </p>
    - id: tenantId
      type: "26831127"
      description: <p>the tenantId in Active Directory </p>
    return:
      type: com.microsoft.azure._azure._authenticated
      description: <p>the authenticated <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> client </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: 8291270b
  spec.java:
  - name: File
    fullName: File
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withCallbackExecutor(Executor)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withCallbackExecutor(Executor executor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withCallbackExecutor(Executor executor)
  type: Method
  summary: >-
    <p>Sets the executor for async callbacks to run on.</p>

    <p></p>
  syntax:
    content: public T withCallbackExecutor(Executor executor)
    parameters:
    - id: executor
      type: 6f968643
      description: <p>the executor to execute the callbacks. </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withConnectionTimeout(long,TimeUnit)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withConnectionTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withConnectionTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the connection timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withConnectionTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withInterceptor(Interceptor)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withInterceptor(Interceptor interceptor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withInterceptor(Interceptor interceptor)
  type: Method
  summary: >-
    <p>Plug in an interceptor into the HTTP pipeline.</p>

    <p></p>
  syntax:
    content: public T withInterceptor(Interceptor interceptor)
    parameters:
    - id: interceptor
      type: 910a0506
      description: <p>the interceptor to plug in </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withLogLevel(HttpLoggingInterceptor.Level)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withLogLevel(HttpLoggingInterceptor.Level level)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withLogLevel(HttpLoggingInterceptor.Level level)
  type: Method
  summary: >-
    <p>Set the logging level on the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withLogLevel(HttpLoggingInterceptor.Level level)
    parameters:
    - id: level
      type: b12c7a8c
      description: <p>the OkHttp logging level </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withMaxIdleConnections(int)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withMaxIdleConnections(int maxIdleConnections)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withMaxIdleConnections(int maxIdleConnections)
  type: Method
  summary: >-
    <p>Set the maximum idle connections for the HTTP client. Default is 5.</p>

    <p></p>
  syntax:
    content: public T withMaxIdleConnections(int maxIdleConnections)
    parameters:
    - id: maxIdleConnections
      type: f75371fa
      description: <p>the maximum idle connections </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withProxy(Proxy)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withProxy(Proxy proxy)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withProxy(Proxy proxy)
  type: Method
  summary: >-
    <p>Sets the proxy for the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withProxy(Proxy proxy)
    parameters:
    - id: proxy
      type: abc26ef5
      description: <p>the proxy to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withReadTimeout(long,TimeUnit)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withReadTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withReadTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the read timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withReadTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.withUserAgent(String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withUserAgent(String userAgent)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withUserAgent(String userAgent)
  type: Method
  summary: >-
    <p>Specify the user agent header.</p>

    <p></p>
  syntax:
    content: public T withUserAgent(String userAgent)
    parameters:
    - id: userAgent
      type: "26831127"
      description: <p>the user agent to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  parent: com.microsoft.azure.management.resources.fluentcore.arm
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: AzureConfigurable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T>
  type: Interface
  summary: >-
    <p>The base interface for allowing configurations to be made on the HTTP client.</p>

    <p></p>
  syntax:
    content: public interface AzureConfigurable<T extends AzureConfigurable< T>>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the actual type of the interface extending this interface </p>
- uid: com.microsoft.azure._azure._authenticated
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure._authenticated.yml
  name: Azure.Authenticated
  fullName: com.microsoft.azure.Azure.Authenticated
  type: Interface
  summary: >-
    <p>Provides authenticated access to a subset of <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> APIs that do not require a specific subscription. </p>

    <p>To access the subscription-specific APIs, use <xref href="com.microsoft.azure._azure._authenticated.withSubscription(String)" data-throw-if-not-resolved="false"></xref>, or <xref href="com.microsoft.azure._azure._authenticated.withDefaultSubscription()" data-throw-if-not-resolved="false"></xref> if a default subscription has already been previously specified (for example, in a previously specified authentication file). </p>
  syntax:
    content: public interface Authenticated
- uid: com.microsoft.rest.credentials._service_client_credentials
  parent: com.microsoft.rest.credentials
  href: com.microsoft.rest.credentials._service_client_credentials.yml
  name: ServiceClientCredentials
  fullName: com.microsoft.rest.credentials.ServiceClientCredentials
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.rest.credentials._service_client_credentials" data-throw-if-not-resolved="false"></xref> is the abstraction for credentials used by ServiceClients accessing REST services. </p>
  syntax:
    content: public interface ServiceClientCredentials
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.credentials._azure_token_credentials
  parent: com.microsoft.azure.credentials
  href: com.microsoft.azure.credentials._azure_token_credentials.yml
  name: AzureTokenCredentials
  fullName: com.microsoft.azure.credentials.AzureTokenCredentials
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.azure.credentials._azure_token_credentials" data-throw-if-not-resolved="false"></xref> represents a credentials object with access to <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref><xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> management. </p>
  syntax:
    content: public interface AzureTokenCredentials extends ServiceClientCredentials
- uid: com.microsoft.azure._azure.authenticate(File)
  parent: com.microsoft.azure._azure
  href: com.microsoft.azure._azure.yml
  name: authenticate(File credentialsFile)
  fullName: static Authenticated com.microsoft.azure.Azure.authenticate(File credentialsFile)
  type: Method
  summary: <p>Authenticates API access using a properties file containing the required credentials. </p>
  syntax:
    content: public static Authenticated authenticate(File credentialsFile)
    parameters:
    - id: credentialsFile
      type: 8291270b
      description: <p>the file containing the credentials in the standard Java properties file format, with the following keys:</p>
    return:
      type: com.microsoft.azure._azure._authenticated
      description: <p>authenticated <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> client </p>
