items:
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_create
  id: _with_create
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_create_1ac0a17600433305d4bfe2babd2efba341
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_create.yml
  langs:
  - java
  name: Deployment.DefinitionStages.WithCreate
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithCreate
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 238
  package: com.microsoft.azure.management.resources
  summary: <p>A deployment definition with sufficient inputs to create a new deployment in the cloud, but exposing additional optional inputs to specify. </p>
  syntax:
    content: public interface WithCreate extends Creatable< Deployment >
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._creatable_1acf3889a24f1bb5e64f8e6a751397f991
  - com.microsoft.azure.management.resources.fluentcore.model._creatable_1adbc46a6d347c6b82ecca1a86b3bd6f10
  - com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_create_1ac0a17600433305d4bfe2babd2efba341
  id: _with_create_1ac0a17600433305d4bfe2babd2efba341
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_create
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_create.yml
  langs:
  - java
  name: beginCreate()
  fullName: Deployment com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithCreate.beginCreate()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 239
  package: com.microsoft.azure.management.resources
  syntax:
    content: public Deployment beginCreate()
    return:
      type: com.microsoft.azure.management.resources._deployment
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable_1acf3889a24f1bb5e64f8e6a751397f991
  parent: com.microsoft.azure.management.resources.fluentcore.model._creatable
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: create()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Creatable< T >.create()
  type: Method
  summary: >-
    <p>Execute the create request.</p>

    <p></p>
  syntax:
    content: public T create()
    return:
      type: 8ce1ecb9
      description: <p>the create resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable_1adbc46a6d347c6b82ecca1a86b3bd6f10
  parent: com.microsoft.azure.management.resources.fluentcore.model._creatable
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: createAsync(ServiceCallback< T > callback)
  fullName: ServiceCall com.microsoft.azure.management.resources.fluentcore.model.Creatable< T >.createAsync(ServiceCallback< T > callback)
  type: Method
  summary: >-
    <p>Puts the request into the queue and allow the HTTP client to execute it when system resources are available.</p>

    <p></p>
  syntax:
    content: public ServiceCall createAsync(ServiceCallback< T > callback)
    parameters:
    - id: callback
      type: com.microsoft.rest._service_callback34132889
      description: <p>the callback to handle success and failure </p>
    return:
      type: com.microsoft.rest._service_call
      description: <p>a handle to cancel the request </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: Creatable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>
  type: Interface
  summary: >-
    <p>The final stage of the resource definition, at which it can be create, using <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable_1acf3889a24f1bb5e64f8e6a751397f991" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface Creatable<T> extends Indexable
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the fluent type of the resource to be created </p>
- uid: com.microsoft.azure.management.resources._deployment._definition
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition.yml
  name: Deployment.Definition
  fullName: com.microsoft.azure.management.resources.Deployment.Definition
  type: Interface
  summary: <p>Container interface for all the deployment definitions. </p>
  syntax:
    content: public interface Definition extends Deployment.DefinitionStages.Blank,Deployment.DefinitionStages.WithGroup,Deployment.DefinitionStages.WithTemplate,Deployment.DefinitionStages.WithParameters,Deployment.DefinitionStages.WithMode,Deployment.DefinitionStages.WithCreate
- uid: com.microsoft.azure.management.resources._deployment
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment.yml
  name: Deployment
  fullName: com.microsoft.azure.management.resources.Deployment
  type: Interface
  summary: <p>An immutable client-side representation of an <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> deployment. </p>
  syntax:
    content: public interface Deployment extends Refreshable< Deployment >,Updatable< Deployment.Update >,Wrapper< DeploymentExtendedInner >
