items:
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  id: _multi_instance_settings
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._multi_instance_settings_1ae08a98a4f4f8f2067c8efd7f74080712
  - com.microsoft.azure.batch.protocol.models._multi_instance_settings_1a8c5ecc89c81d6ff1fd3d86c399b527a3
  - com.microsoft.azure.batch.protocol.models._multi_instance_settings_1a8578423ce5bf1b74fae28bc55d02fecc
  - com.microsoft.azure.batch.protocol.models._multi_instance_settings_1ab669ff0371ef57df8b6f9cada6430791
  - com.microsoft.azure.batch.protocol.models._multi_instance_settings_1aa3814353e4c71b9243b2be8616449a77
  - com.microsoft.azure.batch.protocol.models._multi_instance_settings_1ab6001cde0d41fd2ba2771298e7460d2e
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  langs:
  - java
  name: MultiInstanceSettings
  fullName: com.microsoft.azure.batch.protocol.models.MultiInstanceSettings
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Settings which specify how to run a multi-instance task. Multi-instance tasks are commonly used to support MPI tasks. </p>
  syntax: &o1
    content: public class MultiInstanceSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings_1ae08a98a4f4f8f2067c8efd7f74080712
  id: _multi_instance_settings_1ae08a98a4f4f8f2067c8efd7f74080712
  parent: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  langs:
  - java
  name: commonResourceFiles()
  fullName: List<ResourceFile> com.microsoft.azure.batch.protocol.models.MultiInstanceSettings.commonResourceFiles()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
    startLine: 85
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the commonResourceFiles value.</p>

    <p></p>
  syntax:
    content: public List< ResourceFile > commonResourceFiles()
    return:
      type: f6a6204dcom.microsoft.azure.batch.protocol.models._resource_file9ec3e006
      description: <p>the commonResourceFiles value </p>
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings_1a8c5ecc89c81d6ff1fd3d86c399b527a3
  id: _multi_instance_settings_1a8c5ecc89c81d6ff1fd3d86c399b527a3
  parent: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  langs:
  - java
  name: coordinationCommandLine()
  fullName: String com.microsoft.azure.batch.protocol.models.MultiInstanceSettings.coordinationCommandLine()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
    startLine: 65
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the coordinationCommandLine value.</p>

    <p></p>
  syntax:
    content: public String coordinationCommandLine()
    return:
      type: "26831127"
      description: <p>the coordinationCommandLine value </p>
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings_1a8578423ce5bf1b74fae28bc55d02fecc
  id: _multi_instance_settings_1a8578423ce5bf1b74fae28bc55d02fecc
  parent: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  langs:
  - java
  name: numberOfInstances()
  fullName: int com.microsoft.azure.batch.protocol.models.MultiInstanceSettings.numberOfInstances()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
    startLine: 45
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the numberOfInstances value.</p>

    <p></p>
  syntax:
    content: public int numberOfInstances()
    return:
      type: f75371fa
      description: <p>the numberOfInstances value </p>
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings_1ab669ff0371ef57df8b6f9cada6430791
  id: _multi_instance_settings_1ab669ff0371ef57df8b6f9cada6430791
  parent: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  langs:
  - java
  name: withCommonResourceFiles(List< ResourceFile > commonResourceFiles)
  fullName: MultiInstanceSettings com.microsoft.azure.batch.protocol.models.MultiInstanceSettings.withCommonResourceFiles(List< ResourceFile > commonResourceFiles)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
    startLine: 95
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the commonResourceFiles value.</p>

    <p></p>
  syntax:
    content: public MultiInstanceSettings withCommonResourceFiles(List< ResourceFile > commonResourceFiles)
    parameters:
    - id: commonResourceFiles
      type: f6a6204dcom.microsoft.azure.batch.protocol.models._resource_file9ec3e006
      description: <p>the commonResourceFiles value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._multi_instance_settings
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._multi_instance_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings_1aa3814353e4c71b9243b2be8616449a77
  id: _multi_instance_settings_1aa3814353e4c71b9243b2be8616449a77
  parent: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  langs:
  - java
  name: withCoordinationCommandLine(String coordinationCommandLine)
  fullName: MultiInstanceSettings com.microsoft.azure.batch.protocol.models.MultiInstanceSettings.withCoordinationCommandLine(String coordinationCommandLine)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
    startLine: 75
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the coordinationCommandLine value.</p>

    <p></p>
  syntax:
    content: public MultiInstanceSettings withCoordinationCommandLine(String coordinationCommandLine)
    parameters:
    - id: coordinationCommandLine
      type: "26831127"
      description: <p>the coordinationCommandLine value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._multi_instance_settings
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._multi_instance_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings_1ab6001cde0d41fd2ba2771298e7460d2e
  id: _multi_instance_settings_1ab6001cde0d41fd2ba2771298e7460d2e
  parent: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  langs:
  - java
  name: withNumberOfInstances(int numberOfInstances)
  fullName: MultiInstanceSettings com.microsoft.azure.batch.protocol.models.MultiInstanceSettings.withNumberOfInstances(int numberOfInstances)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/MultiInstanceSettings.java
    startLine: 55
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the numberOfInstances value.</p>

    <p></p>
  syntax:
    content: public MultiInstanceSettings withNumberOfInstances(int numberOfInstances)
    parameters:
    - id: numberOfInstances
      type: f75371fa
      description: <p>the numberOfInstances value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._multi_instance_settings
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._multi_instance_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f6a6204dcom.microsoft.azure.batch.protocol.models._resource_file9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.batch.protocol.models._resource_file
    name: ResourceFile
    fullName: com.microsoft.azure.batch.protocol.models.ResourceFile
    href: com.microsoft.azure.batch.protocol.models._resource_file.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.batch.protocol.models._resource_file
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._resource_file.yml
  name: ResourceFile
  fullName: com.microsoft.azure.batch.protocol.models.ResourceFile
  type: Class
  summary: <p>A file to be downloaded from <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> blob storage to a compute node. </p>
  syntax:
    content: public class ResourceFile
- uid: com.microsoft.azure.batch.protocol.models._multi_instance_settings
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._multi_instance_settings.yml
  name: MultiInstanceSettings
  fullName: com.microsoft.azure.batch.protocol.models.MultiInstanceSettings
  type: Class
  summary: <p>Settings which specify how to run a multi-instance task. Multi-instance tasks are commonly used to support MPI tasks. </p>
  syntax: *o1
