items:
- uid: com.microsoft.azure.management.resources._deployment._update_stages
  id: _update_stages
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update_stages.yml
  langs:
  - java
  name: Deployment.UpdateStages
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 254
  package: com.microsoft.azure.management.resources
  summary: <p>Grouping of all the deployment updates stages. </p>
  syntax:
    content: public interface UpdateStages
references: []
