items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  id: _update_f68ea101757e880e58df31ecebf76672
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(Creatable< PublicIpAddress >)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(String)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withoutPublicIpAddress()
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateStages.WithPublicIpAddress
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 413
  package: com.microsoft.azure.management.network
  summary: <p>The stage of the network interface IP configuration update allowing to specify public IP address. </p>
  syntax:
    content: public interface WithPublicIpAddress
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress()
  id: withNewPublicIpAddress()
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  langs:
  - java
  name: withNewPublicIpAddress()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 435
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource and associate it with the IP configuration. </p>

    <p>The internal name and DNS label for the public IP address will be derived from the network interface name, if there is an existing public IP association then that will be removed in favour of this.</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(Creatable< PublicIpAddress >)
  id: withNewPublicIpAddress(Creatable< PublicIpAddress >)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  langs:
  - java
  name: withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 424
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Create a new public IP address to associate the network interface IP configuration with, based on the provided definition. </p>

    <p>If there is public IP associated with the IP configuration then that will be removed in favour of this.</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
    parameters:
    - id: creatable
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._public_ip_address9ec3e006
      description: <p>a creatable definition for a new public IP </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(String)
  id: withNewPublicIpAddress(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  langs:
  - java
  name: withNewPublicIpAddress(String leafDnsLabel)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress(String leafDnsLabel)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 447
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource, with the specified DNS label and associate it with the IP configuration. </p>

    <p>The internal name for the public IP address will be derived from the DNS label, if there is an existing public IP association then that will be removed in favour of this</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress(String leafDnsLabel)
    parameters:
    - id: leafDnsLabel
      type: "26831127"
      description: <p>the leaf domain label </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withoutPublicIpAddress()
  id: withoutPublicIpAddress()
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  langs:
  - java
  name: withoutPublicIpAddress()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withoutPublicIpAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 454
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Specifies that remove any public IP associated with the IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withoutPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._public_ip_address9ec3e006
  spec.java:
  - uid: com.microsoft.azure.management.resources.fluentcore.model._creatable
    name: Creatable
    fullName: com.microsoft.azure.management.resources.fluentcore.model.Creatable
    href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  - name: '< '
    fullName: '< '
  - uid: com.microsoft.azure.management.network._public_ip_address
    name: PublicIpAddress
    fullName: com.microsoft.azure.management.network.PublicIpAddress
    href: com.microsoft.azure.management.network._public_ip_address.yml
  - name: " >"
    fullName: " >"
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update.yml
  name: NicIpConfiguration.Update
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Update
  type: Interface
  summary: <p>The entirety of a network interface IP configuration update as part of a network interface update. </p>
  syntax:
    content: public interface Update extends Settable< NetworkInterface.Update >,NicIpConfiguration.UpdateStages.WithSubnet,NicIpConfiguration.UpdateStages.WithPrivateIp,NicIpConfiguration.UpdateStages.WithPublicIpAddress,NicIpConfiguration.UpdateStages.WithLoadBalancer,NicIpConfiguration.UpdateStages.WithBackendAddressPool
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: Creatable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>
  type: Interface
  summary: >-
    <p>The final stage of the resource definition, at which it can be create, using <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable.create()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface Creatable<T> extends Indexable
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the fluent type of the resource to be created </p>
- uid: com.microsoft.azure.management.network._public_ip_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._public_ip_address.yml
  name: PublicIpAddress
  fullName: com.microsoft.azure.management.network.PublicIpAddress
  type: Interface
  summary: <p>Public IP address. </p>
  syntax:
    content: public interface PublicIpAddress extends GroupableResource,Refreshable< PublicIpAddress >,Wrapper< PublicIPAddressInner >,Updatable< PublicIpAddress.Update >
