items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration
  id: _nic_ip_configuration
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration.getNetwork()
  - com.microsoft.azure.management.network._nic_ip_configuration.listAssociatedLoadBalancerBackends()
  - com.microsoft.azure.management.network._nic_ip_configuration.listAssociatedLoadBalancerInboundNatRules()
  - com.microsoft.azure.management.network._nic_ip_configuration.privateIpAddressVersion()
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: NicIpConfiguration
  fullName: com.microsoft.azure.management.network.NicIpConfiguration
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 19
  package: com.microsoft.azure.management.network
  summary: <p>An IP configuration in a network interface. </p>
  syntax:
    content: public interface NicIpConfiguration extends Wrapper< NetworkInterfaceIPConfigurationInner >,ChildResource< NetworkInterface >,HasPrivateIpAddress,HasPublicIpAddress,HasSubnet
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_public_ip_address.getPublicIpAddress()
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  - com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.name()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.networkId()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.parent()
  - com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAddress()
  - com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAllocationMethod()
  - com.microsoft.azure.management.network.model._has_public_ip_address.publicIpAddressId()
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
  - com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.subnetName()
- uid: com.microsoft.azure.management.network._nic_ip_configuration.getNetwork()
  id: getNetwork()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: getNetwork()
  fullName: Network com.microsoft.azure.management.network.NicIpConfiguration.getNetwork()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 30
  package: com.microsoft.azure.management.network
  syntax:
    content: public Network getNetwork()
    return:
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network associated with this IP configuration </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration.listAssociatedLoadBalancerBackends()
  id: listAssociatedLoadBalancerBackends()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: listAssociatedLoadBalancerBackends()
  fullName: List<Backend> com.microsoft.azure.management.network.NicIpConfiguration.listAssociatedLoadBalancerBackends()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 40
  package: com.microsoft.azure.management.network
  syntax:
    content: public List< Backend > listAssociatedLoadBalancerBackends()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._backend9ec3e006
      description: <p>the load balancer backends associated with this network interface IP configuration </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration.listAssociatedLoadBalancerInboundNatRules()
  id: listAssociatedLoadBalancerInboundNatRules()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: listAssociatedLoadBalancerInboundNatRules()
  fullName: List<InboundNatRule> com.microsoft.azure.management.network.NicIpConfiguration.listAssociatedLoadBalancerInboundNatRules()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 45
  package: com.microsoft.azure.management.network
  syntax:
    content: public List< InboundNatRule > listAssociatedLoadBalancerInboundNatRules()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._inbound_nat_rule9ec3e006
      description: <p>the load balancer inbound NAT rules associated with this network interface IP configuration </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration.privateIpAddressVersion()
  id: privateIpAddressVersion()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: privateIpAddressVersion()
  fullName: IPVersion com.microsoft.azure.management.network.NicIpConfiguration.privateIpAddressVersion()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 35
  package: com.microsoft.azure.management.network
  syntax:
    content: public IPVersion privateIpAddressVersion()
    return:
      type: com.microsoft.azure.management.network._i_p_version
      description: <p>private IP address version </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.network._backend9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._backend
    name: Backend
    fullName: com.microsoft.azure.management.network.Backend
    href: com.microsoft.azure.management.network._backend.yml
  - name: " >"
    fullName: " >"
- uid: f6a6204dcom.microsoft.azure.management.network._inbound_nat_rule9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._inbound_nat_rule
    name: InboundNatRule
    fullName: com.microsoft.azure.management.network.InboundNatRule
    href: com.microsoft.azure.management.network._inbound_nat_rule.yml
  - name: " >"
    fullName: " >"
- uid: com.microsoft.azure.management.network.model._has_public_ip_address.getPublicIpAddress()
  parent: com.microsoft.azure.management.network.model._has_public_ip_address
  href: com.microsoft.azure.management.network.model._has_public_ip_address.yml
  name: getPublicIpAddress()
  fullName: PublicIpAddress com.microsoft.azure.management.network.model.HasPublicIpAddress.getPublicIpAddress()
  type: Method
  syntax:
    content: public PublicIpAddress getPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>the associated public IP address </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: inner()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Wrapper< T >.inner()
  type: Method
  syntax:
    content: public T inner()
    return:
      type: 8ce1ecb9
      description: <p>wrapped inner object providing direct access to the underlying auto-generated API implementation, based on <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> REST API </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.name()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: name()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource< ParentT >.name()
  type: Method
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name of this child object </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.networkId()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.yml
  name: networkId()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet.networkId()
  type: Method
  syntax:
    content: public String networkId()
    return:
      type: "26831127"
      description: <p>the resource ID of the virtual network whose subnet is associated with this resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.parent()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: parent()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource< ParentT >.parent()
  type: Method
  syntax:
    content: public ParentT parent()
    return:
      type: 18a275b1
      description: <p>the parent of this child object </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAddress()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: privateIpAddress()
  fullName: String com.microsoft.azure.management.network.model.HasPrivateIpAddress.privateIpAddress()
  type: Method
  syntax:
    content: public String privateIpAddress()
    return:
      type: "26831127"
      description: <p>the private IP address associated with this resource </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAllocationMethod()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: privateIpAllocationMethod()
  fullName: IPAllocationMethod com.microsoft.azure.management.network.model.HasPrivateIpAddress.privateIpAllocationMethod()
  type: Method
  syntax:
    content: public IPAllocationMethod privateIpAllocationMethod()
    return:
      type: com.microsoft.azure.management.network._i_p_allocation_method
      description: <p>the private IP address allocation method within the associated subnet </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address.publicIpAddressId()
  parent: com.microsoft.azure.management.network.model._has_public_ip_address
  href: com.microsoft.azure.management.network.model._has_public_ip_address.yml
  name: publicIpAddressId()
  fullName: String com.microsoft.azure.management.network.model.HasPublicIpAddress.publicIpAddressId()
  type: Method
  syntax:
    content: public String publicIpAddressId()
    return:
      type: "26831127"
      description: <p>the resource ID of the associated public IP address </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: setInner(T inner)
  fullName: void com.microsoft.azure.management.resources.fluentcore.model.Wrapper< T >.setInner(T inner)
  type: Method
  summary: >-
    <p>Set the wrapped inner model. (For internal use only)</p>

    <p></p>
  syntax:
    content: public void setInner(T inner)
    parameters:
    - id: inner
      type: 8ce1ecb9
      description: <p>the new inner model </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.subnetName()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.yml
  name: subnetName()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet.subnetName()
  type: Method
  syntax:
    content: public String subnetName()
    return:
      type: "26831127"
      description: <p>the name of the subnet associated with this resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: Wrapper<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>
  type: Interface
  summary: >-
    <p>The wrapper around an inner object providing extended functionalities.</p>

    <p></p>
  syntax:
    content: public interface Wrapper<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the inner object. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: ChildResource<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource<ParentT>
  type: Interface
  summary: <p>Base interface used by child resources. </p>
  syntax:
    content: public interface ChildResource<ParentT> extends Indexable
    typeParameters:
    - type: 18a275b1
      description: <p>parent interface </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: HasPrivateIpAddress
  fullName: com.microsoft.azure.management.network.model.HasPrivateIpAddress
  type: Interface
  summary: <p>An interface representing a model's ability to reference a private IP address. </p>
  syntax:
    content: public interface HasPrivateIpAddress
- uid: com.microsoft.azure.management.network.model._has_public_ip_address
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_public_ip_address.yml
  name: HasPublicIpAddress
  fullName: com.microsoft.azure.management.network.model.HasPublicIpAddress
  type: Interface
  summary: <p>An interface representing a model's ability to reference a public IP address. </p>
  syntax:
    content: public interface HasPublicIpAddress
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.yml
  name: HasSubnet
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet
  type: Interface
  summary: <p>An interface representing a model's ability to reference a subnet by its name and network's ID. </p>
  syntax:
    content: public interface HasSubnet
- uid: com.microsoft.azure.management.network.implementation._nic_ip_configuration_impl
- uid: com.microsoft.azure.management.network._network
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network.yml
  name: Network
  fullName: com.microsoft.azure.management.network.Network
  type: Interface
  summary: <p>Entry point for Virtual <xref href="com.microsoft.azure.management.network._network" data-throw-if-not-resolved="false"></xref> management API in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Network extends GroupableResource,Refreshable< Network >,Wrapper< VirtualNetworkInner >,Updatable< Network.Update >
- uid: com.microsoft.azure.management.network._i_p_version
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._i_p_version.yml
  name: IPVersion
  fullName: com.microsoft.azure.management.network.IPVersion
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._i_p_version" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class IPVersion
- uid: com.microsoft.azure.management.network._backend
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._backend.yml
  name: Backend
  fullName: com.microsoft.azure.management.network.Backend
  type: Interface
  summary: <p>An immutable client-side representation of an load balancer's backend address pool. </p>
  syntax:
    content: public interface Backend extends Wrapper< BackendAddressPoolInner >,ChildResource< LoadBalancer >,HasLoadBalancingRules
- uid: com.microsoft.azure.management.network._inbound_nat_rule
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._inbound_nat_rule.yml
  name: InboundNatRule
  fullName: com.microsoft.azure.management.network.InboundNatRule
  type: Interface
  summary: <p>An immutable client-side representation of an inbound NAT rule. </p>
  syntax:
    content: public interface InboundNatRule extends HasFrontend,HasBackendPort,HasProtocol< TransportProtocol >,HasFloatingIp,Wrapper< InboundNatRuleInner >,ChildResource< LoadBalancer >
