items:
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  id: _cloud_service_configuration
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a48a6495a426c57993c68ad5831af9ed0
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a2d0ff86213a89dd114b22bd2ca01a4d9
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a3077711eeb8510f17fd3de58fe36b173
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1ad0287674842353fa143d27b723ac1273
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a57c700d3c9de0e4174012a3df0cd6e20
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a721edff7da535334b0f522281448dd09
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: CloudServiceConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 16
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>The configuration for nodes in a pool based on the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Cloud Services platform. </p>
  syntax: &o1
    content: public class CloudServiceConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a48a6495a426c57993c68ad5831af9ed0
  id: _cloud_service_configuration_1a48a6495a426c57993c68ad5831af9ed0
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: currentOSVersion()
  fullName: String com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.currentOSVersion()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 83
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the currentOSVersion value.</p>

    <p></p>
  syntax:
    content: public String currentOSVersion()
    return:
      type: "26831127"
      description: <p>the currentOSVersion value </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a2d0ff86213a89dd114b22bd2ca01a4d9
  id: _cloud_service_configuration_1a2d0ff86213a89dd114b22bd2ca01a4d9
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: osFamily()
  fullName: String com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.osFamily()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 43
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the osFamily value.</p>

    <p></p>
  syntax:
    content: public String osFamily()
    return:
      type: "26831127"
      description: <p>the osFamily value </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a3077711eeb8510f17fd3de58fe36b173
  id: _cloud_service_configuration_1a3077711eeb8510f17fd3de58fe36b173
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: targetOSVersion()
  fullName: String com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.targetOSVersion()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 63
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the targetOSVersion value.</p>

    <p></p>
  syntax:
    content: public String targetOSVersion()
    return:
      type: "26831127"
      description: <p>the targetOSVersion value </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1ad0287674842353fa143d27b723ac1273
  id: _cloud_service_configuration_1ad0287674842353fa143d27b723ac1273
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: withCurrentOSVersion(String currentOSVersion)
  fullName: CloudServiceConfiguration com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.withCurrentOSVersion(String currentOSVersion)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 93
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the currentOSVersion value.</p>

    <p></p>
  syntax:
    content: public CloudServiceConfiguration withCurrentOSVersion(String currentOSVersion)
    parameters:
    - id: currentOSVersion
      type: "26831127"
      description: <p>the currentOSVersion value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._cloud_service_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a57c700d3c9de0e4174012a3df0cd6e20
  id: _cloud_service_configuration_1a57c700d3c9de0e4174012a3df0cd6e20
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: withOsFamily(String osFamily)
  fullName: CloudServiceConfiguration com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.withOsFamily(String osFamily)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 53
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the osFamily value.</p>

    <p></p>
  syntax:
    content: public CloudServiceConfiguration withOsFamily(String osFamily)
    parameters:
    - id: osFamily
      type: "26831127"
      description: <p>the osFamily value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._cloud_service_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration_1a721edff7da535334b0f522281448dd09
  id: _cloud_service_configuration_1a721edff7da535334b0f522281448dd09
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: withTargetOSVersion(String targetOSVersion)
  fullName: CloudServiceConfiguration com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.withTargetOSVersion(String targetOSVersion)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 73
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the targetOSVersion value.</p>

    <p></p>
  syntax:
    content: public CloudServiceConfiguration withTargetOSVersion(String targetOSVersion)
    parameters:
    - id: targetOSVersion
      type: "26831127"
      description: <p>the targetOSVersion value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._cloud_service_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  name: CloudServiceConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration
  type: Class
  summary: <p>The configuration for nodes in a pool based on the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Cloud Services platform. </p>
  syntax: *o1
