items:
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference
  id: _application_package_reference
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_package_reference_1a9b7ac457777cf773616eeef963d125ed
  - com.microsoft.azure.batch.protocol.models._application_package_reference_1a10da748e217797113e783ce7027bf7fe
  - com.microsoft.azure.batch.protocol.models._application_package_reference_1ab981d7c244ff53dc915bf20f328193be
  - com.microsoft.azure.batch.protocol.models._application_package_reference_1a05879bdf6acf30b4a060c2d74e067887
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: ApplicationPackageReference
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationPackageReference
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 16
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>A reference to an application package to be installed on compute nodes in a pool. </p>
  syntax: &o1
    content: public class ApplicationPackageReference
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference_1a9b7ac457777cf773616eeef963d125ed
  id: _application_package_reference_1a9b7ac457777cf773616eeef963d125ed
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: applicationId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.applicationId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 34
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the applicationId value.</p>

    <p></p>
  syntax:
    content: public String applicationId()
    return:
      type: "26831127"
      description: <p>the applicationId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference_1a10da748e217797113e783ce7027bf7fe
  id: _application_package_reference_1a10da748e217797113e783ce7027bf7fe
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: version()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.version()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 54
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the version value.</p>

    <p></p>
  syntax:
    content: public String version()
    return:
      type: "26831127"
      description: <p>the version value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference_1ab981d7c244ff53dc915bf20f328193be
  id: _application_package_reference_1ab981d7c244ff53dc915bf20f328193be
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: withApplicationId(String applicationId)
  fullName: ApplicationPackageReference com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.withApplicationId(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 44
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the applicationId value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackageReference withApplicationId(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>the applicationId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_package_reference
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_package_reference" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference_1a05879bdf6acf30b4a060c2d74e067887
  id: _application_package_reference_1a05879bdf6acf30b4a060c2d74e067887
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: withVersion(String version)
  fullName: ApplicationPackageReference com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.withVersion(String version)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 64
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the version value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackageReference withVersion(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_package_reference
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_package_reference" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  name: ApplicationPackageReference
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationPackageReference
  type: Class
  summary: <p>A reference to an application package to be installed on compute nodes in a pool. </p>
  syntax: *o1
