items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._blank
  id: _blank
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._blank.yml
  langs:
  - java
  name: NicIpConfiguration.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 77
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The first stage of network interface IP configuration definition.</p>

    <p></p>
  syntax:
    content: public interface Blank<ParentT> extends NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withExistingNetwork(Network)
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withNewNetwork(Creatable< Network >)
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withNewNetwork(String,String)
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withNewNetwork(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withExistingNetwork(Network)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.yml
  name: withExistingNetwork(Network network)
  fullName: WithSubnet<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >.withExistingNetwork(Network network)
  type: Method
  summary: >-
    <p>Associate an existing virtual network with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithSubnet< ParentT > withExistingNetwork(Network network)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>an existing virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_subneta6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withNewNetwork(Creatable< Network >)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.yml
  name: withNewNetwork(Creatable< Network > creatable)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >.withNewNetwork(Creatable< Network > creatable)
  type: Method
  summary: >-
    <p>Create a new virtual network to associate with the network interface IP configuration, based on the provided definition.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(Creatable< Network > creatable)
    parameters:
    - id: creatable
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._network9ec3e006
      description: <p>a creatable definition for a new virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ipa6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withNewNetwork(String,String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.yml
  name: withNewNetwork(String name, String addressSpace)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >.withNewNetwork(String name, String addressSpace)
  type: Method
  summary: >-
    <p>Creates a new virtual network to associate with the network interface IP configuration. </p>

    <p>the virtual network will be created in the same resource group and region as of parent network interface, it will be created with the specified address space and a default subnet covering the entirety of the network IP address space.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(String name, String addressSpace)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the new virtual network </p>
    - id: addressSpace
      type: "26831127"
      description: <p>the address space for rhe virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ipa6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.withNewNetwork(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.yml
  name: withNewNetwork(String addressSpace)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >.withNewNetwork(String addressSpace)
  type: Method
  summary: >-
    <p>Creates a new virtual network to associate with the network interface IP configuration. </p>

    <p>the virtual network will be created in the same resource group and region as of parent network interface, it will be created with the specified address space and a default subnet covering the entirety of the network IP address space.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(String addressSpace)
    parameters:
    - id: addressSpace
      type: "26831127"
      description: <p>the address space for the virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ipa6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_network.yml
  name: NicIpConfiguration.DefinitionStages.WithNetwork<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithNetwork<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify the virtual network.</p>

    <p></p>
  syntax:
    content: public interface WithNetwork<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition.yml
  name: NicIpConfiguration.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of the network interface IP configuration definition. </p>
  syntax:
    content: public interface Definition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
