items:
- uid: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration
  id: _with_ip_configuration
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration.defineSecondaryIpConfiguration(String)
  - com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration.updateIpConfiguration(String)
  href: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration.yml
  langs:
  - java
  name: NetworkInterface.UpdateStages.WithIpConfiguration
  fullName: com.microsoft.azure.management.network.NetworkInterface.UpdateStages.WithIpConfiguration
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterface.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterface.java
    startLine: 553
  package: com.microsoft.azure.management.network
  summary: <p>The stage of the network interface update allowing to configure IP configuration. </p>
  syntax:
    content: public interface WithIpConfiguration
- uid: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration.defineSecondaryIpConfiguration(String)
  id: defineSecondaryIpConfiguration(String)
  parent: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration
  href: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration.yml
  langs:
  - java
  name: defineSecondaryIpConfiguration(String name)
  fullName: NicIpConfiguration.UpdateDefinitionStages.Blank<NetworkInterface.Update> com.microsoft.azure.management.network.NetworkInterface.UpdateStages.WithIpConfiguration.defineSecondaryIpConfiguration(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterface.java
    startLine: 560
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Starts definition of a secondary IP configuration.</p>

    <p></p>
  syntax:
    content: public NicIpConfiguration.UpdateDefinitionStages.Blank< NetworkInterface.Update > defineSecondaryIpConfiguration(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>name for the IP configuration </p>
    return:
      type: f507ecc1
      description: <p>the first stage of a secondary IP configuration definition </p>
- uid: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration.updateIpConfiguration(String)
  id: updateIpConfiguration(String)
  parent: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration
  href: com.microsoft.azure.management.network._network_interface._update_stages._with_ip_configuration.yml
  langs:
  - java
  name: updateIpConfiguration(String name)
  fullName: NicIpConfiguration.Update com.microsoft.azure.management.network.NetworkInterface.UpdateStages.WithIpConfiguration.updateIpConfiguration(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterface.java
    startLine: 568
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Starts update of an IP configuration.</p>

    <p></p>
  syntax:
    content: public NicIpConfiguration.Update updateIpConfiguration(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>name of the IP configuration </p>
    return:
      type: c5a4ca50
      description: <p>the first stage of an IP configuration update </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f507ecc1
  spec.java:
  - name: NicIpConfiguration.UpdateDefinitionStages.Blank< NetworkInterface.Update >
    fullName: NicIpConfiguration.UpdateDefinitionStages.Blank< NetworkInterface.Update >
- uid: c5a4ca50
  spec.java:
  - name: NicIpConfiguration.Update
    fullName: NicIpConfiguration.Update
- uid: com.microsoft.azure.management.network._network_interface._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network_interface._update.yml
  name: NetworkInterface.Update
  fullName: com.microsoft.azure.management.network.NetworkInterface.Update
  type: Interface
  summary: >-
    <p>The template for an update operation, containing all the settings that can be modified. </p>

    <p>Call <xref href="com.microsoft.azure.management.resources.fluentcore.model._appliable.apply()" data-throw-if-not-resolved="false"></xref> to apply the changes to the resource in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Update extends Appliable< NetworkInterface >,Resource.UpdateWithTags< Update >,NetworkInterface.UpdateStages.WithPrimaryNetworkSubnet,NetworkInterface.UpdateStages.WithPrimaryPrivateIp,NetworkInterface.UpdateStages.WithPrimaryPublicIpAddress,NetworkInterface.UpdateStages.WithNetworkSecurityGroup,NetworkInterface.UpdateStages.WithIpForwarding,NetworkInterface.UpdateStages.WithDnsServer,NetworkInterface.UpdateStages.WithIpConfiguration,NetworkInterface.UpdateStages.WithLoadBalancer
