items:
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  id: _compute_node_get_remote_login_settings_headers
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a596a7e319acf906d2b696ebd2706542a
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a6745c79afbf14f557fb05fd07f7e1c1f
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1ac89aa13bb6ab78909ef8604a953046d6
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a272d7e8523b4dac9e580cad34b6f2759
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a382184aae8dfb997632d13104ebd7be8
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1adad47846529499a8fec1c0b2f2bf13bf
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a6660f4ff3eb9ffb4655c17c603dca200
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1abf5e813779274ddb643c0f7426fc05e3
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: ComputeNodeGetRemoteLoginSettingsHeaders
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Defines headers for GetRemoteLoginSettings operation. </p>
  syntax: &o1
    content: public class ComputeNodeGetRemoteLoginSettingsHeaders
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a596a7e319acf906d2b696ebd2706542a
  id: _compute_node_get_remote_login_settings_headers_1a596a7e319acf906d2b696ebd2706542a
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 48
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a6745c79afbf14f557fb05fd07f7e1c1f
  id: _compute_node_get_remote_login_settings_headers_1a6745c79afbf14f557fb05fd07f7e1c1f
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: eTag()
  fullName: String com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.eTag()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 88
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the eTag value.</p>

    <p></p>
  syntax:
    content: public String eTag()
    return:
      type: "26831127"
      description: <p>the eTag value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1ac89aa13bb6ab78909ef8604a953046d6
  id: _compute_node_get_remote_login_settings_headers_1ac89aa13bb6ab78909ef8604a953046d6
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: lastModified()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.lastModified()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 108
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the lastModified value.</p>

    <p></p>
  syntax:
    content: public DateTime lastModified()
    return:
      type: 230df18c
      description: <p>the lastModified value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a272d7e8523b4dac9e580cad34b6f2759
  id: _compute_node_get_remote_login_settings_headers_1a272d7e8523b4dac9e580cad34b6f2759
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: requestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.requestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 68
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the requestId value.</p>

    <p></p>
  syntax:
    content: public String requestId()
    return:
      type: "26831127"
      description: <p>the requestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a382184aae8dfb997632d13104ebd7be8
  id: _compute_node_get_remote_login_settings_headers_1a382184aae8dfb997632d13104ebd7be8
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ComputeNodeGetRemoteLoginSettingsHeaders com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 58
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsHeaders withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1adad47846529499a8fec1c0b2f2bf13bf
  id: _compute_node_get_remote_login_settings_headers_1adad47846529499a8fec1c0b2f2bf13bf
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: withETag(String eTag)
  fullName: ComputeNodeGetRemoteLoginSettingsHeaders com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.withETag(String eTag)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 98
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the eTag value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsHeaders withETag(String eTag)
    parameters:
    - id: eTag
      type: "26831127"
      description: <p>the eTag value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1a6660f4ff3eb9ffb4655c17c603dca200
  id: _compute_node_get_remote_login_settings_headers_1a6660f4ff3eb9ffb4655c17c603dca200
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: withLastModified(DateTime lastModified)
  fullName: ComputeNodeGetRemoteLoginSettingsHeaders com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.withLastModified(DateTime lastModified)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 121
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the lastModified value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsHeaders withLastModified(DateTime lastModified)
    parameters:
    - id: lastModified
      type: 230df18c
      description: <p>the lastModified value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers_1abf5e813779274ddb643c0f7426fc05e3
  id: _compute_node_get_remote_login_settings_headers_1abf5e813779274ddb643c0f7426fc05e3
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  langs:
  - java
  name: withRequestId(String requestId)
  fullName: ComputeNodeGetRemoteLoginSettingsHeaders com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders.withRequestId(String requestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsHeaders.java
    startLine: 78
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the requestId value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsHeaders withRequestId(String requestId)
    parameters:
    - id: requestId
      type: "26831127"
      description: <p>the requestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.rest._date_time_rfc1123
  parent: com.microsoft.rest
  href: com.microsoft.rest._date_time_rfc1123.yml
  name: DateTimeRfc1123
  fullName: com.microsoft.rest.DateTimeRfc1123
  type: Class
  summary: <p>Simple wrapper over joda.time.DateTime used for specifying RFC1123 format during serialization/deserialization. </p>
  syntax:
    content: public class DateTimeRfc1123
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_headers.yml
  name: ComputeNodeGetRemoteLoginSettingsHeaders
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsHeaders
  type: Class
  summary: <p>Defines headers for GetRemoteLoginSettings operation. </p>
  syntax: *o1
