items:
- uid: com.microsoft.azure.management.compute.implementation._compute_manager._configurable
  id: _configurable
  parent: com.microsoft.azure.management.compute.implementation
  children:
  - com.microsoft.azure.management.compute.implementation._compute_manager._configurable_1a755a3d19bc12e18899bd07d197de3c1f
  href: com.microsoft.azure.management.compute.implementation._compute_manager._configurable.yml
  langs:
  - java
  name: ComputeManager.Configurable
  fullName: com.microsoft.azure.management.compute.implementation.ComputeManager.Configurable
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/ComputeManager.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/ComputeManager.java
    startLine: 62
  package: com.microsoft.azure.management.compute.implementation
  summary: <p>The interface allowing configurations to be set. </p>
  syntax:
    content: public interface Configurable extends AzureConfigurable< Configurable >
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a688b59f0b61bdb7483ce300a4e68d336
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a75723b8886afb9ffd6cda3b9727e129c
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a9557917d15770e1f13c140234e0eb198
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a6b414c66da048d7b516479ff79648e7c
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a0bc5972c5d188f36218bd4ace5023759
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a4db90c995cb273b895b5ff16f8590c7d
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1aee80cd0339df9b310c874819669a7155
  - com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a3789530ecd024a9f4d7b8f5ca75b145b
- uid: com.microsoft.azure.management.compute.implementation._compute_manager._configurable_1a755a3d19bc12e18899bd07d197de3c1f
  id: _configurable_1a755a3d19bc12e18899bd07d197de3c1f
  parent: com.microsoft.azure.management.compute.implementation._compute_manager._configurable
  href: com.microsoft.azure.management.compute.implementation._compute_manager._configurable.yml
  langs:
  - java
  name: authenticate(ServiceClientCredentials credentials, String subscriptionId)
  fullName: ComputeManager com.microsoft.azure.management.compute.implementation.ComputeManager.Configurable.authenticate(ServiceClientCredentials credentials, String subscriptionId)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/ComputeManager.java
    startLine: 70
  package: com.microsoft.azure.management.compute.implementation
  summary: >-
    <p>Creates an instance of <xref href="com.microsoft.azure.management.compute.implementation._compute_manager" data-throw-if-not-resolved="false"></xref> that exposes Compute resource management API entry points.</p>

    <p></p>
  syntax:
    content: public ComputeManager authenticate(ServiceClientCredentials credentials, String subscriptionId)
    parameters:
    - id: credentials
      type: com.microsoft.rest.credentials._service_client_credentials
      description: <p>the credentials to use </p>
    - id: subscriptionId
      type: "26831127"
      description: <p>the subscription </p>
    return:
      type: com.microsoft.azure.management.compute.implementation._compute_manager
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation._compute_manager" data-throw-if-not-resolved="false"></xref></p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a688b59f0b61bdb7483ce300a4e68d336
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withCallbackExecutor(Executor executor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withCallbackExecutor(Executor executor)
  type: Method
  summary: >-
    <p>Sets the executor for async callbacks to run on.</p>

    <p></p>
  syntax:
    content: public T withCallbackExecutor(Executor executor)
    parameters:
    - id: executor
      type: 6f968643
      description: <p>the executor to execute the callbacks. </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a75723b8886afb9ffd6cda3b9727e129c
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withConnectionTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withConnectionTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the connection timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withConnectionTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a9557917d15770e1f13c140234e0eb198
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withInterceptor(Interceptor interceptor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withInterceptor(Interceptor interceptor)
  type: Method
  summary: >-
    <p>Plug in an interceptor into the HTTP pipeline.</p>

    <p></p>
  syntax:
    content: public T withInterceptor(Interceptor interceptor)
    parameters:
    - id: interceptor
      type: 910a0506
      description: <p>the interceptor to plug in </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a6b414c66da048d7b516479ff79648e7c
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withLogLevel(HttpLoggingInterceptor.Level level)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withLogLevel(HttpLoggingInterceptor.Level level)
  type: Method
  summary: >-
    <p>Set the logging level on the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withLogLevel(HttpLoggingInterceptor.Level level)
    parameters:
    - id: level
      type: b12c7a8c
      description: <p>the OkHttp logging level </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a0bc5972c5d188f36218bd4ace5023759
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withMaxIdleConnections(int maxIdleConnections)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withMaxIdleConnections(int maxIdleConnections)
  type: Method
  summary: >-
    <p>Set the maximum idle connections for the HTTP client. Default is 5.</p>

    <p></p>
  syntax:
    content: public T withMaxIdleConnections(int maxIdleConnections)
    parameters:
    - id: maxIdleConnections
      type: f75371fa
      description: <p>the maximum idle connections </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a4db90c995cb273b895b5ff16f8590c7d
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withProxy(Proxy proxy)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withProxy(Proxy proxy)
  type: Method
  summary: >-
    <p>Sets the proxy for the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withProxy(Proxy proxy)
    parameters:
    - id: proxy
      type: abc26ef5
      description: <p>the proxy to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1aee80cd0339df9b310c874819669a7155
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withReadTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withReadTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the read timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withReadTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable_1a3789530ecd024a9f4d7b8f5ca75b145b
  parent: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: withUserAgent(String userAgent)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable< T extends AzureConfigurable< T >.withUserAgent(String userAgent)
  type: Method
  summary: >-
    <p>Specify the user agent header.</p>

    <p></p>
  syntax:
    content: public T withUserAgent(String userAgent)
    parameters:
    - id: userAgent
      type: "26831127"
      description: <p>the user agent to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable
  parent: com.microsoft.azure.management.resources.fluentcore.arm
  href: com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable.yml
  name: AzureConfigurable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable<T>
  type: Interface
  summary: >-
    <p>The base interface for allowing configurations to be made on the HTTP client.</p>

    <p></p>
  syntax:
    content: public interface AzureConfigurable<T extends AzureConfigurable< T>>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the actual type of the interface extending this interface </p>
- uid: com.microsoft.azure.management.compute.implementation._compute_manager
  parent: com.microsoft.azure.management.compute.implementation
  href: com.microsoft.azure.management.compute.implementation._compute_manager.yml
  name: ComputeManager
  fullName: com.microsoft.azure.management.compute.implementation.ComputeManager
  type: Class
  summary: <p>Entry point to <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> compute resource management. </p>
  syntax:
    content: public class ComputeManager extends Manager< ComputeManager, ComputeManagementClientImpl >
- uid: com.microsoft.rest.credentials._service_client_credentials
  parent: com.microsoft.rest.credentials
  href: com.microsoft.rest.credentials._service_client_credentials.yml
  name: ServiceClientCredentials
  fullName: com.microsoft.rest.credentials.ServiceClientCredentials
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.rest.credentials._service_client_credentials" data-throw-if-not-resolved="false"></xref> is the abstraction for credentials used by ServiceClients accessing REST services. </p>
  syntax:
    content: public interface ServiceClientCredentials
