items:
- uid: com.microsoft.azure.batch.protocol.models._application_get_options
  id: _application_get_options
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_get_options_1a1501ecf4e7e1a42efcb0f3d9afcb566e
  - com.microsoft.azure.batch.protocol.models._application_get_options_1ad766df60a7249130bdb9db12019c37b7
  - com.microsoft.azure.batch.protocol.models._application_get_options_1aa9e6039c3b389eeac5a6efe403e15114
  - com.microsoft.azure.batch.protocol.models._application_get_options_1aa603884fc14c7a7eb7fc042748ab5d01
  - com.microsoft.azure.batch.protocol.models._application_get_options_1a2b33217230ab25b7aae9cffe25000343
  - com.microsoft.azure.batch.protocol.models._application_get_options_1aa2520fcd8feeb2e6e682e274b06159ce
  - com.microsoft.azure.batch.protocol.models._application_get_options_1a0a7a7ae5816385a8625337fcd16167ee
  - com.microsoft.azure.batch.protocol.models._application_get_options_1ad4ce59a1f58f69927b4bb0f14d804863
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: ApplicationGetOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationGetOptions
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Additional parameters for the Application_Get operation. </p>
  syntax: &o1
    content: public class ApplicationGetOptions
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1a1501ecf4e7e1a42efcb0f3d9afcb566e
  id: _application_get_options_1a1501ecf4e7e1a42efcb0f3d9afcb566e
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 72
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1ad766df60a7249130bdb9db12019c37b7
  id: _application_get_options_1ad766df60a7249130bdb9db12019c37b7
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: ocpDate()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.ocpDate()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 112
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the ocpDate value.</p>

    <p></p>
  syntax:
    content: public DateTime ocpDate()
    return:
      type: 230df18c
      description: <p>the ocpDate value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1aa9e6039c3b389eeac5a6efe403e15114
  id: _application_get_options_1aa9e6039c3b389eeac5a6efe403e15114
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: returnClientRequestId()
  fullName: Boolean com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.returnClientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 92
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public Boolean returnClientRequestId()
    return:
      type: 866c2227
      description: <p>the returnClientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1aa603884fc14c7a7eb7fc042748ab5d01
  id: _application_get_options_1aa603884fc14c7a7eb7fc042748ab5d01
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: timeout()
  fullName: Integer com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.timeout()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 52
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the timeout value.</p>

    <p></p>
  syntax:
    content: public Integer timeout()
    return:
      type: 08effaa0
      description: <p>the timeout value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1a2b33217230ab25b7aae9cffe25000343
  id: _application_get_options_1a2b33217230ab25b7aae9cffe25000343
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ApplicationGetOptions com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 82
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetOptions withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1aa2520fcd8feeb2e6e682e274b06159ce
  id: _application_get_options_1aa2520fcd8feeb2e6e682e274b06159ce
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: withOcpDate(DateTime ocpDate)
  fullName: ApplicationGetOptions com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.withOcpDate(DateTime ocpDate)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 125
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the ocpDate value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetOptions withOcpDate(DateTime ocpDate)
    parameters:
    - id: ocpDate
      type: 230df18c
      description: <p>the ocpDate value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1a0a7a7ae5816385a8625337fcd16167ee
  id: _application_get_options_1a0a7a7ae5816385a8625337fcd16167ee
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: withReturnClientRequestId(Boolean returnClientRequestId)
  fullName: ApplicationGetOptions com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.withReturnClientRequestId(Boolean returnClientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 102
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetOptions withReturnClientRequestId(Boolean returnClientRequestId)
    parameters:
    - id: returnClientRequestId
      type: 866c2227
      description: <p>the returnClientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_get_options_1ad4ce59a1f58f69927b4bb0f14d804863
  id: _application_get_options_1ad4ce59a1f58f69927b4bb0f14d804863
  parent: com.microsoft.azure.batch.protocol.models._application_get_options
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  langs:
  - java
  name: withTimeout(Integer timeout)
  fullName: ApplicationGetOptions com.microsoft.azure.batch.protocol.models.ApplicationGetOptions.withTimeout(Integer timeout)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationGetOptions.java
    startLine: 62
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the timeout value.</p>

    <p></p>
  syntax:
    content: public ApplicationGetOptions withTimeout(Integer timeout)
    parameters:
    - id: timeout
      type: 08effaa0
      description: <p>the timeout value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_get_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_get_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.rest._date_time_rfc1123
  parent: com.microsoft.rest
  href: com.microsoft.rest._date_time_rfc1123.yml
  name: DateTimeRfc1123
  fullName: com.microsoft.rest.DateTimeRfc1123
  type: Class
  summary: <p>Simple wrapper over joda.time.DateTime used for specifying RFC1123 format during serialization/deserialization. </p>
  syntax:
    content: public class DateTimeRfc1123
- uid: com.microsoft.azure.batch.protocol.models._application_get_options
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_get_options.yml
  name: ApplicationGetOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationGetOptions
  type: Class
  summary: <p>Additional parameters for the Application_Get operation. </p>
  syntax: *o1
