items:
- uid: com.microsoft.azure.management.batch._application._update_stages._with_application_package
  id: _with_application_package
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._application._update_stages._with_application_package.defineNewApplicationPackage(String)
  - com.microsoft.azure.management.batch._application._update_stages._with_application_package.withoutApplicationPackage(String)
  href: com.microsoft.azure.management.batch._application._update_stages._with_application_package.yml
  langs:
  - java
  name: Application.UpdateStages.WithApplicationPackage
  fullName: com.microsoft.azure.management.batch.Application.UpdateStages.WithApplicationPackage
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 192
  package: com.microsoft.azure.management.batch
  summary: <p>A application definition to allow creation of application package. </p>
  syntax:
    content: public interface WithApplicationPackage
- uid: com.microsoft.azure.management.batch._application._update_stages._with_application_package.defineNewApplicationPackage(String)
  id: defineNewApplicationPackage(String)
  parent: com.microsoft.azure.management.batch._application._update_stages._with_application_package
  href: com.microsoft.azure.management.batch._application._update_stages._with_application_package.yml
  langs:
  - java
  name: defineNewApplicationPackage(String version)
  fullName: Update com.microsoft.azure.management.batch.Application.UpdateStages.WithApplicationPackage.defineNewApplicationPackage(String version)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 199
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>First stage to create new application package in Batch account application.</p>

    <p></p>
  syntax:
    content: public Update defineNewApplicationPackage(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version of the application </p>
    return:
      type: com.microsoft.azure.management.batch._application._update
      description: <p>next stage to create the application. </p>
- uid: com.microsoft.azure.management.batch._application._update_stages._with_application_package.withoutApplicationPackage(String)
  id: withoutApplicationPackage(String)
  parent: com.microsoft.azure.management.batch._application._update_stages._with_application_package
  href: com.microsoft.azure.management.batch._application._update_stages._with_application_package.yml
  langs:
  - java
  name: withoutApplicationPackage(String version)
  fullName: Update com.microsoft.azure.management.batch.Application.UpdateStages.WithApplicationPackage.withoutApplicationPackage(String version)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 207
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Deletes specified application package from the application.</p>

    <p></p>
  syntax:
    content: public Update withoutApplicationPackage(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the reference version of the application to be removed </p>
    return:
      type: com.microsoft.azure.management.batch._application._update
      description: <p>the stage representing updatable batch account definition. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.batch._application._update
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update.yml
  name: Application.Update
  fullName: com.microsoft.azure.management.batch.Application.Update
  type: Interface
  summary: <p>The entirety of application update as a part of parent batch account update. </p>
  syntax:
    content: public interface Update extends Settable< BatchAccount.Update >,Application.UpdateStages.WithOptionalProperties,Application.UpdateStages.WithApplicationPackage
- uid: com.microsoft.azure.management.batch.implementation._application_impl.defineNewApplicationPackage(String)
  parent: com.microsoft.azure.management.batch.implementation._application_impl
  href: com.microsoft.azure.management.batch.implementation._application_impl.yml
  name: defineNewApplicationPackage(String applicationPackageName)
  fullName: ApplicationImpl com.microsoft.azure.management.batch.implementation.ApplicationImpl.defineNewApplicationPackage(String applicationPackageName)
  type: Method
  summary: >-
    <p>First stage to create new application package in Batch account application.</p>

    <p></p>
  syntax:
    content: public ApplicationImpl defineNewApplicationPackage(String applicationPackageName)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version of the application </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_impl
      description: <p>next stage to create the application. </p>
- uid: com.microsoft.azure.management.batch.implementation._application_impl.withoutApplicationPackage(String)
  parent: com.microsoft.azure.management.batch.implementation._application_impl
  href: com.microsoft.azure.management.batch.implementation._application_impl.yml
  name: withoutApplicationPackage(String applicationPackageName)
  fullName: Update com.microsoft.azure.management.batch.implementation.ApplicationImpl.withoutApplicationPackage(String applicationPackageName)
  type: Method
  summary: >-
    <p>Deletes specified application package from the application.</p>

    <p></p>
  syntax:
    content: public Update withoutApplicationPackage(String applicationPackageName)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the reference version of the application to be removed </p>
    return:
      type: com.microsoft.azure.management.batch._application._update
      description: <p>the stage representing updatable batch account definition. </p>
