items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_definition
  id: _update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_definition.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 171
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of a network interface IP configuration definition as part of a network interface update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends NicIpConfiguration.UpdateDefinitionStages.Blank< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithAttach< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withExistingNetwork(Network)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withNewNetwork(Creatable< Network >)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withNewNetwork(String,String)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withNewNetwork(String)
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.withPrivateIpVersion(IPVersion)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6.withSubnet(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.InUpdate< ParentT >.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withExistingNetwork(Network)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  name: withExistingNetwork(Network network)
  fullName: WithSubnet<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withExistingNetwork(Network network)
  type: Method
  summary: >-
    <p>Associate an existing virtual network with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithSubnet< ParentT > withExistingNetwork(Network network)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>an existing virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6a6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withNewNetwork(Creatable< Network >)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  name: withNewNetwork(Creatable< Network > creatable)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withNewNetwork(Creatable< Network > creatable)
  type: Method
  summary: >-
    <p>Create a new virtual network to associate with the network interface IP configuration, based on the provided definition.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(Creatable< Network > creatable)
    parameters:
    - id: creatable
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._network9ec3e006
      description: <p>a creatable definition for a new virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withNewNetwork(String,String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  name: withNewNetwork(String name, String addressSpace)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withNewNetwork(String name, String addressSpace)
  type: Method
  summary: >-
    <p>Creates a new virtual network to associate with the network interface IP configuration. </p>

    <p>the virtual network will be created in the same resource group and region as of parent network interface, it will be created with the specified address space and a default subnet covering the entirety of the network IP address space.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(String name, String addressSpace)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the new virtual network </p>
    - id: addressSpace
      type: "26831127"
      description: <p>the address space for rhe virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.withNewNetwork(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  name: withNewNetwork(String addressSpace)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withNewNetwork(String addressSpace)
  type: Method
  summary: >-
    <p>Creates a new virtual network to associate with the network interface IP configuration. </p>

    <p>the virtual network will be created in the same resource group and region as of parent network interface, it will be created with the specified address space and a default subnet covering the entirety of the network IP address space.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(String addressSpace)
    parameters:
    - id: addressSpace
      type: "26831127"
      description: <p>the address space for the virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.withPrivateIpVersion(IPVersion)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.yml
  name: withPrivateIpVersion(IPVersion ipVersion)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp< ParentT >.withPrivateIpVersion(IPVersion ipVersion)
  type: Method
  summary: <p>Specifies the IP version for the private IP address. </p>
  syntax:
    content: public WithAttach< ParentT > withPrivateIpVersion(IPVersion ipVersion)
    parameters:
    - id: ipVersion
      type: com.microsoft.azure.management.network._i_p_version
      description: <p>an IP version </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089a6da57ba
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6.withSubnet(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6.yml
  name: withSubnet(String name)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithSubnet< ParentT >.withSubnet(String name)
  type: Method
  summary: >-
    <p>Associate a subnet with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withSubnet(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the subnet name </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_definition_stages._blank
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_definition_stages._blank.yml
  name: NicIpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  summary: >-
    <p>The first stage of network interface IP configuration definition.</p>

    <p></p>
  syntax:
    content: public interface Blank<ParentT> extends NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of network interface IP configuration. </p>

    <p>At this stage, any remaining optional settings can be specified, or the network interface IP configuration definition can be attached to the parent network interface definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithNetwork<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify the virtual network.</p>

    <p></p>
  syntax:
    content: public interface WithNetwork<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify private IP address within a virtual network subnet.</p>

    <p></p>
  syntax:
    content: public interface WithPrivateIp<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithSubnet<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify subnet.</p>

    <p></p>
  syntax:
    content: public interface WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_c3cce3289129918c5353c4599ebfbf2c.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to associate it with a public IP address.</p>

    <p></p>
  syntax:
    content: public interface WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
