items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update
  id: _update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update.yml
  langs:
  - java
  name: NicIpConfiguration.Update
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Update
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 423
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of a network interface IP configuration update as part of a network interface update. </p>
  syntax:
    content: public interface Update extends Settable< NetworkInterface.Update >,NicIpConfiguration.UpdateStages.WithSubnet,NicIpConfiguration.UpdateStages.WithPrivateIp,NicIpConfiguration.UpdateStages.WithPublicIpAddress
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._settable_1a2161d5ed2001041610d85dad2e36db2e
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1a9fd0c6c059c60b45796911398de38eb6
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1ae17f04b8f01abebe8deb47fd28e9d3b6
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1a77b40c67a1a866f66eda1920aef19675
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1a3de84ad6b9b84eb3bdb73c456eb7fbad
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip_1a2d13d55809bf9345250895b2db9a559d
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip_1a1b1332f02b57496fffdc52733b6b689f
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet_1ae952abf7216f9d158315c701273ed1e2
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable_1a2161d5ed2001041610d85dad2e36db2e
  parent: com.microsoft.azure.management.resources.fluentcore.model._settable
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: parent()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Settable< ParentT >.parent()
  type: Method
  summary: >-
    <p>Begins an update for a child resource. </p>

    <p>This is the beginning of the builder pattern used to update child resources The final method completing the update and continue the actual parent resource update process in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> is <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable_1a2161d5ed2001041610d85dad2e36db2e" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public ParentT parent()
    return:
      type: 18a275b1
      description: <p>the stage of parent resource update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1a9fd0c6c059c60b45796911398de38eb6
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  type: Method
  summary: >-
    <p>Create a new public IP address to associate the network interface IP configuration with, based on the provided definition. </p>

    <p>If there is public IP associated with the IP configuration then that will be removed in favour of this.</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
    parameters:
    - id: creatable
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._public_ip_address9ec3e006
      description: <p>a creatable definition for a new public IP </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1ae17f04b8f01abebe8deb47fd28e9d3b6
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withNewPublicIpAddress()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress()
  type: Method
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource and associate it with the IP configuration. </p>

    <p>The internal name and DNS label for the public IP address will be derived from the network interface name, if there is an existing public IP association then that will be removed in favour of this.</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1a77b40c67a1a866f66eda1920aef19675
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withNewPublicIpAddress(String leafDnsLabel)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress(String leafDnsLabel)
  type: Method
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource, with the specified DNS label and associate it with the IP configuration. </p>

    <p>The internal name for the public IP address will be derived from the DNS label, if there is an existing public IP association then that will be removed in favour of this</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress(String leafDnsLabel)
    parameters:
    - id: leafDnsLabel
      type: "26831127"
      description: <p>the leaf domain label </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672_1a3de84ad6b9b84eb3bdb73c456eb7fbad
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withoutPublicIpAddress()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withoutPublicIpAddress()
  type: Method
  summary: >-
    <p>Specifies that remove any public IP associated with the IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withoutPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip_1a2d13d55809bf9345250895b2db9a559d
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  name: withPrivateIpAddressDynamic()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp.withPrivateIpAddressDynamic()
  type: Method
  summary: >-
    <p>Enables dynamic private IP address allocation within the specified existing virtual network subnet to the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withPrivateIpAddressDynamic()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip_1a1b1332f02b57496fffdc52733b6b689f
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  name: withPrivateIpAddressStatic(String staticPrivateIpAddress)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp.withPrivateIpAddressStatic(String staticPrivateIpAddress)
  type: Method
  summary: >-
    <p>Assigns the specified static private IP address within the specified existing virtual network subnet to the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withPrivateIpAddressStatic(String staticPrivateIpAddress)
    parameters:
    - id: staticPrivateIpAddress
      type: "26831127"
      description: <p>the static IP address within the specified subnet to assign to the IP configuration </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet_1ae952abf7216f9d158315c701273ed1e2
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.yml
  name: withSubnet(String name)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithSubnet.withSubnet(String name)
  type: Method
  summary: >-
    <p>Associate a subnet with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withSubnet(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the subnet name </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: Settable<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Settable<ParentT>
  type: Interface
  summary: >-
    <p>The base interface for all template interfaces for child resources that support update operations.</p>

    <p></p>
  syntax:
    content: public interface Settable<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable_1a2161d5ed2001041610d85dad2e36db2e" data-throw-if-not-resolved="false"></xref> returns to </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.yml
  name: NicIpConfiguration.UpdateStages.WithSubnet
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithSubnet
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify subnet. </p>
  syntax:
    content: public interface WithSubnet
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  name: NicIpConfiguration.UpdateStages.WithPrivateIp
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify private IP. </p>
  syntax:
    content: public interface WithPrivateIp
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: NicIpConfiguration.UpdateStages.WithPublicIpAddress
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify public IP address. </p>
  syntax:
    content: public interface WithPublicIpAddress
- uid: com.microsoft.azure.management.network.implementation._nic_ip_configuration_impl
