items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  id: _update_f68ea101757e880e58df31ecebf76672
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateStages.WithPublicIpAddress
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 339
  package: com.microsoft.azure.management.network
  summary: <p>The stage of the network interface IP configuration update allowing to specify public IP address. </p>
  syntax:
    content: public interface WithPublicIpAddress extends HasPublicIpAddress.UpdateStages.WithPublicIpAddress< Update >
references:
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_126a32c4ceab914c62e1ba55e4d88b1cd
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_public_ip_address_126a32c4ceab914c62e1ba55e4d88b1cd.yml
  name: HasPublicIpAddress.UpdateStages.WithPublicIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateStages.WithPublicIpAddress<ReturnT>
  type: Interface
  summary: >-
    <p>The stage definition allowing to associate the resource with a public IP address.</p>

    <p></p>
  syntax:
    content: public interface WithPublicIpAddress<ReturnT> extends HasPublicIpAddress.UpdateStages.WithExistingPublicIpAddress< ReturnT >,HasPublicIpAddress.UpdateStages.WithNewPublicIpAddress< ReturnT >
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update.yml
  name: NicIpConfiguration.Update
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Update
  type: Interface
  summary: <p>The entirety of a network interface IP configuration update as part of a network interface update. </p>
  syntax:
    content: public interface Update extends Settable< NetworkInterface.Update >,NicIpConfiguration.UpdateStages.WithSubnet,NicIpConfiguration.UpdateStages.WithPrivateIp,NicIpConfiguration.UpdateStages.WithPublicIpAddress,NicIpConfiguration.UpdateStages.WithLoadBalancer,NicIpConfiguration.UpdateStages.WithBackendAddressPool
