items:
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations
  id: _with_configurations
  parent: com.microsoft.azure.management.keyvault
  children:
  - com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDeploymentDisabled()
  - com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDeploymentEnabled()
  - com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDiskEncryptionDisabled()
  - com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDiskEncryptionEnabled()
  - com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withTemplateDeploymentDisabled()
  - com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withTemplateDeploymentEnabled()
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.yml
  langs:
  - java
  name: Vault.DefinitionStages.WithConfigurations
  fullName: com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithConfigurations
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 144
  package: com.microsoft.azure.management.keyvault
  summary: <p>A key vault definition allowing various configurations to be set. </p>
  syntax:
    content: public interface WithConfigurations
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDeploymentDisabled()
  id: withDeploymentDisabled()
  parent: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.yml
  langs:
  - java
  name: withDeploymentDisabled()
  fullName: WithCreate com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithConfigurations.withDeploymentDisabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 171
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Disable <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Virtual Machines to retrieve certificates stored as secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public WithCreate withDeploymentDisabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create
      description: <p>the next stage of key vault definition </p>
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDeploymentEnabled()
  id: withDeploymentEnabled()
  parent: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.yml
  langs:
  - java
  name: withDeploymentEnabled()
  fullName: WithCreate com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithConfigurations.withDeploymentEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 150
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Enable <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Virtual Machines to retrieve certificates stored as secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public WithCreate withDeploymentEnabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create
      description: <p>the next stage of key vault definition </p>
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDiskEncryptionDisabled()
  id: withDiskEncryptionDisabled()
  parent: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.yml
  langs:
  - java
  name: withDiskEncryptionDisabled()
  fullName: WithCreate com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithConfigurations.withDiskEncryptionDisabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 178
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Disable <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Disk Encryption to retrieve secrets from the vault and unwrap keys.</p>

    <p></p>
  syntax:
    content: public WithCreate withDiskEncryptionDisabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create
      description: <p>the next stage of key vault definition </p>
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withDiskEncryptionEnabled()
  id: withDiskEncryptionEnabled()
  parent: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.yml
  langs:
  - java
  name: withDiskEncryptionEnabled()
  fullName: WithCreate com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithConfigurations.withDiskEncryptionEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 157
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Enable <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Disk Encryption to retrieve secrets from the vault and unwrap keys.</p>

    <p></p>
  syntax:
    content: public WithCreate withDiskEncryptionEnabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create
      description: <p>the next stage of key vault definition </p>
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withTemplateDeploymentDisabled()
  id: withTemplateDeploymentDisabled()
  parent: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.yml
  langs:
  - java
  name: withTemplateDeploymentDisabled()
  fullName: WithCreate com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithConfigurations.withTemplateDeploymentDisabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 185
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Disable <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref><xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> Manager to retrieve secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public WithCreate withTemplateDeploymentDisabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create
      description: <p>the next stage of key vault definition </p>
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.withTemplateDeploymentEnabled()
  id: withTemplateDeploymentEnabled()
  parent: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_configurations.yml
  langs:
  - java
  name: withTemplateDeploymentEnabled()
  fullName: WithCreate com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithConfigurations.withTemplateDeploymentEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Vault.java
    startLine: 164
  package: com.microsoft.azure.management.keyvault
  summary: >-
    <p>Enable <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref><xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> Manager to retrieve secrets from the key vault.</p>

    <p></p>
  syntax:
    content: public WithCreate withTemplateDeploymentEnabled()
    return:
      type: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create
      description: <p>the next stage of key vault definition </p>
references:
- uid: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create
  parent: com.microsoft.azure.management.keyvault
  href: com.microsoft.azure.management.keyvault._vault._definition_stages._with_create.yml
  name: Vault.DefinitionStages.WithCreate
  fullName: com.microsoft.azure.management.keyvault.Vault.DefinitionStages.WithCreate
  type: Interface
  summary: <p>A key vault definition with sufficient inputs to create a new storage account in the cloud, but exposing additional optional inputs to specify. </p>
  syntax:
    content: public interface WithCreate
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure._resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._resource.yml
  name: Resource
  fullName: com.microsoft.azure.Resource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class Resource
