items:
- uid: com.microsoft.azure.management.resources._deployment_export_result
  id: _deployment_export_result
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment_export_result_1a7fb015b48a5b39f791ba9b785b966ea4
  - com.microsoft.azure.management.resources._deployment_export_result_1ab92f03abade48ad39dda67117a623cec
  href: com.microsoft.azure.management.resources._deployment_export_result.yml
  langs:
  - java
  name: DeploymentExportResult
  fullName: com.microsoft.azure.management.resources.DeploymentExportResult
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentExportResult.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentExportResult.java
    startLine: 14
  package: com.microsoft.azure.management.resources
  summary: <p>An immutable client-side representation of an <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> deployment template export result. </p>
  syntax:
    content: public interface DeploymentExportResult extends Wrapper< DeploymentExportResultInner >
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper_1abc55ed091c6359eabd413c60b0d3c7fb
- uid: com.microsoft.azure.management.resources._deployment_export_result_1a7fb015b48a5b39f791ba9b785b966ea4
  id: _deployment_export_result_1a7fb015b48a5b39f791ba9b785b966ea4
  parent: com.microsoft.azure.management.resources._deployment_export_result
  href: com.microsoft.azure.management.resources._deployment_export_result.yml
  langs:
  - java
  name: template()
  fullName: Object com.microsoft.azure.management.resources.DeploymentExportResult.template()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentExportResult.java
    startLine: 20
  package: com.microsoft.azure.management.resources
  syntax:
    content: public Object template()
    return:
      type: "79317049"
      description: <p>the template content </p>
- uid: com.microsoft.azure.management.resources._deployment_export_result_1ab92f03abade48ad39dda67117a623cec
  id: _deployment_export_result_1ab92f03abade48ad39dda67117a623cec
  parent: com.microsoft.azure.management.resources._deployment_export_result
  href: com.microsoft.azure.management.resources._deployment_export_result.yml
  langs:
  - java
  name: templateAsJson()
  fullName: String com.microsoft.azure.management.resources.DeploymentExportResult.templateAsJson()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentExportResult.java
    startLine: 25
  package: com.microsoft.azure.management.resources
  syntax:
    content: public String templateAsJson()
    return:
      type: "26831127"
      description: <p>the template content as a JSON string </p>
references:
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper_1abc55ed091c6359eabd413c60b0d3c7fb
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: inner()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Wrapper< T >.inner()
  type: Method
  syntax:
    content: public T inner()
    return:
      type: 8ce1ecb9
      description: <p>wrapped inner object providing direct access to the underlying auto-generated API implementation, based on <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> REST API </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: Wrapper<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>
  type: Interface
  summary: >-
    <p>The wrapper around an inner object providing extended functionalities.</p>

    <p></p>
  syntax:
    content: public interface Wrapper<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the inner object. </p>
- uid: com.microsoft.azure.management.resources.implementation._deployment_export_result_impl
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
