items:
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  id: _slot_config_names_resource_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1acdf9816e6f43663179bb7cee202502eb
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1aed10afce297eb4fe8c8600b330cf699d
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1a331a078935593b20db1efbef4d37e0fc
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1a05ce239949372a2a34f09c203915d1ae
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: SlotConfigNamesResourceInner
  fullName: com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 19
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Slot Config names azure resource. </p>
  syntax: &o1
    content: public class SlotConfigNamesResourceInner extends Resource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._resource
  inheritedMembers:
  - com.microsoft.azure._resource_1a2e102c3a5a80cabb644ef19ec31a9b9a
  - com.microsoft.azure._resource_1a00cc4f65c2d841294380d99ba4fd8782
  - com.microsoft.azure._resource_1ae54c7770e81b739bf0ecf42aa3881887
  - com.microsoft.azure._resource_1a0acbe5481adee4c388e642dfdfeb18e6
  - com.microsoft.azure._resource_1aff3f1f9fe4db6f84d424cd354369e1cd
  - com.microsoft.azure._resource_1a6a1f31436a35ab46583c7e741601a2e8
  - com.microsoft.azure._resource_1a832de9258cf4a03d822c4fe33db8768b
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1acdf9816e6f43663179bb7cee202502eb
  id: _slot_config_names_resource_inner_1acdf9816e6f43663179bb7cee202502eb
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: appSettingNames()
  fullName: List<String> com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.appSettingNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 57
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public List< String > appSettingNames()
    return:
      type: f35af49b
      description: <p>the appSettingNames value </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1aed10afce297eb4fe8c8600b330cf699d
  id: _slot_config_names_resource_inner_1aed10afce297eb4fe8c8600b330cf699d
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: connectionStringNames()
  fullName: List<String> com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.connectionStringNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 37
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public List< String > connectionStringNames()
    return:
      type: f35af49b
      description: <p>the connectionStringNames value </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1a331a078935593b20db1efbef4d37e0fc
  id: _slot_config_names_resource_inner_1a331a078935593b20db1efbef4d37e0fc
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: withAppSettingNames(List< String > appSettingNames)
  fullName: SlotConfigNamesResourceInner com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.withAppSettingNames(List< String > appSettingNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 67
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNamesResourceInner withAppSettingNames(List< String > appSettingNames)
    parameters:
    - id: appSettingNames
      type: f35af49b
      description: <p>the appSettingNames value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner_1a05ce239949372a2a34f09c203915d1ae
  id: _slot_config_names_resource_inner_1a05ce239949372a2a34f09c203915d1ae
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: withConnectionStringNames(List< String > connectionStringNames)
  fullName: SlotConfigNamesResourceInner com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.withConnectionStringNames(List< String > connectionStringNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 47
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNamesResourceInner withConnectionStringNames(List< String > connectionStringNames)
    parameters:
    - id: connectionStringNames
      type: f35af49b
      description: <p>the connectionStringNames value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: com.microsoft.azure._resource_1a2e102c3a5a80cabb644ef19ec31a9b9a
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: getTags()
  fullName: Map<String, String> com.microsoft.azure.Resource.getTags()
  type: Method
  summary: >-
    <p>Get the tags value.</p>

    <p></p>
  syntax:
    content: public Map< String, String > getTags()
    return:
      type: 805937fc
      description: <p>the tags value </p>
- uid: com.microsoft.azure._resource_1a00cc4f65c2d841294380d99ba4fd8782
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: id()
  fullName: String com.microsoft.azure.Resource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._resource_1ae54c7770e81b739bf0ecf42aa3881887
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: location()
  fullName: String com.microsoft.azure.Resource.location()
  type: Method
  summary: >-
    <p>Get the location value.</p>

    <p></p>
  syntax:
    content: public String location()
    return:
      type: "26831127"
      description: <p>the location value </p>
- uid: com.microsoft.azure._resource_1a0acbe5481adee4c388e642dfdfeb18e6
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: name()
  fullName: String com.microsoft.azure.Resource.name()
  type: Method
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure._resource_1aff3f1f9fe4db6f84d424cd354369e1cd
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: type()
  fullName: String com.microsoft.azure.Resource.type()
  type: Method
  summary: >-
    <p>Get the type value.</p>

    <p></p>
  syntax:
    content: public String type()
    return:
      type: "26831127"
      description: <p>the type value </p>
- uid: com.microsoft.azure._resource_1a6a1f31436a35ab46583c7e741601a2e8
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withLocation(String location)
  fullName: Resource com.microsoft.azure.Resource.withLocation(String location)
  type: Method
  summary: >-
    <p>Set the location value.</p>

    <p></p>
  syntax:
    content: public Resource withLocation(String location)
    parameters:
    - id: location
      type: "26831127"
      description: <p>the location value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource_1a832de9258cf4a03d822c4fe33db8768b
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withTags(Map< String, String > tags)
  fullName: Resource com.microsoft.azure.Resource.withTags(Map< String, String > tags)
  type: Method
  summary: >-
    <p>Set the tags value.</p>

    <p></p>
  syntax:
    content: public Resource withTags(Map< String, String > tags)
    parameters:
    - id: tags
      type: 805937fc
      description: <p>the tags value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._resource.yml
  name: Resource
  fullName: com.microsoft.azure.Resource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class Resource
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  name: SlotConfigNamesResourceInner
  fullName: com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner
  type: Class
  summary: <p>Slot Config names azure resource. </p>
  syntax: *o1
