items:
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  id: _virtual_machine_configuration
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.imageReference()
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.nodeAgentSKUId()
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.windowsConfiguration()
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.withImageReference(ImageReference)
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.withNodeAgentSKUId(String)
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.withWindowsConfiguration(WindowsConfiguration)
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: VirtualMachineConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 16
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>The configuration for compute nodes in a pool based on the Azure Virtual Machines infrastructure. </p>
  syntax: &o1
    content: public class VirtualMachineConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.imageReference()
  id: imageReference()
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: imageReference()
  fullName: ImageReference com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.imageReference()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 45
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the imageReference value.</p>

    <p></p>
  syntax:
    content: public ImageReference imageReference()
    return:
      type: com.microsoft.azure.batch.protocol.models._image_reference
      description: <p>the imageReference value </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.nodeAgentSKUId()
  id: nodeAgentSKUId()
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: nodeAgentSKUId()
  fullName: String com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.nodeAgentSKUId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 65
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the nodeAgentSKUId value.</p>

    <p></p>
  syntax:
    content: public String nodeAgentSKUId()
    return:
      type: "26831127"
      description: <p>the nodeAgentSKUId value </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.windowsConfiguration()
  id: windowsConfiguration()
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: windowsConfiguration()
  fullName: WindowsConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.windowsConfiguration()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 85
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the windowsConfiguration value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration windowsConfiguration()
    return:
      type: com.microsoft.azure.batch.protocol.models._windows_configuration
      description: <p>the windowsConfiguration value </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.withImageReference(ImageReference)
  id: withImageReference(ImageReference)
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: withImageReference(ImageReference imageReference)
  fullName: VirtualMachineConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.withImageReference(ImageReference imageReference)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 55
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the imageReference value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineConfiguration withImageReference(ImageReference imageReference)
    parameters:
    - id: imageReference
      type: com.microsoft.azure.batch.protocol.models._image_reference
      description: <p>the imageReference value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._virtual_machine_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.withNodeAgentSKUId(String)
  id: withNodeAgentSKUId(String)
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: withNodeAgentSKUId(String nodeAgentSKUId)
  fullName: VirtualMachineConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.withNodeAgentSKUId(String nodeAgentSKUId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 75
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the nodeAgentSKUId value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineConfiguration withNodeAgentSKUId(String nodeAgentSKUId)
    parameters:
    - id: nodeAgentSKUId
      type: "26831127"
      description: <p>the nodeAgentSKUId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._virtual_machine_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.withWindowsConfiguration(WindowsConfiguration)
  id: withWindowsConfiguration(WindowsConfiguration)
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: withWindowsConfiguration(WindowsConfiguration windowsConfiguration)
  fullName: VirtualMachineConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.withWindowsConfiguration(WindowsConfiguration windowsConfiguration)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 95
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the windowsConfiguration value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineConfiguration withWindowsConfiguration(WindowsConfiguration windowsConfiguration)
    parameters:
    - id: windowsConfiguration
      type: com.microsoft.azure.batch.protocol.models._windows_configuration
      description: <p>the windowsConfiguration value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._virtual_machine_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.batch.protocol.models._image_reference
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._image_reference.yml
  name: ImageReference
  fullName: com.microsoft.azure.batch.protocol.models.ImageReference
  type: Class
  summary: <p>A reference to an Azure Virtual Machines Marketplace image. </p>
  syntax:
    content: public class ImageReference
- uid: com.microsoft.azure.batch.protocol.models._windows_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._windows_configuration.yml
  name: WindowsConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.WindowsConfiguration
  type: Class
  summary: <p>Windows operating system settings to apply to the virtual machine. </p>
  syntax:
    content: public class WindowsConfiguration
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  name: VirtualMachineConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration
  type: Class
  summary: <p>The configuration for compute nodes in a pool based on the Azure Virtual Machines infrastructure. </p>
  syntax: *o1
